### ISSUE TITLE
Should WIT `createAttachment` encode filenames?

### ISSUE THREAD

**Issue by jeffwilcox** [Microsoft/azure-devops-node-api#109]
Hi,
Within the WIT client, `createAttachment` directly passes through the filename when creating an attachment. We have filenames that may contain characters that are not valid URL components, such as "a filename with a commit hash # xyz.xlsx".

We can use `encodeuricomponent` to encode the filename before passing it to the client, but I wanted to open an issue to understand whether the onus for encoding parameters such as this should fall on the client library or not.

Should the underlying library's `getVersioningData` method look to URI encode query values?

To reproduce:
With the client library, upload a file with a filename such as "magical#file.txt", _without uri encoding the filename_.

Expected: the file appears the same as if a user of VSTS uploaded a file with the same name, preserving the filename in tact. The client library takes the input value, prepares it to safely send to the REST API. The filename is preserved.

Actual:
The file receives the name "magical", truncating the rest of the filename, including the file extension.

**Comment by stephenmichaelf** [comment]
Thanks for bringing this up Jeff. The Apis are generated based on C# code that we have for REST endpoints. In order to automatically handle encoding I think we would need to add some attribute to mark the field as needing encoding. I agree that the responsibility most likely should be on the library not on the consumer. I will dig in to this.

**Comment by damccorm** [comment]
I think that this was already fixed, but if not then #226 should take care of this, the query params are all definitely URI encoded now.

**Comment by damccorm** [comment]
#226 has been submitted, so this should be working, let me know if its still causing problems. I'm going to close for now, feel free to reopen if appropriate.
