### ISSUE TITLE
Requesting a resource that does not exist returns undefined (documentation)

### ISSUE THREAD

**Issue by jakekrammer-axosoft** [Microsoft/azure-devops-node-api#137]
Code snippet:
```javascript
import vsts from 'vso-node-api';

const browserHost = 'https://{accountname}.visualstudio.com';
const authHandler = vsts.getPersonalAccessTokenHandler(oauthToken);
const connection = new vsts.WebApi(this.browserHost, authHandler);
const vstsGitApi = connection.getGitApi();

const validProjectName = 'MyProject';
const invalidRepoName = 'NotARepo';

vstsGitApi.getRepository(invalidRepoName, validProjectName)
  .then((repo) => {
   // repo === undefined
    console.log(repo);
  })
  .catch(e) {
    console.log(e); 
  };
```

Expected result: Promise to be rejected
Actual result: `repo` comes in as `undefined`

After digging into the code a bit (see below), it seems that `res` gets the correct result; however, `ret` comes back as `undefined` after formatting the response. 
https://github.com/Microsoft/vsts-node-api/blob/bdef7c9aeec1bbc8e80d42b0ce48b8269795f7b2/api/GitApi.ts#L5605-L5612

I would expect bad requests to reject rather than always resolving, so that I can handle the request errors in my application and relay the pertinent information to the user. That is what most of the other packages we work with typically do.

**Comment by bryanmacfarlane** [comment]
That's not a bad request.  A bad request is a malformed request that can't be serviced.  If it was a bad request, it would have resulted in a 400 (bad request).

This is a valid request for a resource that does not exist.  It's also not exceptional - the service correctly determined the resource by that name/id does not exist  Therefore it returns null and does not throw an exception.  

I'll add that to the docs in the repo.  It's tangentially covered here in the rest api this uses (https://github.com/Microsoft/typed-rest-client#rest)

**Comment by bryanmacfarlane** [comment]
I'm turning this into a documentation issue and assigning it to myself

**Comment by jakekrammer-axosoft** [comment]
@bryanmacfarlane I appreciate your response. I apologize for messing up the terminology. You're absolutely correct that it wasn't a bad request, just a valid request for a resource that does not exist. Looking at the documentation you linked, is it a guarantee anytime I receive `undefined` from a request that it is a 404 error? That will make it very simple to handle in our application if we can guarantee that's the case.

**Comment by bryanmacfarlane** [comment]
I believe so.  You should get the resource if it exists, undefined means it doesn't exist.  Anything else seems exceptional.

However, as I'm writing this, I'm wondering if successfully determining it doesn't exist should result in an explicit null.  

Thoughts?

**Comment by jakekrammer-axosoft** [comment]
An explicit null rather than undefined does seem preferable in my opinion. 

Also, I am a bit curious about the original design decision to treat 404 errors separately from other 4xx and 5xx errors. I can understand the reasoning behind it: the request succeeded but no resource was found so null/undefined is returned. However, it would seem from the response that it is an exceptional case in the eyes of the `typed-rest-client` package (see image below). Is there a specific reason you prefer to return null/undefined instead of having the promise reject? I only ask because I will likely have to add logic to handle each 404 to determine what part of the request could not be found. 

![screen shot 2018-01-31 at 2 09 01 pm](https://user-images.githubusercontent.com/31415703/35647671-817504d4-0690-11e8-858b-736f8b542fd5.png)

**Comment by damccorm** [comment]
Looks like we are now returning an explicit null instead of undefined. I don't think we're going to switch to the promise reject model basically because of the reason you laid out - the request was successful, even if no resource was found, meaning there is no repository there.

**Comment by damccorm** [comment]
I'm going to close since we've switched to null, feel free to reopen if you have further questions/thoughts about that decision though.

**Comment by lmmarsano** [comment]
This issue needs to be reopened.
Successfully fulfilling a 404 error is counterintuitive, and there's no documentation in sight!
How is anyone supposed to know?
Promise type signatures don't document error types.
DocComments don't cover error-cases, and those comments don't show up in editors due to their absence in published interfaces masking their presence in implementation.
