### ISSUE TITLE
getReleaseWorkItemsRefs not working properly

### ISSUE THREAD

**Issue by jycouet** [Microsoft/azure-devops-node-api#138]
Hello, 

I'm trying to get the list of Items closed between 2 releases.
I found: `getReleaseWorkItemsRefs`. ANd it seems good. It's returning me a list of item.

I saw that I forgot to link an item to the PR, so I update my completed PR with linking one more user strory... but when I run again `getReleaseWorkItemsRefs` I don't see the Item I just linked.

Is it normal?

Thank you for your help

**Comment by damccorm** [comment]
I'm going to close this for now, feel free to reopen as appropriate.
