### ISSUE TITLE
getTeamMembersWithExtendedProperties returns the incorrect type

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/azure-devops-node-api#146]
The function [`getTeamMembersWithExtendedProperties()`](https://github.com/Microsoft/vsts-node-api/blob/bdef7c9aeec1bbc8e80d42b0ce48b8269795f7b2/api/CoreApi.ts#L361) in CoreAPI is marked to return a type of [`VSSInterfaces.TeamMember[]`](https://github.com/Microsoft/vsts-node-api/blob/bdef7c9aeec1bbc8e80d42b0ce48b8269795f7b2/api/interfaces/common/VSSInterfaces.ts#L255-L258), but in reality it seems to return a type of [`VSSInterfaces.IdentityRef[]`](https://github.com/Microsoft/vsts-node-api/blob/bdef7c9aeec1bbc8e80d42b0ce48b8269795f7b2/api/interfaces/common/VSSInterfaces.ts#L132-L143) like the previous release did.

This can be verified with the following code:
```ts
this.coreApi.getTeamMembersWithExtendedProperties('foo', 'my group')
  .then((members) => {
    console.log(members);
  });
```

When viewing the logged out array, each object matches the properties of `IdentityRef` and not `TeamMember`

**Comment by chrismbarr** [comment]
We are using a self-hosted TFS.

>**Microsoft Visual Studio Team Foundation Server**
>Version 16.122.27102.1

I've made a Node JS app that would use this API to get various data about some projects and report them to Slack channels.  I had to make a few changes with the most recently update, but nothing too big.  What I mentioned above was the only thing I noticed that actually seemed to be wrong.

**Comment by stephenmichaelf** [comment]
Thanks I am digging in to this. 

During the request we do some negotiation based on version of the APIs. If I had to guess I would say perhaps this endpoint didn't maintain back compatibility. That would mean the new endpoint has a different response data structure than the old version and when the request version is negotiated to the old API version it then tries to deserialize the old data structure into the new response type. I am looking into it more deeply to see if that's what's going on.

Are you blocked on this?

**Comment by chrismbarr** [comment]
Thanks!  No, I'm not  I have a promise that returns a specific type, so for now I can just force the type.  I actually need the data that's being returned right now, so when this changes I'll have the use the commented out code befow.  Here's what I'm doing now to get around this.


```ts
getTeamMembersWithExtendedProperties(this.opts.tfsProjectCollectionId, groupName, 100, skip)
    .then((members: any[]) => { // tslint:disable-line:no-any
        //This seems to have a mismatch as to the data returned vs the typedef
        resolve(members as IdentityRef[]);
        //When fixed, use this instead
        //resolve(members.map((m: TeamMember) => m.identity));
    });
```

**Comment by stephenmichaelf** [comment]
@chrismbarr It looks like this is indeed due to a compat issue with having a newer client and an older server. The general advice is for REST API upgrades to only append data but in this case the shape of the data was changed. The team who owns this API is looking into it.

**Comment by damccorm** [comment]
I think this is something that the team is not planning on fixing. The recommendation is to use an earlier version of this API that is compatible with the version of TFS you are using.
