### ISSUE TITLE
Is it possible to check if the last commit of one branch is present on another branch?

### ISSUE THREAD

**Issue by insulind** [Microsoft/azure-devops-node-api#148]
This is a question or request?

What I want to do is check that the source branch of a pull request is update with the target branch.

I can check the behind count of the source branch however this is only relevant to the 'compare branch in vsts'. I can't see a way to change that through this API.

My other thought was to see if the target branches last commit, is present on the source branch, but I can't see a way of seeing commits by branch.

The PR has a list of commits, but if the source branch, branched over the target branch and the target branch remains unchanged. The PR's list of commits does not contain the commit it was branched off.

Any help or guidance here would be appreciated

**Comment by stephenmichaelf** [comment]
@insulind I am checking into this.

**Comment by damccorm** [comment]
@insulind this should be possible, see here: https://github.com/Microsoft/vsts-node-api/issues/149

**Comment by stephenmichaelf** [comment]
I am going to close this, let's track in #149
