### ISSUE TITLE
Enable to get commits of a branch

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/azure-devops-node-api#149]
Currently, vsts-node-api can not get commits of a branch, while REST api has this feature https://www.visualstudio.com/en-us/docs/integrate/api/git/commits#in-the-history-of-a-branch.

**Comment by stephenmichaelf** [comment]
@lvsezhufu Have you searched the entire API surface area? The GitApi here is generated based off our REST endpoint so it should have all of the same features.

**Comment by insulind** [comment]
https://github.com/Microsoft/vsts-node-api/issues/148 related to my question from a few days ago fyi

**Comment by damccorm** [comment]
@lvsezhufu I believe the getCommits function in the GitApi can do this. The second parameter takes a GitQueryCommitsCriteria object, which has an optional itemVersion field. This allows you to indicate a branch that you would like to search.

**Comment by kim-knudsen** [comment]
Specifying the `GitQueryCommitsCriteria` still has no effect for me, e.g.:

```typescript
const commits = await gitApi.getCommits(
    "repo",
    {
        $top: 100,
        itemVersion: {
            version: "dev",
            versionType: GitVersionType.Branch
        }
    },
    "project"
);
```

I only receive `master` commits. 🤔

**Comment by stephenmichaelf** [comment]
@kim-knudsen Can you turn on Fiddler and compare the HTTP requests and see what's different between the one that gets the results you want and the failing one?

**Comment by damccorm** [comment]
Looks like this was an issue with serializing nested objects that wasn't quite fully fixed. About to put a PR in that fixed it for me locally.
