### ISSUE TITLE
BeginGetLocation endpoint does not exist in TFS 2015 and causes 404.

### ISSUE THREAD

**Issue by stephenmichaelf** [Microsoft/azure-devops-node-api#153]

**Comment by stephenmichaelf** [comment]
This was first added in version 3.2 of the rest API. It did not exist yet in TFS 2015 so it won't work there. Closing.

**Comment by trinhpham** [comment]
This library mostly doesn't work with TFS 2015 now.
All WebApi.get[Component]Api() methods try to call to getResourceAreas() -> getVersioningData() -> beginGetLocation()
And because of this failing, we can't go next.
Do you have any idea for this, @stephenmichaelf ?

**Comment by stephenmichaelf** [comment]
What is the specific issue you are seeing, beginGetLocation is returning 404 and the whole thing stops?

**Comment by trinhpham** [comment]
Yes, @stephenmichaelf 
I've run the sample code and get the error as below.
You could see that the second console.log cannot be run.
![image](https://user-images.githubusercontent.com/9128061/44760017-237a5100-ab67-11e8-9a96-9de89846b237.png)

**Comment by stephenmichaelf** [comment]
Thanks @trinhpham appreciate the details. We need to add some code to handle that more gracefully if the endpoint doesn't exist.

**Comment by damccorm** [comment]
@stephenmichaelf I think that in general it might just make more sense to assume this endpoint does exist and continue to redirect TFS 2015 users to an earlier version. After v0.7.0, we start using REST 3.0 (changed in [this commit](https://github.com/Microsoft/azure-devops-node-api/commit/1864cfbb59f8cef8c6db2570611fa4d7d8e52f6b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)), which is only compatible with [TFS 2017 RTW and up](https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1#api-and-tfs-version-mapping), so we're probably going to have to redirect them to earlier versions anyways.

**Comment by damccorm** [comment]
This is related to #126, to summarize, we need this endpoint to do things like get the route and negotiate the version. Here in particular, negotiating the version is vital because the older versions of TFS will not work with the newer API. I think this has to be a no-op because of this.

I'm going to close, our recommendation here is that you just use an older version of this library that works with TFS 2015.
