### ISSUE TITLE
Please fix parameter and method names (e.g. in ExtensionManagementApi.ts)

### ISSUE THREAD

**Issue by pabrams** [Microsoft/azure-devops-node-api#163]
The parameter names are wrong, e.g. at line 32 of https://github.com/Microsoft/vsts-node-api/blob/master/api/ExtensionManagementApi.ts

`queryCollectionsByName(collectionQuery: ExtensionManagementInterfaces.ExtensionDataCollectionQuery, publisherName: string, extensionName: string`

But if I pass the extensionName the API claims it is not installed.  Passing the IDs works, though.

Refer to #162

**Comment by stephenmichaelf** [comment]
I will have to look into this, the signatures are generated based on the APIs and I just generated the most recent version to check and it still has these parameter names.

**Comment by pabrams** [comment]
A lot of the method names that end with "byName" also don't make sense; seems like the same issue:

> createDocumentByName(doc: any, publisherName: string, extensionName: string, scopeType: string, scopeValue: string, collectionName: string): Promise<any>; 
> 27     deleteDocumentByName(publisherName: string, extensionName: string, scopeType: string, scopeValue: string, collectionName: string, documentId: string): Promise<void>; 
> 28     getDocumentByName(publisherName: string, extensionName: string, scopeType: string, scopeValue: string, collectionName: string, documentId: string): Promise<any>; 
> 29     getDocumentsByName(publisherName: string, extensionName: string, scopeType: string, scopeValue: string, collectionName: string): Promise<any[]>; 
> 30     setDocumentByName(doc: any, publisherName: string, extensionName: string, scopeType: string, scopeValue: string, collectionName: string 



Looks like there was a major refactor at some point, but the symbols still need to be renamed.

And this is probably not limited to the ExtensionDataApi; that's just where I noticed it because it's what I'm working with.

**Comment by damccorm** [comment]
I'm going to close since this is on the appropriate team's backlog and isn't really an issue with this library (since we're just autogenerated from the endpoint). If appropriate, please comment and I'll reopen

**Comment by pabrams** [comment]
@damccorm Do you have a link to the Issue?

**Comment by damccorm** [comment]
No, its on that team's internal backlog so there's not a great way to provide visibility unfortunately.

As of now I don't think they've started work on this, I'll update here when they do.
