### ISSUE TITLE
addBuildTag API fails

### ISSUE THREAD

**Issue by smikula** [Microsoft/azure-devops-node-api#167]
### Environment
Node version: v8.7.0
Npm version: 
OS and version: Windows 10
vsts-node-api version: 6.3.2

### Issue Description
`addBuildTag` API fails

### Expected behaviour
API should succeed, adding a tag to the build.

### Actual behaviour
It fails with this error:
```
Error: No api-version was supplied for the "PUT" request. The version must be supplied either as part of the Accept header (e.g. "application/json; api-version=1.0") or as a query parameter (e.g. "?api-version=1.0").
```

From some quick debugging, it looks like the problem is in this line:
```
res = await this.rest.replace<string[]>(url, options);
```

`rest.replace` takes 3 arguments, and the options argument should be the *third* of them.

**Comment by stephenmichaelf** [comment]
Thanks for letting us know @smikula I will take a look.

**Comment by stephenmichaelf** [comment]
There is a bug in the API generation code for replace and update calls in the typed-rest-client. We need to pass null when there is no resources value. Working on an upstream change to fix this and will then regenerate the clients.

**Comment by damccorm** [comment]
I submitted a PR to update the generation logic, we should be able to regenerate soon and fix this.

**Comment by damccorm** [comment]
Also, this is currently being tracked in #203, I'm going to close here and continue to follow up there.
