### ISSUE TITLE
ExtensionManagementApi:  How to delete document collection?

### ISSUE THREAD

**Issue by pabrams** [Microsoft/azure-devops-node-api#176]
A document collection is automatically created when I create some documents against that collection.

I've been testing my command line interface.  After creating test documents, I delete them using IExtensionManagementApi.deleteDocumentByName (and passing document id instead of name).  

Now, the database contains a lot of empty documentCollections (in [Extension].[tbl_ExtensionDataCollection]).  How do I delete those?  I don't see an api call for that.

**Comment by stephenmichaelf** [comment]
I have reached out to find the right person to answer this question, will update you here when I know more.

**Comment by stephenmichaelf** [comment]
@pabrams This is not possible through the API right now. I created a bug for the team that owns this API. They will follow up here with more details as progress is made on the change.

Thanks for letting us know!

**Comment by damccorm** [comment]
Update, this is in the team's backlog, the current proposed solution is to delete document collections when all documents are removed from them.

**Comment by damccorm** [comment]
This has been fixed internally, you should no longer be able to create this type of doc.
