### ISSUE TITLE
Suggestion: Angular5 and vsts-node-api example

### ISSUE THREAD

**Issue by RamiSh** [microsoft/azure-devops-node-api#180]
I am wondering whether it is a good idea to include angular integration example in the sample folder? 

I have a working code that can be used as a starting point for folks who are just starting with both, angular and the vso api.

If utilizing vsts-node-api with angular is too obvious we can pass on this.

Thanks!
Rami

**Comment by damccorm** [comment]
@SeriousM sorry this slipped through the cracks a little bit

@bryanmacfarlane - thoughts on me coming back to this and trying to get this working (versus spending that time working through task issues)? I think most of the work was basically done in [this PR](https://github.com/Microsoft/typed-rest-client/pull/84), but we had reservations about merging that in without a bigger test/sample push
