### ISSUE TITLE
support no_proxy

### ISSUE THREAD

**Issue by gforceg** [Microsoft/azure-devops-node-api#183]
### Environment
Node version: 8.1.4
Npm version: 5.0.3
OS and version: Win10 x64
vsts-node-api version: tfx cli version 0.5.10 

### Issue Description

With on-prem TFS, our collection is not accessible through our proxy. This means I have to unset http_proxy before using tfx-cli. Some tools (e.g., npm, git, curl) don't require this because they obey the no_proxy environment variable convention that [wget](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) uses. Would it be difficult to support no_proxy in tfx-cli?

### Expected behaviour

vsts-node-api should ignore http_proxy if the TFS instance's domain is listed in the no_proxy variable.

### Actual behaviour

vsts-node-api does not ignore http_proxy

### Steps to reproduce

1. set http_proxy
2. add the host of your TFS instance to the no_proxy variable
3. attempt to log-in using tfx-cli
4. tfx-cli will attempt to use the http_proxy

### Logs

C:\Users\my-user-name>tfx login -u http://my-tfs-server/my-tfs-collection -t my-token
2018-04-30T18:47:56.899Z : loader.load
TFS Cross Platform Command Line Interface v0.5.10
Copyright Microsoft Corporation
error: Error: Connection failed. Check your internet connection & collection URL.
error: Message: Failed Request: Internal Server Error(500) - http://my-tfs-server/my-tfs-collection/_apis/connectionData

**Comment by gforceg** [comment]
I just discovered that passing in `--proxy ''` in the `tfx login` command works just as well as what I'm trying to do.

**Comment by japj** [comment]
The vsts-agent has a proxybypass option, perhaps this is something that could be made to behave in a consistent way? (Same configuration/behavior)

**Comment by nschonni** [comment]
@gforceg your patch looks good, are you going to submit a PR?

**Comment by gforceg** [comment]
@nschonni, I forgot I started this issue after I made the above comment regarding the --proxy argument. I'll submit the PR and see what happens.

**Comment by damccorm** [comment]
Closing because of #192
