### ISSUE TITLE
[Suggestion] Tag/Release when the final api-version is generated

### ISSUE THREAD

**Issue by nschonni** [Microsoft/azure-devops-node-api#197]
For those running on TFS rather than VSTS, being able to browse the API for the version of TFS we're using would be very helpful.
EX: From the versions listed here https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1#api-and-tfs-version-mapping
Being able to click through to the git tag of the generated API would mean we could see what the API contracts are, even if they are no longer documented under the under the https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/overview?view=tfs-2017

**Comment by damccorm** [comment]
Added a PR to start to address this, will add tags once that's in

**Comment by damccorm** [comment]
PR is in and tags have been added so I'm going to close this. Feel free to reopen if appropriate
