### ISSUE TITLE
Build definition trigger types are not DefinitionTriggerType

### ISSUE THREAD

**Issue by ethomson** [Microsoft/azure-devops-node-api#204]
vsts-node-api version: 6.5.0

### Issue Description
When I query build definitions, and request to include all properties, the returned trigger types are not `DefinitionTriggerType`s.  Unlike the return of a single build definition query, these are enums to string values, not numeric values.

Assuming that I have a build definition with a single trigger that is a pull request trigger:

```
var buildDefinitions = await vstsBuild.getDefinitions(
    project,
    undefined,
    "user/repo",
    "GitHub",
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    true)

definitions.forEach(function(definitionReference) {
    var definition = definitionReference as BuildDefinition

    definition.triggers.forEach(function (t) {
        console.log('Trigger: ' + t.triggerType)
        console.log('Trigger value: ' + t.triggerType.valueOf())
        console.log('Is a pull request? ' + (t.triggerType == DefinitionTriggerType.PullRequest))
        console.log('Is stringily a pull request? ' + (t.triggerType.toString() == 'pullRequest'))
    }
})
```

### Expected behaviour
```
Trigger: 64
Trigger value: 64
Is a pull request? true
Is stringily a pull request? false
```

### Actual behaviour
```
Trigger: pullRequest
Trigger value: pullRequest
Is a pull request? false
Is stringily a pull request? true
```

**Comment by damccorm** [comment]
Definitely looks like this is an issue with the API, not this library. Try https://dev.azure.com/{organization}/{project}/_apis/build/definitions?api-version=4.1&includeAllProperties=true. It comes back with the trigger types as strings with no additional info linking them to the enum.

Not sure if this was intentional, but it doesn't seem ideal. Regardless, might be hard to fix without breaking back-compat though.

**Comment by damccorm** [comment]
I filed a bug internally for this, will follow up here with more info as it comes

**Comment by MireilleHanna** [comment]
This is actually by design for readability. Users can bypass this through providing the header "enumsAsNumbers"

**Comment by ethomson** [comment]
It's odd that `getDefinitions` is inconsistent with `getDefinition` though.  The latter returns ints by default.

```
console.log('getDefinitions:')
var all_definitions = await buildapi.getDefinitions(
    projectName,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    true)

all_definitions.forEach(function(dr) {
  console.log('ID: ' + dr.id)
  dr.triggers.forEach(function(t) {
  console.log('Trigger: ' + t.triggerType)
  })
})

console.log('---------------------')

console.log('getDefinition:')
var def = await buildapi.getDefinition(43, "nit")
console.log('ID: ' + def.id)
def.triggers.forEach(function(t) {
  console.log('Trigger: ' + t.triggerType)
})
```

Results:
```
getDefinitions:
ID: 43
Trigger: continuousIntegration
Trigger: pullRequest
---------------------
getDefinition:
ID: 43
Trigger: 2
Trigger: 64
```

One would expect that they have the same defaults.

**Comment by damccorm** [comment]
I'm going to close here since this isn't really an issue with the library and they've decided not to change this on the API side, though a workaround has been provided.

**Comment by stephenmichaelf** [comment]
I agree that this is confusing. If it's more readable for one it should be for the other too?
