### ISSUE TITLE
UpdateRelease gives bogus error when using OAuth token

### ISSUE THREAD

**Issue by johnseghersmsft** [Microsoft/azure-devops-node-api#207]
### Environment
VSTS agent version 2.129.0 
Node version: v8.9.4
Npm version: 5.6.0
OS and version: Windows 10.0.14393 
vsts-node-api version: 6.3.2

### Issue Description
Using UpdateRelease to change the Deployment Group queueId in a Deployment Phase works when using Personal Access Token, but not when using OAuth token.

As a secondary issue, it is unclear the mapping between "Project Collection Build Service" permissions and the much more granular scopes for PATs. Also it would be helpful if the REST API documentation specified what scopes each of the APIs require.

### Expected behaviour
Operation should complete normally with either authentication method.

### Actual behaviour
Even with the "Project Collection Build Service" for the Team Project set to all "Allow", the call to updateRelease fails with the error message "Error: Deployment group with identifier 126 was not found. Either the deployment group has been deleted or no longer shared with this team project."

The deployment group has not changed and is used by other releases in the same session.

### More info
I have a master release that triggers multiple child releases. The master release has references to all of the artifacts that are used by all of the child releases. A custom StartChildRelease task does the following for each of the child releases:
1. Creates a Draft Release, matching the artifacts used in the child release to the versions specified in the master release.
2. Searches the draft release to find a specified Environment.
3. Sets the environment.deployPhasesSnapshot[0].deploymentInput.queueId to the desired target Deployment Group.
4. Calls ReleaseApi.updateRelease() to update the environment.
5. Calls ReleaseApi.updateReleaseResource to change the draft to Active
6. Calls ReleaseApi.updateReleaseEnvironment to start the child release deployment

If at step (4), the queueId is different than what was originally set in the child release definition, AND one is using the OAuth token for authentication, the error will be thrown.

### Steps to reproduce
1. Initialize vstsRelease using OAuth authentication token
2. Create a draft release
3. Change the deployment group with this code
``` Typescript
            var dps = environment.deployPhasesSnapshot[0] as any;
            dps.deploymentInput.queueId = deploymentGroupId;
            updatedRelease = await vstsRelease.updateRelease(updatedRelease, childProject, childReleaseId);

where: environment is the release environment object to be updated.
In this case, the childProject is the same as the project containing the master release.
```
Note that DeployPhasesSnapshot does not have the deploymentInput member defined. Thus the casting to "any" to be able to change the queueId value.
4. Observe Promise rejection with the above-reference error message.

If you instead use a PAT in step one (with Build (read and execute) and Release (read, write, execute and manage) scopes) then the change occurs correctly.

**Comment by damccorm** [comment]
@johnseghersmsft we recently updated to use the typed-rest-client handlers, is this still an issue? Also, have you tried using OAuth for anything else, and if so was it successful?

**Comment by damccorm** [comment]
@johnseghersmsft I'm going to close, please reopen if this is still a problem.
