### ISSUE TITLE
ReleaseApi.getReleases requires PAT with All Scopes

### ISSUE THREAD

**Issue by johnseghersmsft** [Microsoft/azure-devops-node-api#208]
### Environment
Node version: v8.9.4
Npm version: 5.6.0
OS and version: Windows 17134.228
vsts-node-api version: 6.3.2

### Issue Description
calling ReleaseApi.getReleases with a tag filter requires a PAT with the "All Scopes" option. Using "Selected scopes" and selecting all of the scopes available will not work. Thus the scope required for this API is not selectable for a PAT.

### Expected behaviour
A narrow scope, such as Release (read, write, execute, and manage) should authorize this action.

### Actual behaviour
Generates a 401 error unless "All Scopes" is selected in PAT.

### Steps to reproduce
1. Create a PAT with "Selected Scopes" and select all the scopes
2. let vstsRelease be a ReleaseApi using PAT for authorization.
3. have one or more releases with a tag, e.g. "6.130"
4. call:
``` Typescript
   var releases = await vstsRelease.getReleases(undefined, undefined, 
        undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined,
        undefined, undefined, undefined, undefined, undefined, undefined, undefined, 
        false, [parentRelease.releaseDefinition.id + "." + parentRelease.id]);

where: parentRelease.releaseDefinition.id + "." + parentRelease.id == "6.130" in the recorded case.
```
5. observe a 401 Unauthorized response. 
6. Change the PAT to "All Scopes"
7. Re-run test and it will succeed.

### Logs
```
Fiddler log of the rejected call:
GET https://encen.vsrm.visualstudio.com:443/_apis/Release/releases?isDeleted=false&tagFilter=6.130 HTTP/1.1
Accept: application/json;api-version=4.1-preview.6
User-Agent: node-Release-api
Authorization: Basic <encoded PAT>
X-TFS-FedAuthRedirect: Suppress
Host: encen.vsrm.visualstudio.com:443
Connection: keep-alive


HTTP/1.1 401 Unauthorized
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
WWW-Authenticate: Basic realm="https://rmsprodscussu1.app.vsrm.visualstudio.com/"
X-TFS-ProcessId: b257ca33-64e8-4773-9f44-c2cf884bb5a6
Strict-Transport-Security: max-age=31536000; includeSubDomains
ActivityId: 27aeb06d-eda7-4578-8589-c0aad20d7faf
X-TFS-Session: 27aeb06d-eda7-4578-8589-c0aad20d7faf
X-VSS-E2EID: 27aeb06d-eda7-4578-8589-c0aad20d7faf
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
X-Content-Type-Options: nosniff
X-MSEdge-Ref: Ref A: AA380D1B7FC64E53A21F984060446F2F Ref B: CO1EDGE0310 Ref C: 2018-09-07T21:32:00Z
Date: Fri, 07 Sep 2018 21:31:59 GMT
Content-Length: 0
```

**Comment by bryanmacfarlane** [comment]
service side issue.  not a node api issue (we're just passing the token)

please create a report on developer community: https://developercommunity.visualstudio.com/spaces/21/index.html
