### ISSUE TITLE
Query params broken with version 6.6.0?

### ISSUE THREAD

**Issue by DennisPan** [Microsoft/azure-devops-node-api#215]
### Environment
Node version: 8.11.4
Npm version: 5.6.0
OS and version: macOS High Sierra 10.13.6
azure-devops-node-api version: 6.6.0

### Issue Description
Installed most recent changes (#206). Tried this code:

```
    const pullRequests = await gitApi.getPullRequests(
        repoId,
        { status: pullRequestStatusCompleted },
        projectId
    );
```

### Expected behavior
The request is sent to `https://<account>/<project id>/_apis/git/repositories/<repo id>/pullRequests?status=3"`

### Actual behavior
The request is sent to `https://<account>/<project id>/_apis/git/repositories/<repo id>/pullRequests?status=status=3"`

### Additional notes
I tried reverting to `6.5.0` (`vso-node-api` instead of `azure-devops-node-api`), then it worked as expected.

**Comment by stephenmichaelf** [comment]
Thanks for reporting @DennisPan we will take a look today.

@damccorm Can you take a look? Let's add Nock L0s and some L1s. Can serve as samples too. We should try to make L1s that cover more of the surface area for each API.

**Comment by damccorm** [comment]
Added a PR to take care of the root issue. I'll start working on the tests as well, just figured I'd push this first since its such a simple fix.

**Comment by damccorm** [comment]
Closing this since its been resolved by the PR

**Comment by DennisPan** [comment]
Why aren't we publishing the new version to npm yet?

**Comment by damccorm** [comment]
@bryanmacfarlane Can we release this?
