### ISSUE TITLE
How to get task name and publisher whilst inside a task?

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/azure-devops-node-api#224]
I am writing an extension that has a task.  I am trying to use the ExtensionManagement Api to get documents out by name using the **getDocumentByName** method.

This method expects as arguments:

- publisher
- extensionName

The issue is that I don't want to hardcode these values.  In our release pipeline we have Dev, Preview and Release versions of the extension and the extension name changes with each of these versions.  

How can I look up these two values from within a task?

**Comment by stephenmichaelf** [comment]
Can you parse the [vss-extension.json](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts#step-2-create-the-extension-manifest-file) and get this information?

Publisher is at the root and the task name can be found in the contributions array. If your extension just has one task you can get the first item and check for the id.

**Comment by gregpakes** [comment]
Hi,

In theory yes, but as I said we have a different vss-extension.json file for dev.  So I thought it would be better if this data came from the runtime.

thanks,

Greg

**Comment by gregpakes** [comment]
Further to this - how would I do this when the filename changes during deployment?

The source file is **vss-extension.json**, but when packaged the file is **extension.vsomanifest**.

The package file also does not contain the publisher.

Is there no better way to do this?

**Comment by stephenmichaelf** [comment]
Can you pass the extension name to your release and change that value per version?

I am not sure I fully understand what you're trying to do. You're releasing your extensions but want to query the API to get the name of the extension you're trying to release?

And when you say "look up... from within a task" do you mean the task in your task definition or the task inside your extension?

If you could provide a step by step of what you're trying to do it would help :) To make sure we are on the same page.

**Comment by gregpakes** [comment]
@stephenmichaelf I appreciate you trying to help.  I will explain the situation below.

I have an extension.  This extension contains a **Pull Request Hub** and a **Release task**.

The hub puts documents into the **extensiondata** that will later be retrieved by the task.  The issue is that the API to interact with **extensiondata** is different between the hub and the task.

In the hub, you do not need to specify the publisher and extension name.  I am assuming it is handled by the api.  However, in this api, you need to pass in the publisher and the extension name.

We have a full dev, preview and production flow for this extension.  This means that the extension name changes between these different stages.  This means that I can't hardcode anything.  So I am looking for an inbuilt way that the task can get data about itself (the publisher and the extension name).

I really hope this makes sense.

**Comment by gregpakes** [comment]
I'm still blocked by this - Any ideas would be great!

**Comment by bryanmacfarlane** [comment]
We don't offer that in node-api.  I also don't think it's the role of node-api.  Node-api is a generated api of the rest apis proferred by azure-devops.

**Comment by gregpakes** [comment]
Is there a better/different repo I should be posting this to?

**Comment by bryanmacfarlane** [comment]
You're in a task that's in an extension.  You know what extension you're part of.  It's a constant.

**Comment by bryanmacfarlane** [comment]
vsts-task-lib is a better place however I still believe it's a constant, not an api
