### ISSUE TITLE
Failing to map response header value to response object.

### ISSUE THREAD

**Issue by wham** [microsoft/azure-devops-node-api#232]
My build definition has 1k+ builds over the course of the past month. Method `getBuilds()` does not return them all. My understanding is that I need to implement pagination. There is a parameter `continuationToken` but it's not clear how to set it. API response header `x-ms-continuationtoken` does not seem to be persisted by the code. Any suggestions please?

**Comment by stephenmichaelf** [comment]
Yes it looks like that header is the value you need to pass in the subsequent request. I will check on how we can update our code to map it for easy access.

**Comment by wham** [comment]
Thanks! I'm looking for a contribution, if you give me a spec how this should be done, I can try coding it. I suspect we'll have to modify https://github.com/Microsoft/typed-rest-client first, it currently does not expose the response headers.

**Comment by damccorm** [comment]
@wham I just assigned an issue to you here: https://github.com/Microsoft/typed-rest-client/issues/87

Once RestClient returns headers, it should be possible to update the autogeneration to pull them out here.

**Comment by debben** [comment]
It looks like typed-rest-client now supports returning headers. Is this ticket still in need of a contributor or is this support dependent on changes to code generation?

**Comment by damccorm** [comment]
It might need both a change here and a change in the generation. Ideally they would come in the same minor version.

What we're doing now is calling
```
let ret = this.formatResponse(res.result, null, false);
```
See [here](https://github.com/microsoft/azure-devops-node-api/blob/d6c74df97a203b684c3fa6733ab6532a71d72264/api/BuildApi.ts#L196) for an example of this.

`formatResponse` lives in the [ClientApiBase](https://github.com/microsoft/azure-devops-node-api/blob/d6c74df97a203b684c3fa6733ab6532a71d72264/api/ClientApiBases.ts#L40) file which isn't auto-generated, so we should be able to modify that.

With that said, I would prefer not to break compat, and I definitely don't want to update the return types for all the functions right now (I don't think this can be done unilaterally through the gen code, I'm not positive though).

All of that to say, this is a tricky situation and I'm not sure what the best path forward is. Right now this isn't super high priority for me, so I'm not 100% sure when I'll get the bandwidth to put the appropriate amount of thought into it. Maybe I'm missing something though, and I'm definitely open to suggestions here.

**Comment by sgerace** [comment]
I stumbled upon this issue while attempting to retrieve the complete list of agent requests (via `taskAgent.getAgentRequests`). Am I correct in my interpretation that there is no way at the moment to obtain the continuation token required to get the next page of results? Are we therefore basically limited to the number of items that we request via the `top` parameter?

**Comment by jjguijt** [comment]
I have the same problem when trying to list my organization's projects. Is there any update on this?
