### ISSUE TITLE
CoreApi: Cannot create new project with name of deleted project

### ISSUE THREAD

**Issue by alexjchapman** [Microsoft/azure-devops-node-api#234]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 10.5.0
Npm version: 6.1.0
OS and version: Windows 7
vsts-node-api version: 6.6.0

### Issue Description
I want to create a new project with the name of an old project that has been deleted from Azure Devops, but I receive an error telling me that this project already exists.

### Expected behaviour
I should be able to create a new project with the name of a project that has been deleted.

### Actual behaviour
I receive this error:
Error: TF200019: The following project already exists on the Team Foundation Server: {project-name}. You cannot create a new project with the same name as an existing project. Provide a different name.

### Steps to reproduce
1. Create a new project.
2. Delete it.
3. Try and create a new project with the same name.

### Logs
```
{ 
  '$id': '1',
  innerException: null,
  message:
   'TF200019: The following project already exists on the Team Foundation Server: {project-name}. You cannot create a new project with the same name as an existing project. Provide a different name.',

  typeName:
   'Microsoft.TeamFoundation.Core.WebApi.ProjectAlreadyExistsException, Microsoft.TeamFoundation.Core.WebApi',
  typeKey: 'ProjectAlreadyExistsException',
  errorCode: 0,
  eventId: 3000 
}
```

**Comment by stephenmichaelf** [comment]
How long was it from the time the project was deleted to the time you tried to create it with the same name? It's possible there is a delay in the actual deleting.

**Comment by stephenmichaelf** [comment]
@damccorm You had been looking into the creation queue for some of our tests, did you see anything about deleting when you looked?

**Comment by damccorm** [comment]
Hmm, I just reverified that I can still do this without errors, example code that I ran here: https://github.com/Microsoft/azure-devops-node-api/blob/b8778333948c98e689f0d25b0a50b0c152c7a9e8/samples/run.ts (this basically spins up a project, runs samples, and deletes the project. It can be run repeatedly with no issues, but the project always has the same name). Are you deleting the project with this API or via the UI? Maybe there's some difference in how it marks it deleted?

**Comment by damccorm** [comment]
I'm also using git for version control, maybe there are differences there that are causing issues. @alexjchapman would you mind providing an example create call that's failing?

**Comment by alexjchapman** [comment]
`project = {
            capabilities: {
                processTemplate: {
                    templateTypeId: "27450541-8e31-4150-9947-dc59f998fc01",
                },
                versioncontrol: {
                    sourceControlType: "git",
                },
            },
            description: "New project",
            name: projectName,
            visibility: "private",
        }`

**Comment by alexjchapman** [comment]
Our create and delete code is identical to yours, the only difference is the template type id in the project body.

**Comment by damccorm** [comment]
Ok, I tried switching to that template type id and was still able to get it to work. With that being said, I see that you have your visibility set to "private" as a string, but visibility is supposed to map to the ProjectVisibility enum. I think what you want is coreInterfaces.ProjectVisibility.Private (or just 0). Please try that and let me know if that fixes your issue.

https://github.com/Microsoft/azure-devops-node-api/blob/dad0dce0fced5512b3a2b273dd7baa734a9665db/api/interfaces/CoreInterfaces.ts#L96-L101

**Comment by damccorm** [comment]
Agreed, that's not super helpful. With that being said, my typescript compiler at least caught the issue and wouldn't let me create that object, so I'm surprised it didn't do the same for you (unless you're just using normal JavaScript). The error behavior is also an issue with the API (this library is autogenerated from a REST endpoint), I'll pass it on to them internally and close the issue here, feel free to reopen if appropriate though!

**Comment by alexjchapman** [comment]
Just realised why our typescript compiler wasn't catching this, we passed our project body as type any because my colleague didn't want to populate the _links, defaultTeam, abbreviation, id, revision, url and state fields (that you also passed in as null in your example code). Could be worth asking your guys to change those fields to be optional.

**Comment by damccorm** [comment]
Yeah, that's a pain to do, we actually have a PR in for this internally now, its being tracked here: https://github.com/Microsoft/azure-devops-node-api/issues/74
