### ISSUE TITLE
Reading package.json fails when using in VS code extension

### ISSUE THREAD

**Issue by cschleiden** [Microsoft/azure-devops-node-api#249]
When using the API in a vscode extension, package.json is not available, and creation of an API fails. 

![image](https://user-images.githubusercontent.com/2201819/47114519-e0f0fe80-d210-11e8-9451-93f3e73dc4e4.png)

As a sidenote: as a user I was very surprised that an http client library tries to read files from the disk, is that really necessary? The library should know its version without doing that.

**Comment by damccorm** [comment]
This has been fixed, see #244 - we will republish soon. And I don't know of a good way to get the library without reading from the package.json or hardcoding it, certainly open to suggestions and/or PRs though.

**Comment by cschleiden** [comment]
Why don't you encode the version when building?

**Comment by cschleiden** [comment]
It's about being predicable. I hadn't used our node API package before, and when I saw the error message about `package.json` not being found I would have never guessed - without debugging - that the error was caused by the API client. 

If you need the version of the API package, we should hardcode it during the build in `make.sh`. Basically have some `const` and replace its value with the version from this repo's package.json.
