### ISSUE TITLE
Failing to run samples

### ISSUE THREAD

**Issue by andreasblueher** [Microsoft/azure-devops-node-api#252]
### Environment
Node version:  10.11.0
Npm version: 6.4.1
OS and version: Windows Server 2016 
azure-devops-node-api version: 

### Issue Description
I'm trying to get the samples up and running. I've set the environment variables and executed npm run samples.

### Expected behaviour
Samples should run

### Actual behaviour
I get the error in the attached log file

### Logs
[node api log.txt](https://github.com/Microsoft/azure-devops-node-api/files/2513810/node.api.log.txt)

Thank your for helping

**Comment by damccorm** [comment]
I'm unable to reproduce locally, but it looks like you're getting a 401 unauthorized error. Are you sure the token you've supplied has both read and write permissions?

**Comment by andreasblueher** [comment]
Hey Daniel, let me give it fullcontrol and see if that resolves the issue. I'll come back to you.

**Comment by andreasblueher** [comment]
It appears i messed up permissions. I create a pat with full access and it worked. So I'll figure out which permission I was missing. Thank you very much
