### ISSUE TITLE
Access to Completion Options

### ISSUE THREAD

**Issue by cgosiak** [Microsoft/azure-devops-node-api#258]
### Environment
Node version: v8.12.0
Npm version: v6.4.1
OS and version: Windows 10
azure-devops-node-api version: v7.0.0

### Issue Description
When attempting to programmatically modify the "completion options" of a pull request I receive an error disallowing me to update the pull request.

### Expected behaviour
I would like to have access to modify the options available in the completionOptions section of a pull request.

### Actual behaviour
Error -> Parameter name: You can only update reviewers, descriptions, titles, merge status, and status.

### The Code
```
async function setMergeTitle(pullRequest: GitPullRequest, title: string) {
  const gitApi: GitApi = await getGitApi();
  if (pullRequest.completionOptions) {
    pullRequest.completionOptions.mergeCommitMessage = title;
  } else {
    pullRequest.completionOptions = <GitPullRequestCompletionOptions>{
      mergeCommitMessage: title
    };
  }
  await gitApi.updatePullRequest(pullRequest, pullRequest.repository.id, pullRequest.pullRequestId);
}
```

**Comment by damccorm** [comment]
This looks like an internal issue with our REST Api. I created an internal issue with the team that owns this and will post any updates here.

**Comment by damccorm** [comment]
From the team that owns this: "The only time we let you update the merge commit message is when you are completing or auto-completing a pull request. Typically we build the merge commit message from the title and description of the PR, so this is by design. When completing the PR you can set the completion options as desired."

**Comment by damccorm** [comment]
I believe if you set it and complete it at the same time you should be able to do it through the API
