### ISSUE TITLE
Creating a branch is not possible

### ISSUE THREAD

**Issue by JulianNeuberger** [Microsoft/azure-devops-node-api#259]
### Environment
Node version: v8.10.0
Npm version: -
OS and version: Ubuntu 18.04.1 LTS
azure-devops-node-api version: 7.0.0

### Issue Description
Creating a branch using `GitApi.updateRef()` is not possible, even though Azure Devops uses the `_apis/git/repositories/<repo-id>/refs` endpoint in the web view to do that.

### Expected behaviour
Calling 

```
GitApi.updateRef({
  name: `refs/head/mybranch`,
  newObjectId: "<some-commit-id>"
}, <repo-id>)
```

creates a new branch.

### Actual behaviour

```
GitApi.updateRef({
  name: `refs/head/mybranch`,
  newObjectId: "<some-commit-id>"
}, <repo-id>)
```

does not compile, since `filter` is required. Setting `filter` to the new branch name will result in error `Error: The only property which can be patched is isLocked.`

**Comment by damccorm** [comment]
UpdateRef isn't meant to create branches, it is supposed to [lock/unlock a branch](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/refs/update%20ref?view=azure-devops-rest-4.1). I think you want [createRef](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/refs/create?view=azure-devops-rest-4.1)

**Comment by JulianNeuberger** [comment]
At first I thought so as well, but documentation says

> Creates a ref favorite

Additionally the overview for the [https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-4.1](git api) links to updateRef, when you click on 

> Create, update, or delete a branch.

**Comment by damccorm** [comment]
Hm, you're right, I'm not 100% sure what the correct guidance is here. I've reached out internally to the team that owns the API (we just generate this library based on the REST Endpoints). I'll update you as I get more info.

**Comment by pasangh** [comment]
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/refs/update%20refs?view=azure-devops-rest-4.1

Update refs endpoint can be used to create a ref. You can review the sample example in the link. 
To create a new ref, the "oldObjectId" should point to "0000000000000000000000000000000000000000"

**Comment by damccorm** [comment]
Closing since @pasangh has answered the question. If appropriate, comment and I'll reopen.

**Comment by jholovacs** [comment]
How does this work if branching off a specific branch?

**Comment by jholovacs** [comment]
Is the following code correct?

```csharp
private async Task CreateBranch(GitHttpClient gitClient, GitRepository repo, string originalBranchName, string newBranchName) {
	var originalBranch =
		await gitClient.GetBranchAsync(repo.ProjectReference.Id, repo.Id, $"refs/heads/{originalBranchName}");
	var newBranch =
		await gitClient.GetBranchAsync(repo.ProjectReference.Id, repo.Id, $"refs/heads/{newBranchName}");

	if (newBranch == null)
	{
		var gitRef = await gitClient.UpdateRefAsync(new GitRefUpdate
		{
			Name = newBranchName,
			NewObjectId = originalBranch.Commit.CommitId,
			OldObjectId = "0000000000000000000000000000000000000000",
			IsLocked = false,
			RepositoryId = repo.Id
		}, repo.ProjectReference.Id, repo.Id, string.Empty);
	}
}
```

**Comment by damccorm** [comment]
I'm not 100% sure - it looks right to me. @pasangh to comment as an endpoint owner

**Comment by pasangh** [comment]
Yep, looks good to me.

**Comment by hibroseph** [comment]
@jholovacs How did you find/have access to that class GitHttpClient? I am trying to locate it to use it in an internship project I am currently involved in.

**Comment by hibroseph** [comment]
@pasangh While trying to follow the above example given by jholovacs, I keep getting an issue with the ```string.Empty``` for the filter parameter. That filter parameter is referring to unlock/locking the branch. I am not sure what I should do for that parameter.

**Comment by TofferAtNeal** [comment]
Was there ever an answer to the above question?  I'm also hitting this same issue.

**Comment by hibroseph** [comment]
I got it working for my specific use case. This is what I had to do to following @jholovacs snip.

```csharp
await gitClient.UpdateRefsAsync( new GitRefUpdate[ ] { new GitRefUpdate
{
    Name = $"refs/heads/{branchName}",
    NewObjectId = (originalBranch).Commit.CommitId,
    OldObjectId = new string('0', 40)
} }, repositoryId: (repository).Id );
```
You need to obviously grab the original branch using GetBranchAsync in the gitClient as well as have the repositoryId.

**Comment by psamerliondata** [comment]
This one will work
`public async Task<List<GitRefUpdateResult>> CreateBranch(string repositoryId, string originBranchName, string newBranchName)
{
    var repository = await _gitHttpClient.GetRepositoryAsync(repositoryId);
    var originBranch = await _gitHttpClient.GetBranchAsync(repository.ProjectReference.Id, repositoryId, originBranchName);
    var update = new GitRefUpdate
    {
        Name = $"refs/heads/{newBranchName}",
        OldObjectId = new string('0', 40),
        NewObjectId = (originBranch).Commit.CommitId,
    };
    
    var gitRef = await _gitHttpClient.UpdateRefsAsync(new GitRefUpdate[] { update }, repositoryId:repositoryId);

    return gitRef;
}`
