### ISSUE TITLE
Where is IGalleryApi?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/azure-devops-node-api#260]
Looking into adopting the latest version in [VSCE](https://github.com/Microsoft/vscode-vsce), and I can't seem to find the `IGalleryAPI` which we're using to query extensions from the Marketplace.

**Comment by damccorm** [comment]
Resolved by merging #233

**Comment by joaomoreno** [comment]
Thanks a lot! Looking forward to a release.

**Comment by damccorm** [comment]
@bryanmacfarlane can we release ```7.1.0```? The only changes should be those from #233 adding this.
