### ISSUE TITLE
IGalleryAPI.createExtension returns success when using an unknown publisher

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/azure-devops-node-api#261]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 8.10.0
Npm version: 6.4.1
OS and version: macOS 10.14.1
vso-node-api version: 6.1.2-preview

### Issue Description

Using a valid PAT, one can call `IGalleryAPI.createExtension` and attempt to create an extension with a non-existing publisher name and it the promise will return success even though nothing happens, since the publisher was never created.

From https://github.com/Microsoft/vscode-vsce/issues/311#issuecomment-445216868:

> The call to [`createExtension`](https://github.com/Microsoft/vscode-vsce/blob/6d58bca7245f4e6c82fcaaca8ec75211ba2ea64f/src/publish.ts#L73) seems to return a success, this is an issue in `vso-node-api`.
> 
> We're using `vso-node-api@6.1.2-preview` which isn't the latest. I attempted to update it to the latest version or even to the `azure-devops-node-api` package, but those options don't work because they seem to have removed functionality which VSCE uses... Created https://github.com/Microsoft/azure-devops-node-api/issues/260

### Expected behaviour

I expected the call to return a failing Promise, as it used to happen some time in the past. Not sure whether this regression was triggered by an eventual update of `vso-node-api` or a service deployment.

---

Also, in case the issue is fixed in a later version, we can't seem to update from `vso-node-api@6.1.2-preview` because https://github.com/Microsoft/azure-devops-node-api/issues/260

cc @DanielSundberg @pkuma-msft

**Comment by joaomoreno** [comment]
ping @DanielSundberg @pkuma-msft @stephenmichaelf

**Comment by damccorm** [comment]
@joaomoreno is this still an issue with #233?

**Comment by stephenmichaelf** [comment]
Closing because of #233, let's reopen if it's still an issue.

**Comment by joaomoreno** [comment]
Sorry guys, super busy... still haven't been able to catch up to this.
