### ISSUE TITLE
getCommitDiffs url parameter naming

### ISSUE THREAD

**Issue by debben** [microsoft/azure-devops-node-api#278]
### Environment
Node version: 8.7.0
Npm version: 5.4.2
OS and version: Windows 10
azure-devops-node-api version: 7.0.0

### Issue Description
When using the getCommitDiffs method with the typed parameters baseVersionDescriptor and targetVersionDescriptor, the URL parameters for these values are incorrectly translated.

```
// example.js
    let baseVersion: GitBaseVersionDescriptor = {
        baseVersion: oldCommitId,
        baseVersionType: GitVersionType.Commit
    };

    let targetVersion: GitTargetVersionDescriptor = {
        targetVersion: newCommitId,
        targetVersionType: GitVersionType.Commit
    };
   gitApi.getCommitDiffs(repositoryId, projectId, true, null, null, baseVersion, targetVersion)
```
### Expected behaviour
Per the [docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/diffs/get?view=azure-devops-rest-5.0), The getCommitDiffs method should hit an endpoint that looks like such:

/myorg/projectName/_apis/git/repositories/4f0bebd0-6488-4f6b-a449-d11d6700a4d8/diffs/commits?diffCommonCommit=true&**baseVersion**=7e95bf85fa03fb8f2d048310ec7d5ebf94200253&**baseVersionType**=2&**targetVersion**=42396331bd99fccc037b0dfbd884b51e1ef0272d&**targetVersionType**=2

### Actual behaviour
The endpoint that the method reaches out to prefixes the query string parameters for versioning with either **baseVersionDescriptor** or **targetVersionDescriptor** 
/myorg/projectName/_apis/git/repositories/4f0bebd0-6488-4f6b-a449-d11d6700a4d8/diffs/commits?diffCommonCommit=true&**baseVersionDescriptor.baseVersion**=7e95bf85fa03fb8f2d048310ec7d5ebf94200253&**baseVersionDescriptor.baseVersionType**=2&**targetVersionDescriptor.targetVersion**=42396331bd99fccc037b0dfbd884b51e1ef0272d&**targetVersionDescriptor.targetVersionType**=2

I've seen the *descriptor prefix used in other endpoints such as [items get](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-5.0). The naming used here however isn't being taken correctly by the AzureDevOps api and returns me an empty diff in which the base, target, and common commit are all the same.

**Comment by damccorm** [comment]
This looks like an inconsistency that should be addressed on the API side (we just generate this library from the REST endpoints). I'll file a bug internally, I think having the targetVersionDescriptor prefix _should_ be valid though.

**Comment by damccorm** [comment]
Unfortunately the generation code is all internal :(

**Comment by alechirsch** [comment]
I am unable to get a successful call using getCommitDiffs because of this issue. Is there a working example of getting a diff between two branches using this API?

It generates this URL: 
```
https://${org}.visualstudio.com/${project}/_apis/git/repositories/${repo}/diffs/commits?%24top=100&%24skip=1&baseVersionDescriptor.baseVersion=develop&targetVersionDescriptor.targetVersion=master
```

**Comment by damccorm** [comment]
If you cut `baseVersionDescriptor` and `targetVersionDescriptor` it should work. So your example would be:

```
https://${org}.visualstudio.com/${project}/_apis/git/repositories/${repo}/diffs/commits?%24top=100&%24skip=1&baseVersion=develop&targetVersion=master
```

I'll follow up internally to see if we can get this fixed.

**Comment by alechirsch** [comment]
@damccorm Thanks, I was able to make the call with the correct URL. But this module still generates the incorrect URL, so I cannot use it effectively.

**Comment by RickKrause** [comment]
Looking to utilize the api, but this is blocking.

**Comment by RickKrause** [comment]
Have PR open for this feature to at least patch and make function work based on supporting API...   How can we get somebody to review and approve PR?

**Comment by tylermurry** [comment]
Has there been any traction on regenerating this library with the fix? I would love to use this library but the current version (9.0.1) is simply unusable for this feature.

**Comment by alechirsch** [comment]
Is this fixed?

**Comment by bkapellusch** [comment]
Here's what I had to do to get it to work:

    const baseVersionDescriptor = {
        version: 'your first commit id',
        versionType: GitVersionType.Commit
    } as GitBaseVersionDescriptor;
    const targetVersionDescriptor = {
        versionType: GitVersionType.Commit,
        version: 'your second commit id'
    } as GitTargetVersionDescriptor;

instead of:

    const baseVersionDescriptor = {
        baseVersion: 'your first commit id',
        baseVersionType: GitVersionType.Commit
    } as GitBaseVersionDescriptor;
    const targetVersionDescriptor = {
        baseVersionType: GitVersionType.Commit,
        baseVersion: 'your second commit id'
    } as GitTargetVersionDescriptor;

The types that getCommitDiffs take are a little misleading. The implementation ignores any of the properties of the subclasses of GitVersionDescriptor.
