### ISSUE TITLE
Add unpublishExtension to GalleryApi

### ISSUE THREAD

**Issue by damccorm** [Microsoft/azure-devops-node-api#283]
Consider adding ```unpublishExtension``` to the GalleryApi (probably requires some work on the generation side).

See [here](https://github.com/Microsoft/azure-devops-node-api/pull/233/#issuecomment-451907276)

**Comment by damccorm** [comment]
@joaomoreno does an endpoint exist for ```unpublishExtension```? Or does it exist under a similar name? I wasn't able to find one and we would need that before we can generate it here.

**Comment by damccorm** [comment]
Closing after offline discussion - this can be achieved using ```updateExtensionProperties```

**Comment by nschonni** [comment]
Nice! Is there a work item to get this documented somewhere?
