### ISSUE TITLE
Create GitHub releases to match npm releases

### ISSUE THREAD

**Issue by JamieMagee** [Microsoft/azure-devops-node-api#285]
The latest version of `azure-devops-node-api` on npmjs.com is 7.0.0, however the latest GitHub release is 6.6.2. Versions 6.6.3 and 7.0.0 are missing from GitHub releases.

I would expect the releases on GitHub and npm to match.

**Comment by damccorm** [comment]
We actually use the GitHub releases and npm releases slightly differently. The npm release should map to the latest release in general. The GitHub releases map to [TFS releases](https://github.com/Microsoft/azure-devops-node-api#api-and-tfs-mapping) (a newer version of the library won't work with an older version of TFS). This is mostly just for tracking purposes (see [here](https://github.com/Microsoft/azure-devops-node-api/issues/197))

**Comment by JamieMagee** [comment]
If I understand correctly GitHub releases tag the commit where the API is generated? And do not match the package that is released to npm?

**Comment by damccorm** [comment]
Yes, GitHub releases should be a subset of packages released to npm though. I'll go ahead and document this behavior in the tags of the releases for clarity as well

**Comment by damccorm** [comment]
It should be documented more clearly now at https://github.com/Microsoft/azure-devops-node-api/releases

**Comment by JamieMagee** [comment]
I understand the need to map TFS release to `azure-devops-node-api` release, but I think that source code not matching released code is a security bug. Just look at [the `event-stream` fiasco](https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502) to see an example of this.

It is possible to have an npm package with npm releases and GitHub releases that have to match to another product's version. My team maintains [Microsoft/tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib) which maintains compatibility with tslint versions.

**Comment by damccorm** [comment]
Source code definitely does match released code - what we have published most recently on npm always matches our current source code (with 1 or 2 exceptions where development is slightly ahead of the release), and our GitHub releases match previous versions of our source code (which are available to browse). The only difference between the 2 is that we've published to GitHub less often.

Maybe I'm misunderstanding, but this feels hugely different from something like ```event-stream``` and I don't see the security issue. Frankly, the biggest reason that we have the GitHub releases is to make it easier for people to (a) figure out which release they need for TFS versions, but also (b) allow people to easily browse the source code at that point in time. This is mostly for the sake of understanding the API that existed at that point in time, but also useful for finding anything that seems insecure.

**Comment by JamieMagee** [comment]
I've clearly misunderstood, and I apologise if I came off as hostile. Can you help me to understand what the 2 newer versions on npm are for—`6.6.3`, and `7.0.0`. Is `6.6.3` a patch for TFS 2018 Update 2, and is `7.0.0` for TFS vNEXT?

**Comment by bryanmacfarlane** [comment]
When code is updated it’s gen’d from the latest code.  Code ships to hosted every 3 weeks and the same code a couple times a year builds tfs on prem.

There is no affinity of node api to any hosted or on prem.  You should just use latest node api and connect to any of them.

Service holds back and node api will negotiate down to talk to older tfs.  

Hope that helps

**Comment by JamieMagee** [comment]
Okay, thanks for taking the time to explain @bryanmacfarlane and @damccorm
