### ISSUE TITLE
error TS2503: Cannot find namespace 'NodeJS' - again

### ISSUE THREAD

**Issue by nils-a** [Microsoft/azure-devops-node-api#289]
I can't seem to get `azure-devops-node-api` working. I tried to create a minimal example:

Start new..
1. npm init
2. npm install --save-dev typescript
3. npm install --save azure-devops-node-api
4. create `index.ts` like so:
    ```
    import * as azdev from "azure-devops-node-api";

    // your collection url
    let orgUrl = "https://dev.azure.com/yourorgname";

    // ideally from config
    let token: string = "cbdeb34vzyuk5l4gxc4qfczn3lko3avfkfqyb47etahq6axpcqha"; 

    let authHandler = azdev.getPersonalAccessTokenHandler(token); 
    let connection = new azdev.WebApi(orgUrl, authHandler);   
    ```
running `tsc` yields:

> \> test1@1.0.0 build D:\_dev\test1
> \> tsc
> 
> node_modules/azure-devops-node-api/BuildApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(9,93): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(11,113): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(13,128): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(34,158): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(40,113): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(43,64): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(44,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(57,89): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(80,146): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(81,120): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(115,93): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(132,113): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(151,128): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(362,158): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(411,113): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(435,64): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(445,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(558,89): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(730,146): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/BuildApi.d.ts(738,120): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/FileContainerApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/FileContainerApi.d.ts(7,31): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/FileContainerApi.d.ts(8,125): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/FileContainerApi.d.ts(18,125): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/FileContainerApi.d.ts(19,31): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/FileContainerApi.d.ts(20,75): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/GitApi.d.ts(11,144): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(12,104): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(13,140): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(37,354): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(39,351): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(40,350): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(43,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(45,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(47,112): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(126,139): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(168,144): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(177,104): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(188,140): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(414,354): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(444,351): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(460,350): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(489,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(507,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(524,112): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/GitApi.d.ts(1250,139): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(2,23): error TS2307: Cannot find module 'http'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(3,22): error TS2307: Cannot find module 'url'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(55,58): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(56,62): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(57,51): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/interfaces/common/VsoBaseInterfaces.d.ts(58,63): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(13,183): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(14,206): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(24,100): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(49,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(50,58): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(51,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(52,178): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(53,168): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(64,105): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(70,93): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(154,183): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(166,206): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(246,100): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(443,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(450,58): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(460,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(473,178): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(485,168): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(589,105): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/ReleaseApi.d.ts(634,93): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/TaskAgentApi.d.ts(6,84): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApi.d.ts(25,114): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApi.d.ts(47,84): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(70,76): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(81,51): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(99,108): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(107,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(130,91): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(137,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(554,76): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(613,51): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(711,108): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(778,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(946,91): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskAgentApiBase.d.ts(996,116): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(8,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(10,159): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(13,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(47,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(67,159): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TaskApi.d.ts(93,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/TestApi.d.ts(13,125): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(15,121): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(16,153): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(18,149): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(20,96): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(22,92): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(179,125): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(196,121): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(206,153): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(225,149): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(241,96): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TestApi.d.ts(256,92): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(16,102): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(18,265): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(20,262): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(21,261): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(129,102): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(155,265): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(178,262): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/TfvcApi.d.ts(191,261): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WikiApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/WikiApi.d.ts(7,224): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WikiApi.d.ts(8,223): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WikiApi.d.ts(29,224): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WikiApi.d.ts(40,223): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(13,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(14,104): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(15,100): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(53,75): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(54,76): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(127,57): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(136,104): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(145,100): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(447,75): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/azure-devops-node-api/WorkItemTrackingApi.d.ts(455,76): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/HttpClient.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/typed-rest-client/HttpClient.d.ts(2,22): error TS2307: Cannot find module 'url'.
> node_modules/typed-rest-client/HttpClient.d.ts(3,23): error TS2307: Cannot find module 'http'.
> node_modules/typed-rest-client/HttpClient.d.ts(70,58): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/HttpClient.d.ts(76,62): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/HttpClient.d.ts(86,55): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/HttpClient.d.ts(93,67): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/Interfaces.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/typed-rest-client/Interfaces.d.ts(2,23): error TS2307: Cannot find module 'http'.
> node_modules/typed-rest-client/Interfaces.d.ts(3,22): error TS2307: Cannot find module 'url'.
> node_modules/typed-rest-client/Interfaces.d.ts(18,58): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/Interfaces.d.ts(19,62): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/Interfaces.d.ts(20,51): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/Interfaces.d.ts(21,63): error TS2503: Cannot find namespace 'NodeJS'.
> node_modules/typed-rest-client/RestClient.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
> node_modules/typed-rest-client/RestClient.d.ts(71,63): error TS2503: Cannot find namespace 'NodeJS'.

The old [Issue#58](https://github.com/Microsoft/azure-devops-node-api/issues/58) says:
> Installing typings should resolve this. [...]

However, the project comes with it's own typings.. So I am unsure which typings to install.

**Comment by damccorm** [comment]
I think you want to install the actual [typings module](https://www.npmjs.com/package/typings).

You may also need `typings install dt~node --global --save-dev` to save node as a global dependency.

**Comment by nils-a** [comment]
Ok. Thanks. 
As I'm kind of quirky when it comes to installing things global - and the old typings module has been deprecatd for years now, I tried `npm add --save-dev @types/node` which relsoved the issue.
