### ISSUE TITLE
Intermittent ECONNRESET errors

### ISSUE THREAD

**Issue by dmitryserbin** [Microsoft/azure-devops-node-api#292]
### Environment

Node version: 11.12
Npm version: 6.2
OS and version: Windows 2018 server (Azure DevOps release pipelines)
azure-devops-node-api version: 7.0.0 (also 6.x)

### Issue Description

I'm experiencing intermittent [ECONNRESET](https://stackoverflow.com/questions/17245881/node-js-econnreset) errors [running](https://github.com/dmitryserbin/azdev-release-orchestrator) various Build/Core/Release API methods against Azure DevOps projects or pipelines. Failure rate is about 1-2 per 100 calls.

The issue affects various APIs, for example:

- IReleaseApi > getRelease, getReleases, getReleaseDefinition, etc.
- IBuildApi > getBuild, getBuilds, getBuildTags, etc.
- ICoreApi > getProject

Basically, I'm forced to use a retry mechanism on top of the methods as a workaround:

```typescript
        let result: Build | undefined;
        let retryAttempt: number = 0;

        while (retryAttempt < retry) {
            try {
                retryAttempt++;
                // Get build
                result = await this.buildApi.getBuild(buildId, projectName);
                // Stop retrying on success
                retryAttempt = retry;
            } catch {
                console.log(`Retry retrieving build..`);
                // Delay before next retry
                await this.delay(timeout);
            }
        }
```

I do not believe there's anything wrong with your code, but please advise if it's possible to address these type of issues on the library level? For example, by introducing a native retry mechanism (or anything else you could recommend).

### Expected behaviour

API should return response.

### Actual behaviour

ECONNRESET thrown.

### Steps to reproduce

It is challenging to reproduce as you need need to be very lucky. The task I'm running in a pipeline is making >100 call per ~5 min. I have never experienced this issue locally - it only happens in Azure DevOps pipelines.

### Logs

Not much logs at this point, but I can get some, if needed.

```
2019-03-16T16:06:07.4473715Z ##[error]read ECONNRESET
```

**Comment by stephenmichaelf** [comment]
We just added a PR to the rest-client that this library uses and it should be incorporated here soon!

@damccorm

**Comment by dmitryserbin** [comment]
Awesome, that should do, thanks a lot

**Comment by dmitryserbin** [comment]
Just to follow up on this @stephenmichaelf @damccorm - it seems like retry isn't really working as we're still experiencing ECONNRESET errors.

`
2019-05-15T00:07:05.4224798Z ##[warning]read ECONNRESET
`

```javascript
const options = {
            allowRetries: true,
            maxRetries: 20,
        } as vi.IRequestOptions;

this.webApi = new az.WebApi(endpoint.url, auth, options);
```

```json
"dependencies": {
    "@types/cli-table": "^0.3.0",
    "@types/debug": "^4.1.4",
    "azure-devops-node-api": "^8.0.0",
    "azure-pipelines-task-lib": "^2.8.0",
    "cli-table": "^0.3.1",
    "debug": "^4.1.1",
    "moment": "^2.24.0"
  },
```

**Comment by stephenmichaelf** [comment]
Are the logs showing that there were 20 retries?

**Comment by dmitryserbin** [comment]
I don't think is retrying at all @stephenmichaelf. I will try to reproduce it and come back to you with some logs.

**Comment by stephenmichaelf** [comment]
@dmitryserbin Where did you end up landing on this?

**Comment by dmitryserbin** [comment]
@stephenmichaelf I couldn't get the retry mechanism properly working, so I ended up writing a little retry [decorator](https://github.com/dmitryserbin/azdev-release-orchestrator/blob/master/OrchestratorV1/retry.ts) for to use with the get methods.

It is quite tricky to troubleshoot and reproduce as the issue is intermittent. And I cannot enable debug mode for long period of time to catch the issue as it slows the pipelines down quite a lot.

Manual (i.e. using decorator) retry works perfectly so far. I am hoping to get back to this issue and pull some logs, but not sure when.

**Comment by mastrzyz** [comment]
I did some digging , it looks like the retry mechanism from the rest client in usage looks at status codes to determine if we should retry while this error is an exception raised by the 'http','https' libraries themselves : https://github.com/microsoft/typed-rest-client/issues/220
