### ISSUE TITLE
No children in GetQueries

### ISSUE THREAD

**Issue by TheDarkBoz** [Microsoft/azure-devops-node-api#298]
### Environment
Node version: 11.13.0
Npm version: 6.7.0
OS and version: Windows 10
azure-devops-node-api version:  Azure Devops Server 2019

### Issue Description
When I use the api for Get Querries, I have my 2 root queries.
But I dont have theirs children.
I have checked with browser debugger I don't have the propriety while the propriety hasChildren is okay

### Steps to reproduce
I use following code : 
`VSS.require(["TFS/WorkItemTracking/RestClient"],
			function(WitRestClient) {
				CurrentProject = VSS.getWebContext().project.name;
				client = WitRestClient.getClient();
				client.getQueries(CurrentProject).then(
					function(Queries) {
						Tree(Queries);
					});
			});
			function Tree(Queries)
			{
				debugger;
				for(var index = 0;index<Queries.length;index++)
				{
					client.getQuery(CurrentProject,Queries[index].name).then(
					function(Query) {
						debugger;
					});
					var out = '';
					for (var i in Queries[index]) {
						out += i + ": " + Queries[index][i] + "\n";
					}
					alert(out);
					if(Queries[index].hasChildren)
					{
						alert(Queries[index].children);
						/*Tree(Queries[index].children);*/
					}
					alert(Queries[index].name);
				}
			}`

I have tried this 

http://localuri/tfs/Collection/ProjectName/_apis/wit/queries?$depth=1&api-version=5.0
(because it is on premise) and it is okay I have the children.

https://docs.microsoft.com/fr-fr/rest/api/azure/devops/wit/queries/get?view=azure-devops-rest-5.0

**Comment by stephenmichaelf** [comment]
Are you able to get this working with raw HTTP queries from something like Postman? This library is just a wrapper around the APIs. 

@damccorm can you take a quick look? If it's not readily apparent let's route to API owners.

**Comment by TheDarkBoz** [comment]
I have 401 with postman...

**Comment by TheDarkBoz** [comment]
I am sorry, I found my mistake.
I have the children if add the parameter depth with the value 1 or 2 (not 0)
I replaced 
`client.getQueries(CurrentProject)`
by
`client.getQueries(CurrentProject,'All',2)`

**Comment by damccorm** [comment]
Ok, great! I'm going to close since it seems like you've resolved this, if not feel free to comment and I'll reopen!
