### ISSUE TITLE
Cannot contribute to pull request from a pipeline custom task

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-devops-node-api#300]
### Environment
OS and version: Azure DevOps Services
azure-devops-node-api version: 7.2.0

### Issue Description
I am trying to create an Azure DevOps custom pipeline task that will add a message to a specified pull request.

### Expected behaviour
It should be added.

### Actual behaviour

Receive an error message

> TF401027: You need the Git 'PullRequestContribute' permission to perform this action. Details: identity 'Build\XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', scope 'repository'.

### Steps to reproduce
1. Create a custom task with the code [here](https://gist.github.com/MisinformedDNA/419727768593aafd36fb002e95f8fca9)
2. Add task to a release pipeline
3. Execute pipeline
4. Observe errored log
5. Check box "Allow scripts to access the OAuth token" in pipeline job and try again.

### Logs

> TF401027: You need the Git 'PullRequestContribute' permission to perform this action. Details: identity 'Build\XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', scope 'repository'.

![image](https://user-images.githubusercontent.com/1784452/55645924-783a1600-579f-11e9-8d92-8f99a7c9e5ad.png)

I've also created a [SO question](https://stackoverflow.com/questions/55501786/authentication-to-access-other-parts-of-azure-devops-within-a-custom-task) for this.

**Comment by stephenmichaelf** [comment]
Please try using System.AccessToken.

**Comment by MisinformedDNA** [comment]
This results in the same error:

```javascript
var token = tl.getVariable('System.AccessToken');
var credHandler = vsts.getBearerHandler(token);
var connection = new vsts.WebApi(tl.getVariable('System.TeamFoundationCollectionUri'), credHandler);
```

**Comment by damccorm** [comment]
I believe `System.AccessToken` is actually for PAT auth. With that said, I'm not able to reproduce - lots of our built in tasks use the same way of getting Bearer Auth as you (e.g. nuget tasks that use [locationUtilities](https://github.com/Microsoft/azure-pipelines-tasks/blob/261a0f87ab7f9911df2055ef2628c129188946fe/Tasks/Common/packaging-common-old/locationUtilities.ts#L119)).

A couple things you could try:
1) Is the auth scheme you're getting back OAuth? If not you should be using the appropriate authentication method.
2) Are you able to create an ad-hoc query with something like postman (or anything that isn't this library) - https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20threads/create?view=azure-devops-rest-5.0. My inclination is that this isn't an issue with this library since lots of things are using OAuth without issue, but this would confirm one way or the other. From there we can figure out where exactly the issue is coming from.

**Comment by MisinformedDNA** [comment]
1. Am I using OAuth? I think I'm using OAuth. I checked the "Allow scripts to access the OAuth token" box and am accessing 'System.AccessToken'.
2. Yep. I used Postman to create a pull request thread without any issue (using a PAT). Also, I was able to create a work item using the same token and the same library, with no issue.

**Comment by MisinformedDNA** [comment]
I verified the schema is OAuth. I never set up a PAT, so I have to assume it was OAuth, but I'm working on recreating the "create work item" code so I can verify that.

**Comment by MisinformedDNA** [comment]
I guess I never created a work item directly through the library. I was actually using the [Create Work Item](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/CreateWorkItem/en-US/overview.md) task from MS Premier, which uses essentially the same code as me (so both should be OAuth):

```javascript
let auth = tl.getEndpointAuthorization('SystemVssConnection', false);
let credHandler = wa.getBearerHandler(auth.parameters['AccessToken']);
let webApi = new wa.WebApi(tl.getVariable('System.TeamFoundationCollectionUri'), credHandler);
```

I would agree that there seems to be a permissions issues somewhere, but besides the permissions in the image in the OP, I'm not sure what other related permissions exist.

**Comment by damccorm** [comment]
@MisinformedDNA sorry I lost track of this one. Have you made any progress?

One thing you could check is if you've restricted access at the org level. Beyond that, I'm not sure how much help I can give you on this one without seeing your security settings unfortunately. 

![image](https://user-images.githubusercontent.com/42773683/57323333-9b742000-70d3-11e9-97c4-06ead418e496.png)

**Comment by MisinformedDNA** [comment]
The solution was to add the "Project Collection Build Service" user to the “Project Collection Build Service Accounts” security group. Seems strange that the user isn't a member by default.

**Comment by zarochi** [comment]
I just wanted to jump in and thank @MisinformedDNA for the diagnosis and notes. I had the same issue, but once I added "Project Collection Build Service" to "Project Collection Build Service Accounts" and granted that group permission to "contribute to pull requests" on the project this all worked.

**Comment by binte** [comment]
I am still getting the same error, on Azure DevOps, after having:

- Checked box "Allow scripts to access the OAuth token" in pipeline job and try again.
- Added the "Project Collection Build Service" user to the “Project Collection Build Service Accounts” security group, under the Organisation level permissions.

What am I missing here?

**Comment by demyte** [comment]
@binte  You will also need to give the user that is created called `<Project> Build Service (<Org>)` access to contribute to pull requests as per this SO article > https://stackoverflow.com/questions/60048492/raise-a-comment-in-azure-devops-pr

![image](https://user-images.githubusercontent.com/48166/86875029-f0bb1f80-c124-11ea-895a-f6b3a164a957.png)

**Comment by cjsio** [comment]
> @binte You will also need to give the user that is created called `<Project> Build Service (<Org>)` access to contribute to pull requests as per this SO article > https://stackoverflow.com/questions/60048492/raise-a-comment-in-azure-devops-pr
> 
> ![image](https://user-images.githubusercontent.com/48166/86875029-f0bb1f80-c124-11ea-895a-f6b3a164a957.png)

Thank you for this annotated screenshot showing that these permissions are disjointed from `General -> Permissions` inside of `Repos`. It is worth noting that as of the time of writing, Azure has renamed the `Permissions` tab to `Security` in the `Repositories` section.
