### ISSUE TITLE
Git pull request thread api methods are named inconsistently

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-devops-node-api#301]
The way methods are named in IGitApi is inconsistent. Take a look at these methods that all apply to `GitPullRequestCommentThread`:

- `createThread`
- `updateThread`
- `getPullRequestThread`
- `getThreads`

Why do 3 out of the 4 definition names omit "PullRequest"?

See https://github.com/Microsoft/azure-devops-node-api/blob/master/api/GitApi.ts#L109-L112

**Comment by stephenmichaelf** [comment]
Danny can you take a look at our generation? I don't think we do any modification to decide how methods should be named.

**Comment by damccorm** [comment]
Yeah, we don't, this comes directly from the endpoint (which we don't own).

Obviously this isn't great, I'm not sure that its worth introducing breaking changes to fix this though. Could be a good candidate to try to fix next time we do a new API version.

**Comment by MisinformedDNA** [comment]
[Get single](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20threads/get?view=azure-devops-rest-5.0) and [get list](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20threads/list?view=azure-devops-rest-5.0) don't look like they are named differently at the API level:

```
https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}?api-version=5.0
https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads?api-version=5.0
```

**Comment by damccorm** [comment]
Sorry, should have been more clear - this comes from the internal endpoint **controller** code from which this API is generated (not the endpoint itself)

**Comment by damccorm** [comment]
As I rethink this, probably not worth breaking back compat for naming consistency - I'm going to close here. Feel free to comment if you'd like me to reopen
