### ISSUE TITLE
Use different user agents

### ISSUE THREAD

**Issue by simondel** [Microsoft/azure-devops-node-api#302]
### Environment
Node version:  10.x
Npm version: 6.x
OS and version: Windows Server 2016 DC
azure-devops-node-api version: 6.0.1-preview

### Issue Description
The current Api's use a user agent that's quite odd. For example, the `CoreApi` uses user agent `node-Core-api`: https://github.com/Microsoft/azure-devops-node-api/blob/master/api/CoreApi.ts#L55

This makes it quite difficult to use user agent whitelisting on firewalls to ensure that Azure DevOps agents work through a firewall.

### Expected behaviour
Requests done using the user agent of the Azure DevOps agent such as `vsservices`.

### Actual behaviour
Requests are done using different user agents.

**Comment by damccorm** [comment]
Can you just whitelist things that follow the pattern `node-*-api`? I believe all the APIs follow that pattern (and that's consistent across our clients in other languages as well).

As a side note, the user agent is really easy to spoof if that matters to you, so I'd be careful making any security assumptions there.

**Comment by simondel** [comment]
I agree it's not a great thing to use. However, I would expect there to be some notion of Azure DevOps in the user agent of this module to indicate its purpose/make.

**Comment by damccorm** [comment]
That doesn't seem obvious to me. The user agent is primarily used to identify the user (client), not the service its connecting to. In this case, we're connecting to Azure DevOps so it feels redundant to have that in the name.

For the reasons I mentioned above, I'd explicitly recommend against doing something like whitelisting based on user agent, outside of that I don't see much reason to change this (and we're consistent with our naming so you can still do the type of exclusion I mentioned if you **really** want to).

**Comment by damccorm** [comment]
I'm going to close, please comment if you have further thoughts and/or would like me to reopen
