### ISSUE TITLE
Samples do not work

### ISSUE THREAD

**Issue by MisinformedDNA** [Microsoft/azure-devops-node-api#303]
### Environment
Node version: 8.11.1
Npm version: 6.0.1
Tsc version: 3.4.1
OS and version: Win10 1803
azure-devops-node-api version: Git cloned master branch

### Issue Description
I can't get the samples to run.

### Expected behaviour
Samples run successfully

### Actual behaviour
Errors out

### Steps to reproduce
1. git clone
2. cd into directory
3. npm install
4. npm run samples

### Logs

> C:\repos\azure-devops-node-api-2> npm run samples
> 
> > azure-devops-node-api@7.3.0 samples C:\repos\azure-devops-node-api-2
> > node make.js samples
> 
> > tsc --outDir C:\repos\azure-devops-node-api-2\_build
> C:\repos\azure-devops-node-api-2\samples C:\repos\azure-devops-node-api-2
> > npm install ../_build
> npm WARN vsts-node-api-samples@1.0.0 No repository field.
> 
> + azure-devops-node-api@7.3.0
> added 4 packages from 8 contributors in 2.236s
> [+] no known vulnerabilities found [6 packages audited]
> 
> C:\repos\azure-devops-node-api-2
> > tsc -p samples
> samples/workItemTracking.ts(70,53): error TS2551: Property 'getWorkItemTypeFields' does not exist on type 'IWorkItemTrackingApi'. Did you mean 'getWorkItemTypeColors'?
> C:\repos\azure-devops-node-api-2\node_modules\shelljs\src\common.js:417
>       if (config.fatal) throw e;
>                         ^
> 
> Error: exec: internal error
>     at Object.error (C:\repos\azure-devops-node-api-2\node_modules\shelljs\src\common.js:128:27)
>     at _exec (C:\repos\azure-devops-node-api-2\node_modules\shelljs\src\exec.js:292:12)
>     at C:\repos\azure-devops-node-api-2\node_modules\shelljs\src\common.js:350:23
>     at run (C:\repos\azure-devops-node-api-2\make.js:13:14)
>     at Function.target.samples (C:\repos\azure-devops-node-api-2\make.js:67:5)
>     at Object.global.target.(anonymous function) [as samples] (C:\repos\azure-devops-node-api-2\node_modules\shelljs\make.js:36:40)
>     at C:\repos\azure-devops-node-api-2\node_modules\shelljs\make.js:48:27
>     at Array.forEach (<anonymous>)
>     at Timeout._onTimeout (C:\repos\azure-devops-node-api-2\node_modules\shelljs\make.js:46:10)
>     at ontimeout (timers.js:482:11)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! azure-devops-node-api@7.3.0 samples: `node make.js samples`
> npm ERR! Exit status 1

To fix, I changed

```
witApi.getWorkItemTypeFields
```

to

```
witApi.getWorkItemTypeFieldsWithReferences
```

and reran `npm run samples` but I get a permissioning error:

> > tsc -p samples
> C:\repos\azure-devops-node-api-2\samples C:\repos\azure-devops-node-api-2
> > node run.js
> Hello XXXXX XXXXX
> 
> > Creating example project
> Cleaning up from last run
> Nothing to clean up
> (node:12364) UnhandledPromiseRejectionWarning: Error: Failed request: (401)
>     at RestClient.<anonymous> (C:\repos\azure-devops-node-api-2\_build\node_modules\typed-rest-client\RestClient.js:200:31)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\repos\azure-devops-node-api-2\_build\node_modules\typed-rest-client\RestClient.js:6:58)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:12364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:12364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> C:\repos\azure-devops-node-api-2

Note that it shows I'm authenticated with the "Hello" message, but then I get a 401 anyway. I'm using a PAT with full access.

Is it user error? Or is something broken?

**Comment by damccorm** [comment]
Yeah, this is broken, I noticed the same thing the other day. It should be fixed as part of #294

**Comment by MisinformedDNA** [comment]
After switching branches to regen branch (commit bf4d95181fc686cbb701ed28b6c4f98c4e8add67) and running `npm install` and then `npm run samples`, the errors were identical.

**Comment by MisinformedDNA** [comment]
If we can get this fixed quickly, I would greatly appreciate it. I am running into issues trying to create a custom pipeline task and am being able to run this successfully would help me validate what I am doing.

**Comment by damccorm** [comment]
Whoops, had local files that I didn't check in. We can just fix this separately, I just added a PR.

The auth issue is different, I'm not running into it and it definitely indicates that somehow you don't have the right permissions. I'm guessing that this is the same issue as #300, though I'm still not 100% sure what is causing that.

**Comment by MisinformedDNA** [comment]
Upon further investigation, I realized that I didn't initially know that my PAT needed Full Access so it was missing some permissions.

On a side note: I also saw some deletions. Is the sample only reading from the project set by API_PROJECT?

So the samples ran quite well, but fails with

> =======================================
>         Sample profile
> =======================================
> Hello XXXXX XXXXX
> (node:14288) UnhandledPromiseRejectionWarning: Error: Could not find information for resource area 8ccfef3d-2b87-4e99-8ccb-66e343d2daa8 ' + 'from server: https://dev.azure.com/XXXXX
>     at WebApi.<anonymous> (C:\repos\azure-devops-node-api-2\_build\WebApi.js:402:19)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\repos\azure-devops-node-api-2\_build\WebApi.js:6:58)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:14288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:14288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> C:\repos\azure-devops-node-api-2
> done
>

**Comment by damccorm** [comment]
I'm running into this as well - it looks like an issue on the backend with the profile resource area, probably the same root cause as #245 (which I thought was fixed). I'll take a look at it.
