### ISSUE TITLE
queryTestResultsReportForBuild does not return all data

### ISSUE THREAD

**Issue by NxSoftware** [microsoft/azure-devops-node-api#305]
### Environment
Node version: 11.9.0
Npm version: 6.9.0
OS and version: macOS 10.14.4
azure-devops-node-api version: 7.2.0

### Issue Description

The response object received from the Test API `queryTestResultsReportForBuild` method does not contain all of the data in the raw JSON response.

The following code reproduces the issue:

```ts
import * as azure from "azure-devops-node-api";

async function run() {
    let authHandler = azure.getPersonalAccessTokenHandler(AZURE_TOKEN);
    let api = new azure.WebApi(ORG_URL, authHandler);
    let tests = await api.getTestApi();

    let results = await tests.queryTestResultsReportForBuild(PROJECT, BUILD_ID);

    console.info("results:");
    console.info(results);

    console.info("resultsByOutcome:");
    console.info(results
        .aggregatedResultsAnalysis
        .resultsByOutcome);
}

run();
```

Furthermore, using the `WebApi.rest` object we can access the endpoint and successfully retrieve the data:

```ts
let getresult = await this.api.rest.get(this.ORG_URL + '/_apis/test/ResultSummaryByBuild/?buildId=129942');

console.info(getresult.result['aggregatedResultsAnalysis']['resultsByOutcome']);
```

### Expected behaviour

The `AggregatedResultsAnalysis` object contains all child data as available in the JSON response.

### Actual behaviour

The `AggregatedResultsAnalysis` does not appear to correctly parse the `*by*`objects, e.g. `resultsByOutcome`. Rather than the dictionary containing key/value pairs for Passed, Failed etc, it simply contains a single key, `false`. See the results of the above script:

```ts
results:
{ aggregatedResultsAnalysis:
   { previousContext: { contextType: 0, build: null, release: null },
     resultsDifference:
      { increaseInTotalTests: 0,
        increaseInFailures: 0,
        increaseInPassedTests: 0,
        increaseInOtherTests: 0,
        increaseInDuration: '00:00:00.1270000' },
     totalTests: 42,
     duration: '00:00:14.7000000',
     resultsByOutcome: { false: [Object] },
     runSummaryByState: { false: [Object] },
     runSummaryByOutcome: { false: [Object] } },
  testResultsContext:
   { contextType: 1,
     build:
      { id: 129942,
        definitionId: 0,
        uri: 'vstfs:///Build/Build/129942' },
     release: null },
  teamProject:
   { id: 'f8ec5762-87b0-4a80-bb4d-117c41ddc8a8',
     name: 'Mobile',
     state: 'unchanged',
     visibility: 0,
     lastUpdateTime: '0001-01-01T00:00:00' } }

resultsByOutcome:
{ false: { outcome: 3, count: 1, duration: '00:00:00.1960000' } }
```

The raw JSON response from Postman to the `/_apis/test/ResultSummaryByBuild/?buildId=129942` endpoint contains the full information:

```json
{
    "aggregatedResultsAnalysis": {
        "previousContext": {
            "contextType": 0,
            "build": null,
            "release": null
        },
        "resultsDifference": {
            "increaseInTotalTests": 0,
            "increaseInFailures": 0,
            "increaseInPassedTests": 0,
            "increaseInOtherTests": 0,
            "increaseInDuration": "00:00:00.1270000"
        },
        "totalTests": 42,
        "duration": "00:00:14.7000000",
        "resultsByOutcome": {
            "Passed": {
                "outcome": "passed",
                "count": 41,
                "duration": "00:00:02.0290000"
            },
            "Failed": {
                "outcome": "failed",
                "count": 1,
                "duration": "00:00:00.1960000"
            }
        },
        "runSummaryByState": {
            "Completed": {
                "state": "completed",
                "runsCount": 1,
                "resultsByOutcome": {
                    "Passed": {
                        "outcome": "passed",
                        "count": 41,
                        "duration": "00:00:02.0290000"
                    },
                    "Failed": {
                        "outcome": "failed",
                        "count": 1,
                        "duration": "00:00:00.1960000"
                    }
                }
            }
        },
        "runSummaryByOutcome": {
            "Failed": {
                "outcome": "failed",
                "runsCount": 1
            }
        }
    },
    "testResultsContext": {
        "contextType": "build",
        "build": {
            "id": 129942,
            "definitionId": 0,
            "uri": "vstfs:///Build/Build/129942"
        },
        "release": null
    },
    "teamProject": {
        "id": "f8ec5762-87b0-4a80-bb4d-117c41ddc8a8",
        "name": "Mobile",
        "state": "unchanged",
        "visibility": "unchanged",
        "lastUpdateTime": "0001-01-01T00:00:00"
    },
    "totalRunsCount": 1
}
```

### Steps to reproduce
See sample script and response.

**Comment by stephenmichaelf** [comment]
@damccorm Can you take a look? Let's confirm the rest calls are exactly the same then we can look at potentially changing the objects the result is deserialized into.

**Comment by damccorm** [comment]
I'm able to repro.

If you add the following logging to queryTestResultsReportForBuild:

```
console.log('------------------------------------');
console.log('res.result');
console.log(res.result['aggregatedResultsAnalysis']['resultsByOutcome']);
console.log('------------------------------------');

let ret = this.formatResponse(res.result,
                              TestInterfaces.TypeInfo.TestResultSummary,
                              false);
                
console.log('------------------------------------');
console.log('ret');
console.log(ret['aggregatedResultsAnalysis']['resultsByOutcome']);
console.log('------------------------------------');
```

You get:
```
------------------------------------
res.result
{ Passed:
   { outcome: 'passed', count: 504, duration: '00:00:44.4440000' } }
------------------------------------
------------------------------------
ret
{ false: { outcome: 2, count: 504, duration: '00:00:44.4440000' } }
------------------------------------
```

So this is pretty clearly an issue with our serialization (note that changing the outcome from 'passed' to 2 is fine since that's an enum, the issue is just with the Passed to false). I'm taking a look now

**Comment by damccorm** [comment]
Ok, I've figured out the source of the problem. When we deserialize the object, we rely on the provided types. The [way we define our types](https://github.com/Microsoft/azure-devops-node-api/blob/6f647c7f9a1a96c710ab478a139d1c3847f00d6c/api/interfaces/TestInterfaces.ts#L4587), we have a structure that should map `{ Passed: { outcome: 'passed', count: 504, duration: '00:00:44.4440000' } }` to `{ TypeInfo.TestOutcome: TypeInfo.AggregatedResultsByOutcome }`. 

The `AggregatedResultsByOutcome` matches `{ outcome: 'passed', count: 504, duration: '00:00:44.4440000' }` correctly, but `TypeInfo.TestOutcome` maps to a [case sensitive enum](https://github.com/Microsoft/azure-devops-node-api/blob/6f647c7f9a1a96c710ab478a139d1c3847f00d6c/api/interfaces/TestInterfaces.ts#L4366) which has an entry for `'passed'` but not `'Passed'`.

I think our deserializer is actually doing the right thing here, string enum keys like this should be case sensitive. On the API side we need to maintain case sensitivity and return 'passed' as the key value instead of 'Passed'. I'll file a bug with the appropriate team.

**Comment by puagarwa** [comment]
@NxSoftware  can you validate the fix and help to close if issue is fixed.

**Comment by saikrishnav** [comment]
@puagarwa  - Any idea what release this fix would go in? (if not already)

**Comment by damccorm** [comment]
@bryanmacfarlane can we release `9.0.2`?

**Comment by puagarwa** [comment]
@damccorm  can you please confirm if this is already released ?

@saikrishnav  are you able to validate it ?

**Comment by saikrishnav** [comment]
@puagarwa  - The way I validated this is that I published my task by manually editing the file fix in question under node_modules so that my task gets published with the fix. It has been working in the last sprint. Can we release this already?

**Comment by puagarwa** [comment]
@damccorm can you help to release new version of this package, or add someone who can help here.
