### ISSUE TITLE
Investigate caching location data

### ISSUE THREAD

**Issue by stephenmichaelf** [microsoft/azure-devops-node-api#308]
Today we don't cache location data.

https://github.com/Microsoft/azure-devops-node-api/blob/8ba98263f6e0673c08e990f46bbfb64d4c0a0a9c/api/WebApi.ts#L404

The other clients, C# and Python, do cache data to disk to reduce the number of calls.

The Python client has a 24 hour expiration.

Let's investigate how those other client libraries work, how it might work in this lib, how long it will take, etc.

**Comment by damccorm** [comment]
From offline discussion - not sure if this actually adds value so I'm going to close. If anyone disagrees feel free to comment and we can reopen/discuss
