### ISSUE TITLE
Requesting git blame feature

### ISSUE THREAD

**Issue by jarmit** [Microsoft/azure-devops-node-api#309]
I would like an api where I can pass in a file path and a line number, and it will return the commits or latest commit that changed that line on that file path.

**Comment by damccorm** [comment]
This library is almost entirely generated from the endpoints listed [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0&viewFallbackFrom=vsts-rest-4.1), so we can't do much about that request until an endpoint exists. 

Would you mind logging your request with the developer community [here](https://developercommunity.visualstudio.com/spaces/21/index.html)? That way it gets routed to the appropriate people and has a better chance of getting added

**Comment by damccorm** [comment]
I'm going to close since there's nothing we can do about this in this library. Feel free to comment if you'd like me to reopen

**Comment by jarmit** [comment]
Thanks @damccorm. I will post this comment on the azure devops developer community!
