### ISSUE TITLE
Add service endpoint api

### ISSUE THREAD

**Issue by shudv** [microsoft/azure-devops-node-api#310]
### Environment
Node version: 10.14.2
Npm version: 6.4.1
OS and version: Windows 10 Build 18890
azure-devops-node-api version: 7.2.0

### Issue Description
The `getConnectedServices` and `getConnectedServiceDetails` api's in Core interface do not seem to be working. 

### Expected behaviour
I created a custom service connection instance in my ado account. Using [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/get%20service%20endpoints%20by%20names?view=azure-devops-rest-5.0) api I am able to see that the endpoint exists. I should see the same data through the Core API in this library.  

### Actual behaviour
The call to `getConnectedServiceDetails` completes with no data or error.

**Comment by damccorm** [comment]
I can't get a repro, would you mind trying the request from the lib using Fiddler and trying it from the endpoint and diffing the two to see what's different?

**Comment by shudv** [comment]
Sure. It's night time here in India so will try this next morning and report back. Thanks for the suggestion. :)

**Comment by shudv** [comment]
@damccorm, I have been trying to do what you suggested but for some reason I haven't been able to get Fiddler to capture the packets from my process or the browser. I will keep trying to see what I am doing wrong but until then I will lay out some investigation info from my end hoping that it might give you some insight into the problem.

- This is most likely not because of some weird network configuration issue specific to my machine because the behavior is the same on an hosted ADO agent.
- Other thing that I noticed was that `coreApi.getConnectedServices("MY_PROJECT_NAME")` returns no data but does not fail whereas `coreApi.getConnectedServiceDetails("MY_PROJECT_NAME", "MY_ENDPOINT_NAME")` fails asking for an extra permission: **Edit project-level information**.

**Comment by shudv** [comment]
The fiddler does capture the HTTPS GET request from the browser and I see the data as I expect. Although the call from the library does not show up on the fiddler. Are we sure that we are hitting the same route from the library?

**Comment by damccorm** [comment]
I took another look at this - the reason its not returning what you're expecting is that its actually hitting a different api. The api you linked to is part of the service endpoint api, not the core api.

Right now, we don't have this exposed via the generated clients - I'm going to update the title/label to reflect that this is an enhancement.

**Comment by erik-am** [comment]
I'm also looking forward to this being added! 👍

**Comment by Nusserdt** [comment]
@damccorm is there any update about a `ServiceEndpoint` api call over `azure-devops-node-api`?
