### ISSUE TITLE
Get Work Items by Assigned User

### ISSUE THREAD

**Issue by FXschwartz** [microsoft/azure-devops-node-api#311]
I've looked a great deal through the documentation and it's very possible I missed it but is there built functionality to get work items based on the user assigned to the work item?

If I did miss this I apologize, any help pointing me in the right direction would be greatly appreciated!

**Comment by damccorm** [comment]
Whoops, sorry didn't see this one until now. As best I can tell there isn't an api for that. We just generate this library based off the [rest endpoints](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0&viewFallbackFrom=vsts-rest-4.1) and it doesn't look like they have it.

If you need this, the best path forward is to request it in the [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html). That way it gets routed to the endpoint owners, and if implemented will eventually end up here as well when we regen.

**Comment by FXschwartz** [comment]
@damccorm No problem, appreciate the response!

I will do that then and see if its something they could do.

Thanks!
