### ISSUE TITLE
WebApi doesn't work in projects that use Webpack

### ISSUE THREAD

**Issue by alessandromuresan** [microsoft/azure-devops-node-api#312]
### Environment
Node version: v8.9.1
Npm version: 6.9.0
OS and version: Windows 10.0.17134.0
azure-devops-node-api version: 8.0.0

### Issue Description
The WebApi class' constructor tries to read the caller's package.json using `readFileSync`:
```
// WebApi.js, line 148
const nodeApiVersion = JSON.parse(fs.readFileSync(path.resolve(__dirname, 'package.json'), 'utf8')).version;
```
This causes an exception when using Webpack to build and bundle, because the build output folder is an arbitrary `dist` folder, not the project root, as the constructor is expecting. Furthermore, it is a bad practice to do this kind of logic in a constructor. Constructors should be one of the most reliable routines, not making calls that depend on the environment.

### Expected behaviour
Using WebApi should work in projects that are build with Webpack (or any other bundler that makes using __dirname unreliable).

### Actual behaviour
Instantiating a WebApi object fails

### Steps to reproduce
1. Install azure-devops-node-api 8.0.0 in a project that uses Webpack to build
2. Try to create an instance of WebApi

**Comment by damccorm** [comment]
Yeah, I agree this should be fixed. Add a PR to address it

**Comment by aashishsharma490** [comment]
I can still see the issue in version 8.0.0.
Is this fixed? Is there a workaround?

**Comment by damccorm** [comment]
The fix is in 8.2.0 which hasn't been released yet

@bryanmacfarlane can we release?

**Comment by aashishsharma490** [comment]
I hope it comes out soon!

**Comment by evanlouie** [comment]
The offending line is still referencing `__dirname`. Are their any plans to fix this?

**Comment by damccorm** [comment]
Sorry, forgot we had to revert this. I think to unblock people we can probably just make reading from package.json best effort - this telemetry is not worth breaking people.
