### ISSUE TITLE
IRequestOptions inteface defined in VsoBaseInterfaces doesn't support adding redirection options

### ISSUE THREAD

**Issue by aasim** [microsoft/azure-devops-node-api#315]
### Environment
Node version: v8.12.0
Npm version: 6.4.1
OS and version: Windows 10
azure-devops-node-api version: 8.0.0

### Issue Description
The IRequestOptions interface in the typed-rest-client package was updated recently to add the ability to follow redirects, and also to be able to not pass in authorization info for presigned urls. The [IRequestOptions ](https://github.com/microsoft/azure-devops-node-api/blob/master/api/interfaces/common/VsoBaseInterfaces.ts#L87)defined in the VsoBaseInterfaces that we use for our clients, hasn't implemented these fields yet. The ask is to add these to the interface, if needed I can just add and submit a PR as well. These are the new fields to be added:
```
    allowRedirects?: boolean;
    maxRedirects?: number;
    presignedUrlPatterns?: RegExp[];
```

### Expected behaviour
The IRequestOptions interface has the redirection fields which we can use to enable redirection for http clients.
### Actual behaviour
The IRequestOptions interface doesn't have these fields.

**Comment by stephenmichaelf** [comment]
@damccorm Can you take a look? Thanks!
