### ISSUE TITLE
getServiceEndpoints missing in 8.*.*

### ISSUE THREAD

**Issue by grawcho** [microsoft/azure-devops-node-api#317]
### Environment
Node version: v10.15.3
Npm version: 6.9.0
OS and version: linux (fedora 28 kernel 5.0.16
azure-devops-node-api version: 8.1.0

### Issue Description
i'm using azure-devops-node-api to rotate secrets in service endpoints from script and tried to upgrade from 7.2.0 to 8.1.0 and geterviceEndpoints / updateServiceEndpoints is missing from the TaskAgentAPIBase.d.ts

### Expected behaviour
all functions in older version have backward compatibility

### Actual behaviour
functions are missing from the mpn package

### Steps to reproduce
1. install azure-devops-node-api@8.1.0
2. try calling agentapi.getServiceEndpoints(projec.id)
3. error TS2339: Property 'getServiceEndpoints' does not exist on type 'ITaskAgentApiBase'.

**Comment by stephenmichaelf** [comment]
@grawcho There can be breaking changes across major versions of the lib.

**Comment by damccorm** [comment]
I'm going to close since this is expected behavior. We guarantee back-compat for minor/patch updates, but not for major version updates

**Comment by grawcho** [comment]
What could be a possible solution?

**Comment by damccorm** [comment]
In the short term, you can hit the endpoint directly - https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/get%20service%20endpoints?view=azure-devops-rest-5.0

Longer term, it looks like this has been moved into its own API, we should hopefully be able to generate it for this library soon as well - see #310. It might be worth adding this request in the [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html) as well. That way it gets routed to the endpoint owners, and if implemented will eventually end up here as well when we regen.

**Comment by Nusserdt** [comment]
@damccorm is there any update about a `ServiceEndpoints` api call over `azure-devops-node-api`?
