### ISSUE TITLE
WebAPI points to wrong package.json

### ISSUE THREAD

**Issue by eps1lon** [microsoft/azure-devops-node-api#321]
### Environment
Node version: 10.16.0
Npm version: 6.9.0
OS and version: Ubuntu 18.04.2 LTS
azure-devops-node-api version: 9.0.0

### Issue Description
package is published as flat bundle but tested inside nested lib folder: https://github.com/microsoft/azure-devops-node-api/blob/3c7622f8f5787bed172e60158ab793880a277a32/api/WebApi.ts#L148

### Expected behaviour
Following the readme doesn't cause errors

### Actual behaviour
Follwoing the readme leads to `Error: Cannot find module '../package.json'`

### Steps to reproduce
1. Follow https://github.com/microsoft/azure-devops-node-api#create-a-connection
2. run script

**Comment by dmitryserbin** [comment]
Same issue here - azure-devops-node-api v9.0.0

**Comment by damccorm** [comment]
Hm, a couple takeaways here:
1) Lets revert #313 and rerelease. That's clearly the culprit that is causing this issue. We should also reopen issue #312 and come up with a better solution.
2) This reveals an issue with our tests/samples. Neither of them picked up on this issue even though its pretty blatant - the installed code just doesn't work. We should revisit #171 which I think would help us catch issues like this.

Added PR #322 for point 1.
