### ISSUE TITLE
DeployPhases property filter always shows undefined in Release definition 

### ISSUE THREAD

**Issue by ABHINANDAN9006** [microsoft/azure-devops-node-api#323]
Environment
Node version: v10.15.1
Npm version: 6.4.1
OS and version: windows 10 
azure-devops-node-api version: 7.2.0

Issue Description:
I want to fetch the release task id form WorkFlowTask but when I am fetching the release definition, definition doesn't contain deployPhases property under environment. so I am unable to segregate the workFlowtasks and it's ids. 

Here is the code:

 const releaseDefs = this.releaseApi.getReleaseDefinitions(this.buildDefinition.project.name,
            undefined, undefined, undefined, this.buildDefinition.id.toString());
console.log(releases[0].id);  // out put 7
const task = (releases[0].environments[0].deployPhases); // even I tried with other index as well
console.log(task); // output undefined

While making the same call using the browser, it is returning all the property.
https://orgname.vsrm.visualstudio.com/xxxxxxxxxxxxxxxxxxxxx/_apis/Release/definitions/7
### Expected behaviour
release should return deployphases property 

### Actual behaviour
deployphases is undefined

**Comment by stephenmichaelf** [comment]
Two things to try:

1. Check the raw HTTP response and make sure it contains the data you're looking for
2. Do a print of JSON.stringify(releases) and see if the values are somewhere else in the object model

Let me know if that gets you closer.
