### ISSUE TITLE
Prop Access on undefined 

### ISSUE THREAD

**Issue by yoadsn** [microsoft/azure-devops-node-api#325]
### Environment
Node version: Any
Npm version: Any
OS and version: Any
azure-devops-node-api version: 6+

### Issue Description
This line access `res` which is never defined. Somehow - I must be missing something here - could this truly be production code? Got this using the Auth0 Azure Devops integration.

### Expected behaviour
To not throw.

### Actual behaviour
Throws.

### Steps to reproduce
1. Basically, call any part of this lib that gets version/area information.

### Logs
```
[31merror[39m: TypeError: Cannot read property 'value' of undefined
at restClient.options.then (/data/_verquire/vso-node-api/6.5.0/node_modules/vso-node-api/VsoClient.js:130:56)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
(From the Auth0 extension that uses this code).

**Comment by stephenmichaelf** [comment]
Some questions:

1. Could you share the code that calls this code so we can take a look?
2. Did you do a fiddler trace to see what response you're getting? If so, can you share?
3. Did you try updating to the latest version of the lib?
4. Are you using Azure DevOps or Azure DevOps Server?
5. Is it happening always or sometimes? Did it just start happening?

**Comment by yoadsn** [comment]
Hi,
Sure - so this is the `package.json` within the package that uses this code:
https://github.com/auth0-extensions/auth0-deploy-extensions/blob/master/package.json
And this is where it gets called:
https://github.com/auth0-extensions/auth0-deploy-extensions/blob/ba4c57a0077cf4c64f7eaa6f533c2e6fc4fb6f0b/server/lib/providers/tfs-git.js

I have no access to the network and there is not trace of the network in/out since this runs as an extensions in a 3rd party service (Auth0).

I cannot control this dependency - but looking at the code - there is no updated version of that specific method/function.

We are using Azure DevOps.

I was not happening in the previous version of the extension - but the code base has changed (for the extension) so there is no place for comparison I am afraid.

Btw - I posted an issue on the extension repo as well.
https://github.com/auth0-extensions/auth0-deploy-extensions/issues/30
But I see no way this line of code could work - the variable is just.. well - not defined ;)

**Comment by stephenmichaelf** [comment]
Thanks for the detailed response! As far as variable definition, see highlight below:

![image](https://user-images.githubusercontent.com/450490/59218033-4a04f800-8b8d-11e9-8204-4ffcfdd34681.png)

The variable is defined in the callback.

Given their code has changed too, it makes sense to me for them to investigate on their end and let us know if they find there is a specific issue in this lib. If there is we accept PRs or are more than happy to make a fix!

Thanks for the heads up.

**Comment by yoadsn** [comment]
Sorry for missing this 🤦‍♂  - I was sure I looked carefully at the code.
Will see how the other lib analyzes this problem.

**Comment by yoadsn** [comment]
This was resolved on the other lib - must have been a bad configuration on my part.
Thanks for the help and prompt response!
