### ISSUE TITLE
Creating a new Area Path with createOrUpdateClassificationNode fails

### ISSUE THREAD

**Issue by jeffpriz** [microsoft/azure-devops-node-api#327]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 6.11.2
Npm version: 
OS and version: 
azure-devops-node-api version: 9.0.1

### Issue Description
I am attempting to create a new Area Path for a project (to eventually associate with a new team).  I am attempting to use 
WorkItemTrackingApi.IWorkItemTrackingApi.createOrUpdateClassificationNode to create that new Area Path.. however it seems to fail with an error that would seem to indicate that the parameters I am passing are not quite right, however I've double checked that my parameters are in the correct order.. 

### Expected behaviour
Call to createOrUpdateClassificationNode to create an Area Path would create that area path

### Actual behaviour
get message about the Path that I am attempting to create is not a valid value for TreeStructureGroup

### Steps to reproduce
```
        try {
            var witApiObject: WorkItemTrackingApi.IWorkItemTrackingApi = await vsts.getWorkItemTrackingApi();
            
            var newArea:WorkItemTrackingInterfaces.WorkItemClassificationNode = {name: "newareapath"};

         
            var projectId:string = "";
            if(projectRef.id)
            {
                projectId = projectRef.id;
            }
            var areaResult:WorkItemTrackingInterfaces.WorkItemClassificationNode = await witApiObject.createOrUpdateClassificationNode(newArea, projectId, WorkItemTrackingInterfaces.TreeStructureGroup.Areas,"Jeffs Sandbox");
           

            tl.debug("success adding area");
            resolve(areaResult);
            
        }
        catch(err)
        {
            reject(err);

        }

```
this code returns error "The value 'Jeffs Sandbox' is not valid for TreeStructureGroup." .. note 'Jeffs Sandbox' is being passed in the Path parameter, andWorkItemTrackingInterfaces.TreeStructureGroup.Areas is being passed in the TreeStructureGroup parameter

**Comment by stephenmichaelf** [comment]
@jeffpriz Did you check the HTTP request/response here to see if it looks as expected? Do you have a working raw HTTP request? This library is a generated wrapper of the REST apis so it's possible the issue is with the setup of the call.

**Comment by jeffpriz** [comment]
@stephenmichaelf I'm struggling to find a good way to check the raw request/response.. suggestions?

**Comment by jeffpriz** [comment]
Hmm, well through a lot of trial and error, and a lot of shots in the dark, I found that if I add the Path to the path "Areas" it works as I wanted... This really could use some explanation and or documentation help either here And/or on the API Documentations page.. it's REALLY unclear why I don't specify the area path name as the path that I want to add the area to..   It would seem that "Areas" serves as the root area?

**Comment by Jsoconno** [comment]
Can you elaborate on "I found that if I add the Path to the path "Areas" it works as I wanted"?

I've been searching desperately to find an answer to this and same as you I've been taking every shot in the dark I can think of.  I'm using the Python SDK, but the JSON request should look similar.  Can you please post the request you are sending that is working for you?

For additional context, when I create an area path by passing the "name" parameter it does add the node under the project root, but I cannot seem to create the node under another parent or move it after it has been created using the "id" and "path" parameters.

Thanks!
