### ISSUE TITLE
Update TFS Version and Library Table in Readme

### ISSUE THREAD

**Issue by adraut** [microsoft/azure-devops-node-api#329]
The [api-and-tfs-mapping table in the readme](https://github.com/microsoft/azure-devops-node-api/blob/master/README.md#api-and-tfs-mapping) needs updated for newer versions of TFS and Azure DevOps server.

**Comment by damccorm** [comment]
Updated accordingly

**Comment by adraut** [comment]
@damccorm Is TFS Update 3 any different than TFS Update 2?  Should the 6.6.3 version of the library be used over 6.6.2 in any case?

**Comment by damccorm** [comment]
> Is TFS Update 3 any different than TFS Update 2?

Nope, there's some overlap on these, all API versions will work on the server version mentioned as well as later versions.

> Should the 6.6.3 version of the library be used over 6.6.2 in any case?

Sure if you need whatever came in the patch. In general, I'd probably recommend using the later versions of the library when in doubt, we release bug fixes pretty regularly. To be a little more precise here - anything `<7.0.0` should work for TFS Update 2 or 3, we no longer make that guarantee starting at 7.0.0 though
