### ISSUE TITLE
Connection and Authentication Settings for Pipeline Task Execution (Azure DevOps Server)

### ISSUE THREAD

**Issue by HSSE-Dev** [microsoft/azure-devops-node-api#330]
Hello, 
I would like to use the azure-devops-node-api to develop a pipeline task for Azure Devops. Unfortunately I'm not quite sure which authentication settings have to be used for this because I have different rights in the BuildAgent than when I access the API externally. In Powershell scripts it worked with the flag "UseDefaultCredentials".
Thank you in advance.

**Comment by stephenmichaelf** [comment]
@HSSE-Dev Node doesn't have the ability to UseDefaultCredentials. If you wanted to use default credentials you could write a Powershell task but of course then you won't have access to the node API and would have to create rest calls and handle the response yourself.

You could also pass a PAT as a secret variable to the definition but would have to provide guidance on that to anyone using the task.

What specifically are you trying to accomplish with the task? Perhaps there is another route.

**Comment by HSSE-Dev** [comment]
Hello Stephen, 
thanks for the quick answer even if it doesn't make me happy. Then I will probably use the PAT, although it is not quite optimal for the user because of the temporal sequence of the PATs. The goal is to collect some build information (ChangeSets, WorkItems, Testresult, etc.) which will then be sent to an API rest interface. The easiest way would have been the azure-devops-node-api. 
Is it planned to offer this kind of authentication in the future?
Many thanks for the help!
