### ISSUE TITLE
Add required Reviewer

### ISSUE THREAD

**Issue by surr34** [microsoft/azure-devops-node-api#333]
### Environment
Node version: v12.3.0
Npm version: 6.9.0
OS and version: Windows 10 (1903)
azure-devops-node-api version: 9.0.1

### Issue Description
Depending on the result of our pipeline execution we want to block the PR until someone from a specific group approves the PR. Therefore we want to add a required reviewer group to the PR by calling `createPullRequestReviewer` with `{ isRequired: true }`.

Does this API actually support setting a required reviewer? If not is there any other way to block the PR until the group approves?

### Expected behaviour
The reviewer is added as required reviewer (block the PR until approved).

### Actual behaviour
The reviewer is added as optional reviewer.

### Steps to reproduce
```
const apiHandle = new WebApi(<serverUrl>, <authHandler>, undefined);
const gitHandle = await apiHandle.getGitApi();
const result = await gitHandle.createPullRequestReviewer(
    { isRequired: true" },
    <repo-uuid>,
    <pr-number>,
    <group-id>
);
```

**Comment by damccorm** [comment]
Could you try hitting the endpoint directly with your parameters and see if that works? See info on how to do that [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20reviewers/create%20pull%20request%20reviewer?view=azure-devops-server-rest-5.0). That will help us determine if this is an issue with the endpoint or this library.

Would also be helpful if you could capture a Fiddler trace of your request from the node-api

**Comment by surr34** [comment]
Hitting the endpoint directly has the effect shows the same behavior, the reviewer is added as an optional reviewer. So I assume it's not related to the node api. 
Is there any other way to "block" the PR?

**Comment by surr34** [comment]
can you answer whether this is supported or not? :)

**Comment by damccorm** [comment]
Hey @surr34 - sorry this slipped through the cracks. Since this isn't an issue with the node wrapper itself, could you file an issue here for the REST Api itself - https://developercommunity.visualstudio.com/spaces/21/index.html? That way it will get routed to the correct team
