### ISSUE TITLE
Explain how to look up and supply identities required by the API

### ISSUE THREAD

**Issue by lmmarsano** [microsoft/azure-devops-node-api#336]
### Environment
Node version: v10.16.0
Npm version: 6.10.2
OS and version: Oracle Linux Server release 7.6
azure-devops-node-api version: 9.0.1

### Issue Description
Would someone care to explain how to use REST APIs to convert a regular identifier such as an e-mail address into an identifier for the `id`s
https://github.com/microsoft/azure-devops-node-api/blob/517dd5d9b2e8037f52cc49d11e988beb72d3cbb8/api/interfaces/common/VSSInterfaces.ts#L141
needed to specify `reviewers`
https://github.com/microsoft/azure-devops-node-api/blob/517dd5d9b2e8037f52cc49d11e988beb72d3cbb8/api/interfaces/GitInterfaces.ts#L1660
in `createPullRequest`
https://github.com/microsoft/azure-devops-node-api/blob/d6c74df97a203b684c3fa6733ab6532a71d72264/api/GitApi.ts#L4166
?
This is needed for both TFS 2018 Update 3 (on premises) collections, and an Azure DevOps organization.
Far too many hours have been wasted on this painfully nontrivial task.
Moreover, though [Graph resources](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/) may work for Azure organizations, either that doesn't handle TFS on premises storage keys or an explanation for doing that is needed.

**Comment by damccorm** [comment]
We don't own the endpoints, so I'm not an expert on this (and in fact have basically no knowledge of most of them, we just expose methods generated from their endpoints in this library). With that said, all of the endpoints should be documented here - https://docs.microsoft.com/en-us/rest/api/azure/devops/

This one in particular is documented here - https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/create?view=azure-devops-server-rest-5.0. That should have the information you're looking for. If it doesn't, the best place to log that is the repo responsible for those docs - https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues.

**Comment by stephenmichaelf** [comment]
Closing as guidance was provided and this is just a wrapper of the API.
