### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authenticatedUser' of null

### ISSUE THREAD

**Issue by caitakan** [microsoft/azure-devops-node-api#337]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 11.9.0
Npm version: 6.5.0
OS and version: Win10
azure-devops-node-api version: 9.0.1

### Issue Description

after running npm run samples, it shows me 
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authenticatedUser' of null

`let vsts: vm.WebApi = new vm.WebApi(serverUrl, authHandler, option);
            let connData: lim.ConnectionData = await vsts.connect();
            console.log(`Hello ${connData.authenticatedUser.providerDisplayName}`);
            resolve(vsts);`

this seems like I got null from vsts.connect() after setting the API_URL, token and project.
### Expected behaviour

should run without error
### Actual behaviour

throwing error UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'authenticatedUser' of null

### Steps to reproduce
1. set env var API_URL, token and project
2. npm install
3. npm run samples
4. throwing error

**Comment by sijakret** [comment]
would you mind sharing the solution? i am having the same issue..
thanks!
