### ISSUE TITLE
CHANGELOG.md / UPGRADING.md / Release info missing

### ISSUE THREAD

**Issue by kachkaev** [microsoft/azure-devops-node-api#341]
### Issue Description

I have a project using `azure-devops-node-api@8.0.0`. Running [`ncu`](https://www.npmjs.com/package/npm-check-updates) this morning I discovered that the latest version is 9.0.1, so went to check what breaking changes I need to be aware of. However, I could  not find CHANGELOG.md, UPGRADING.md or Release info in this repo.

### Expected behaviour

I'd expect new versions to be documented in an easy-to-digest way to help users with upgrading.

**Comment by kachkaev** [comment]
not stale

**Comment by kachkaev** [comment]
Hope this issue will be addressed sooner or later 🙏

**Comment by kachkaev** [comment]
:(

**Comment by rarkins** [comment]
Bad bot.

https://github.com/microsoft/azure-devops-node-api/blob/master/.github/workflows/stale.yml

https://github.com/actions/stale/issues/21

**Comment by elliotleelewis** [comment]
Yep, v11 was released last week, but I've no idea what I have to change to migrate to it. 😅

Having a changelog would be incredibly valuable. @damccorm can we re-open this? 😄

**Comment by anatolybolshakov** [comment]
Hi @elliotleelewis yep - let me reopen this, sounds like a great idea!

**Comment by rarkins** [comment]
Not stale

**Comment by ac-apple-account** [comment]
Not stale

**Comment by dragan-novakovic** [comment]
Not Stale
