### ISSUE TITLE
Version 0.7.0 (For TFS2015) does not exist in NPM

### ISSUE THREAD

**Issue by Evit15** [microsoft/azure-devops-node-api#342]
### Issue Description
Version 0.7.0 (For TFS2015) does not exist in NPM.
https://www.npmjs.com/package/azure-devops-node-api

### Expected behaviour
Version 0.7.0 (For TFS2015) exists in NPM

**Comment by stephenmichaelf** [comment]
For older versions, the package was [vso-node-api](https://www.npmjs.com/package/vso-node-api).

**Comment by Evit15** [comment]
Hi @stephenmichaelf 

Thank for your quick reply!

What version of vso-node-api do you recommend for TFS 2015 ?
