### ISSUE TITLE
How to get specific fields from work item?

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/azure-devops-node-api#343]
azure-devops-node-api version: 9.0.1

I was able to successfully get query results from `workItemTrackingApi.queryById`, but the resultant list of work items have only a few generic fields on them. How can I get additional fields of the work item? Specifically, I'd like to read "Target Date", but also other fields.

**Comment by jtpetty** [comment]
@eanders-MS - Looking at the API documentation, it does not appear there is a way to control the fields returned back from queryById ( https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/wiql/query%20by%20id?view=azure-devops-rest-5.1) 

Would it be possible for you to use queryByWiql() instead? It seems to have more control over which fields are returned. (https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/wiql/query%20by%20wiql?view=azure-devops-rest-5.1)

**Comment by eanders-MS** [comment]
Thanks for the reply. Turns out the answer was right in front of me. I needed to call `workItemTrackingApi.getWorkItem`, and pass the names of the fields I wanted to retrieve. Here's the full list of fields I'm fetching, in case it helps others:

```ts
const WorkItemFields = [
	"System.AreaPath",
	"System.TeamProject",
	"System.IterationPath",
	"System.WorkItemType",
	"System.State",
	"System.Title",
	"Microsoft.VSTS.Common.Priority",
	"Microsoft.VSTS.Scheduling.TargetDate"
];
```
