### ISSUE TITLE
getProjectCollection needs edit rights

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-devops-node-api#346]
I'm trying to get the name of the collection, considering that I do know only the collection ID.

```
    const tfs: api.WebApi = new api.WebApi(serverUrl, authHandler, { ignoreSslError: true });
    const tfsCore: ICoreApi = await tfs.getCoreApi();
    const currentCollection = await tfsCore.getProjectCollection(collectionId);
```

Unfortunately, it seems that the account I'm using, no matter it can access a project in the collection, thus it can read info about the collection, it can't create an instance of TeamProjectCollection object in the API.

The error I do get is the following:
`Error: Access Denied: Project Collection Build Service (DefaultCollection) needs the following permission(s) to perform this action: Edit instance-level information`

Why the Edit instance-level information is necessary? Is there another way to retrieve the collection name give the collection id via the API?

**Comment by mmajcica** [comment]
This may be not an issue of this library but of the AzDO REST API. Can this be transferred somewhere, somehow?

**Comment by damccorm** [comment]
https://developercommunity.visualstudio.com/spaces/21/index.html is probably the best place for this

**Comment by mmajcica** [comment]
I will try here:
https://developercommunity.visualstudio.com/content/problem/976505/resolving-collection-name.html

Thanks
