### ISSUE TITLE
Not able to authenticate with "adal-node" Bearer token obtained via Device Profile auth flow

### ISSUE THREAD

**Issue by TheUniquePaulSmith** [microsoft/azure-devops-node-api#347]
### Environment
Node version:  v12.4.0
Npm version:  6.9.0
OS and version: Windows 10 1803
azure-devops-node-api version: 9.0.1
adal-node version: 0.2.1

### Issue Description
Not able to authenticate with "adal-node" Bearer token obtained via Device Profile auth flow.
Error returns 
**TF400813: The user '' is not authorized to access this resource.**

### Expected behaviour
Able to login and impersonate user with obtained token

### Actual behaviour
Not able to login and consume ADO REST API

### Steps to reproduce
1. Use adal-node to obtain Device Profile user token
2. Set token in **getBearerHandler** 
3. Try and call **getWorkApi()**

### Logs
None

Also posted more details on Azure Devops Developer Community Forum:
https://developercommunity.visualstudio.com/content/problem/738745/tf400813-the-user-is-not-authorized-to-access-this-5.html

**Comment by volllly** [comment]
We encounter the same issue with a Bearer Token received by [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-js)

**Comment by zkbule** [comment]
Any update on this? we have the same issue here with adal-node
