### ISSUE TITLE
Unable to create new variable group with `azurekeyvault` type

### ISSUE THREAD

**Issue by sarath-p** [microsoft/azure-devops-node-api#350]
### Environment
Node version: v12.10.0
Npm version: 6.11.3
OS and version: macOS Mojave
azure-devops-node-api version: 9.0.1

### Issue Description
Unable to add a new variable group with type `azurekeyvault` in Azure DevOps project.

### Expected behaviour
Create a new variable group with a link to Azure Key Vault for secrets by calling [ITaskAgentApi.addVariableGroup](https://github.com/microsoft/azure-devops-node-api/blob/cf9a8734ac8a2e3fa919fcab0db65fbb0aa78d40/api/TaskAgentApiBase.ts#L6605) method. 

### Actual behaviour

   ```
    Error: Error: Variable group type azurekeyvault is not supported.
    at RestClient.<anonymous> (/Users/.../repos/pipeline/node_modules/typed-rest-client/RestClient.js:200:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/.../repos/pipeline/node_modules/typed-rest-client/RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
   ```

### Steps to reproduce
1. Calling API fails with below code.
    ``` 
    let vsts: vm.WebApi = await cm.getWebApi();
    let vstsTask: ta.ITaskAgentApi = await vsts.getTaskAgentApi();
    let vstsBuild: ba.IBuildApi = await vsts.getBuildApi();

    // creating variable group
    const params: ti.VariableGroupParameters = {
      name: "kvgroup",
      description: "kvgroup desc",
      type: "azurekeyvault",
      variables: {
        key1: {
          value: "value1"
        },
        key2: {
          value: "value2",
          isSecret: true
        }
      }
    };

    const group = await vstsTask.addVariableGroup(params, project);
    ```

**Comment by atbagga** [comment]
@sarath-p  Probably type is case sensitive. Try "AzureKeyVault".

**Comment by sarath-p** [comment]
Yes, `AzureKeyVault` worked.
