### ISSUE TITLE
Version 0.7.0 (For TFS2015) does not exist for vso-node-api OR azure-devops-node-api in NPM

### ISSUE THREAD

**Issue by malchowc** [microsoft/azure-devops-node-api#351]
### Issue Description
Version 0.7.0 (For TFS2015) does not exist in NPM under the **azure-devops-node-api** package name **OR** the **vso-node-api** package name.

The closest version available that is not greater is 0.6.1. Unless there were no bug fixes or features added between 0.6.1 and 0.7.0 then it seems risky to use it versus the releases 0.7.0 version for TFS 2015.

https://www.npmjs.com/package/azure-devops-node-api
https://www.npmjs.com/package/vso-node-api

### Expected behaviour
Version 0.7.0 (For TFS2015) exists in NPM under either the azure-devops-node-api or the vso-node-api package name.

**Comment by damccorm** [comment]
I think all that did was add additional APIs, everything that exists in the API at that point should be safe to use. If you run into anything missing that is present in https://github.com/microsoft/azure-devops-node-api/tree/ee8a0f5188bd633149aa581b78158cd92ed6747a let me know. If it wasn't deemed worth publishing at the time it almost certainly doesn't contain anything critical though.
