### ISSUE TITLE
JsonPatchDocumentObject missing definition

### ISSUE THREAD

**Issue by marknadig** [microsoft/azure-devops-node-api#354]
### Environment
Node version: 10.16.0
Npm version: 6.9.0
OS and version: Win10

### Issue Description
VSInterfaces.ts has an empty definition for JsonPatchDocument:
```
export interface JsonPatchDocument {
}
```

### Expected behaviour
Seems it should be an array of JsonPatchOperation. In practice, I'm sending up an array of JsonPatchOperations and it is working.

CoreApi.ts seems to imply it is expecting an array:
`* @param {VSSInterfaces.JsonPatchDocument} patchDocument - A JSON Patch document that represents an array of property operations. See RFC 6902 for more details on JSON Patch. The accepted operation verbs are Add and Remove, where Add is used for both creating and updating properties. The path consists of a forward slash and a property name.`

### Logs

It is unclear to me the source of the generated files, so not sure how to submit PR.

**Comment by marknadig** [comment]
Still an issue https://github.com/microsoft/azure-devops-node-api/blob/df92f600f55d7f65d07d075803d15a6fdd8a0f00/api/interfaces/common/VSSInterfaces.ts#L176 

Again, happy to submit a PR . However, it seems this file is generated and unclear from what source
https://github.com/microsoft/azure-devops-node-api/commits/master/api/interfaces/common/VSSInterfaces.ts

**Comment by marknadig** [comment]
bah... what did I do wrong that this is still considered stale?

**Comment by damccorm** [comment]
Not sure why it still got closed

**Comment by marknadig** [comment]
Again, happy to submit a PR if someone would point me to where this is derived from.
