### ISSUE TITLE
[Question] : Could we have new release

### ISSUE THREAD

**Issue by bbarroux** [microsoft/azure-devops-node-api#357]
Thanks for the amazing library !
Is there any plan to have a new release published in npm ? 9.0.1 is 5 months old, and many critical issues have already been fixed and merged. 
(TBH, the one I'm specifically personally after is https://github.com/microsoft/azure-devops-node-api/issues/339)

**Comment by stephenmichaelf** [comment]
Thanks @bbarroux sorry for the delays here! We will be releasing this lib next week.

**Comment by damccorm** [comment]
Hi, this has been released - sorry for the delay
