### ISSUE TITLE
When using the getDeployments call and specifying the sourceBranch, result is empty array.

### ISSUE THREAD

**Issue by carlosm2011** [microsoft/azure-devops-node-api#361]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: v10.16.3
Npm version: 6.9.0
OS and version: windows 10 version 1709
azure-devops-node-api version: 9.0.1

### Issue Description
When I invoke the getDeployments call and specify the sourceBranch as "refs/heads/master" or "master" or the repository name I always get an empty array back. Sending a null or empty string brings back results. I looked at the tfs call _apis/Release/deployments and sourceBranch is "refs/heads/master".

### Expected behaviour
Deployments should come back when I specify the sourceBranch

### Actual behaviour
Nothing is coming back

### Steps to reproduce
1. set sourceBranch to "refs/heads/master/
2. execute code 
3. evaluate response from azure

### Logs
No logs

**Comment by stephenmichaelf** [comment]
@carlosm2011 Did you try making an HTTP request from Fiddler to see if the same thing happens? This library is just a wrapper for the API.

**Comment by carlosm2011** [comment]
@stephenmichaelf Yeah it's definitely a bug, I was able to solve this issue by using the TFS API with a similar payload.
