### ISSUE TITLE
GitApi.getBlobsZip needs to be a POST request, but sends GET

### ISSUE THREAD

**Issue by Kayakflo** [microsoft/azure-devops-node-api#362]
### Environment
Node version: v8.16.0
Npm version: 6.4.1
OS and version: macOS Mojave (10.14.6)
azure-devops-node-api version: 7.0.0

### Issue Description
GitAPI.getBlobsZip should send a POST request according to Rest API documentation (https://docs.microsoft.com/en-us/rest/api/azure/devops/git/blobs/get%20blobs%20zip) but sends GET request instead: https://github.com/microsoft/azure-devops-node-api/blob/d4b692556db58a418e5d7c2b01fb68978746b3b4/api/GitApi.ts#L396

### Expected behaviour
GitAPI.getBlobsZip should return a Promise<NodeJS.ReadableStream> transferring the requested zip.

### Actual behaviour
The returned data is: "{"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}"

### Steps to reproduce
1. Instantiate a connection to the GitAPI 
    const gitAPI = await connection.getGitApi();
2. Request ZIP file
    gitAPI.getBlobsZip(blobdIds, repositoryId, projectId);
3. Stream response to log.txt
4. Check content of log.txt

### Logs
In order to make the request work I replaced the following code in getBlobsZip in GitAPI:
```
let apiVersion = verData.apiVersion;  
let accept = this.createAcceptHeader("application/zip", apiVersion);  
resolve((yield this.http.get(url, { "Accept": accept })).message);
```
with
```
let options = this.createRequestOptions('application/json', verData.apiVersion);
options.acceptHeader = this.createAcceptHeader("application/zip", verData.apiVersion);
let res;
res = yield this.rest.create(url, blobIds, options);
resolve(res.message);
```
(notice paramter 'blobIds' has been unused before).

In addition (as a workaround) I replace the following lines in RestClient.create which is being used to send the request:
```
return this._processResponse(res, options);
```
with
```
return res;
```

If you run the reproduction steps again and stream the response to a 'myfile.zip' the data is received correctly.

**Comment by brentlemons** [comment]
I'm having the same, but slightly different issue. I found this issue report because I was also receiving the GET response. I used a similar method to above, but I get an empty response from a POST to .../blobs. I also get an empty response when I call blobs from curl. Is there currently an issue with the Azure DevOps blobs POST endpoint?

**Comment by yiruiHH** [comment]
Also I found that getBlobsZip function does not send the blobIds as the body

**Comment by cjh15hub** [comment]
I have experienced this issue today and it is unresolved. As the original user stated, when using this function, the resulting file will contain the following:
"{"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}"
