### ISSUE TITLE
Add Azure Artifacts API

### ISSUE THREAD

**Issue by evgri243** [microsoft/azure-devops-node-api#364]
Environment
Node version: 13.2.0
Npm version: 6.13.1
OS and version: linux
azure-devops-node-api version: 9.0.1

### Issue Description
SDK has no API implementation for Azure Artifacts.

### Expected behaviour
API and the client should be present in WebApi. We plan to use them from VSCode Extension.

**Comment by icnocop** [comment]
It seems Artifacts are implemented in the BuildApi.

See https://github.com/microsoft/azure-devops-node-api/blob/master/samples/buildArtifact.ts
