### ISSUE TITLE
Retrieve Pull Request Updates/Activity

### ISSUE THREAD

**Issue by bsell93** [microsoft/azure-devops-node-api#365]
### Environment
Node version: v10.15.3
Npm version: 6.4.1
OS and version: macOS 10.13.6
azure-devops-node-api version: 8.0.0

### Question
I scoured the docs and the issues here, but was unable to find anything indicating the ability to get "new comments" or "code updates" on a pr. 

Does something like this exist in the api?

The data that is exposed in the UI that I'm looking to retrieve in the API:
![image](https://user-images.githubusercontent.com/5335177/70825236-faa8ba00-1db1-11ea-8527-3a02bea5e072.png)

Related issue: https://github.com/MicrosoftDocs/vsts-rest-api-specs/issues/262

**Comment by andrewhathaway** [comment]
Would also like to be able to see this. I've noticed that the GitHub API has `lastUpdated` field on a Pull Request which is updated whenever anything on that PR changes.

**Comment by bsell93** [comment]
@stephenmichaelf is there any update on this? Thanks!

**Comment by bsell93** [comment]
This should not be closed. I don't think the joke, "If you ignore a problem long enough it will go away." should apply here.
