### ISSUE TITLE
TaskAgentApi.updateVariableGroup Failed to find api location for area distributedtask

### ISSUE THREAD

**Issue by showmetwo** [microsoft/azure-devops-node-api#369]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: v12.13.1
Npm version: 6.13.4
OS and version: windows 2016
azure-devops-node-api version: 10.0.0

### Issue Description
I am using TFS 2018 on my local, when I try to call TaskAgentApi.updateVariableGroup, it will popup error say: Failed to find api location for area distributedtask xxxx-xxxx-xxxx.
Understand two days ago upgrade new version to 10.0.0, there is no issue when use 9.0.1.
And there is difference between two versions:
updateVariableGroup with 9.0.1, there are three parameters -> variableGroupParameter, project, variableGroupID
updateVariableGroup with 10.0.0, there are two parameters -> variableGroupParameter, variableGroupID

### Expected behaviour
with newest version, suppose update variable group parameter in TFS 2018
### Actual behaviour
popup error Failed to find api location for area distributedtask
### Steps to reproduce
TFS 2018, typescript code:
const tfsUrl: string = "https://xxx/tfs/Default";
const token: string = "xxxxxx";
const webApi: api.WebApi = await common.getWebApi(tfsUrl, token);
const taApi: taskAgentApi.ITaskAgentApi = await webApi.getTaskAgentApi();
let variableGroupParameter: taskAgentInterface.VariableGroupParameters = {};
variableGroupParameter.variables = {};
variableGroupParameter.name = "Test";
variableGroupParameter.variables["abc"] = "123";

// Let's say group id is 1, I can get it from postman since I create variable groups in TFS
await taApi.updateVariableGroup(variableGroupParameter, 1);

**Comment by stephenmichaelf** [comment]
@showmetwo Why did you update the lib if you're going against on-prem? The feature set in on-prem is fixed so there is no need for a new version of this lib.

**Comment by showmetwo** [comment]
> @showmetwo Why did you update the lib if you're going against on-prem? The feature set in on-prem is fixed so there is no need for a new version of this lib.
our on-prem TFS has to customize some build/release task, which need to update library information. since upgrade to 10.0.0 of azure-devops-node-api, the function updateVariableGroup cannot work anymore under TFS 2018.

**Comment by showmetwo** [comment]
turns out, someone changed the id, you can compare two versions, ef5b7057-ffc3-4c77-bbad-c10b4a4abcc7 not workable for both TFS 2018 and Azure DevOps Server 2019:

before: let verData = yield this.vsoClient.getVersioningData("3.2-preview.1", "distributedtask", "f5b09dd5-9d54-45a1-8b5a-1c8287d634cc", routeValues);

now: let verData = yield this.vsoClient.getVersioningData( "6.0-preview.2", "distributedtask",                   "ef5b7057-ffc3-4c77-bbad-c10b4a4abcc7",, routeValues);

**Comment by stephenmichaelf** [comment]
I still don't understand your need to update the library. On-prem APIs aren't changing so the 9.0.1 version of the lib should be able to hit any REST endpoints you need.

**Comment by sarath-p** [comment]
@stephenmichaelf  - I just upgraded to `10.0.0` from `9.0.1` and running into the same issue. I am getting the below error when connecting to Azdo project.

`error:   Atleast one variable group project reference is required.`
