### ISSUE TITLE
Cannot include AgentBasedDeployPhase in a ReleaseDefinitionEnvironment

### ISSUE THREAD

**Issue by schlueter** [microsoft/azure-devops-node-api#370]
### Environment
Node version: v12.14.1
Npm version: 6.13.6
OS and version: MacOS 10.15.2
azure-devops-node-api version: fd94f64 (10.0.0)

### Issue Description
I'm writing a script to update our release definitions, adding an agent based deploy phase
as part of a release definition environment. The api response from the `getReleaseDefinition` method includes such a defintion, but typescript produces an error when I attempt to implement my own `ReleaseDefinitionEnvironment` with a object abiding the `AgentBasedDeployPhase` interface. I can fix this by modifying the `ReleaseDefinitionEnvironment` interface and defining

        deployPhases?: DeployPhase[] | AgentBasedDeployPhase[];

rather than as just DeployPhase.

### Expected behaviour
This should be valid (assuming the content of the ellipsis is valid):

    const newReleaseDefinitionEnvironment: ReleaseInterfaces.ReleaseDefinitionEnvironment = {
        deployPhases: [
            {
                deploymentInput: {...

### Actual behaviour
When I run that typescript through `tsc` I get a big warning:

```
Object literal may only specify known properties, and 'deploymentInput' does not exist in type 'DeployPhase'.

 52                 deploymentInput: {
                    ~~~~~~~~~~~~~~~~~~
 53                     parallelExecution: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 69                     overrideInputs: {}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 70                 },
```

**Comment by kroonprins** [comment]
I am running into the same. Is there any update on this ticket? @jtpetty
