### ISSUE TITLE
A 404 "Not Found" error occurs when trying to get the agent queues using TFS 2015 Update 4 on-premise

### ISSUE THREAD

**Issue by icnocop** [microsoft/azure-devops-node-api#371]
### Environment
Node version: 10.15.1
Npm version: 6.4.1
OS and version: Windows Server 2019 Version 1809 OS Build 17763.107
azure-devops-node-api version: 10.0.0

### Issue Description
A 404 "Not Found" error occurs when trying to get the agent queues using TFS 2015 Update 4 on-premise.

### Expected behaviour
I expected the URL to be queried:
[http://tfs2015:8080/tfs/DefaultCollection/_apis/distributedtask/queues/](http://tfs2015:8080/tfs/DefaultCollection/_apis/distributedtask/queues/)

### Actual behaviour
The URL is queried:
[http://tfs2015:8080/tfs/DefaultCollection/Project Name/_apis/distributedtask/queues/](http://tfs2015:8080/tfs/DefaultCollection/Project%20Name/_apis/distributedtask/queues/)

### Steps to reproduce
1. Call `getAgentQueues("Project Name")` against TFS 2015 Update 4 on-premise.
2. Notice a 404 "Not Found" error

### Logs
I will try to reproduce this issue in isolation if needed, but it may take a bit.

**Comment by stephenmichaelf** [comment]
This is due to using the latest version of the lib with an older version of TFS. Please see our main page [here](https://github.com/microsoft/azure-devops-node-api) for a mapping of what version of the lib to use based on what version of TFS you have.

**Comment by icnocop** [comment]
Thank you.

I guess I'm confused by which "later versions" in "All API versions will work on the server version mentioned as well as later versions." from readme.md.

Does "later versions" mean "later TFS versions"?

**Comment by icnocop** [comment]
As a work-around, I was able to use [IIS URL Rewrite](https://www.iis.net/downloads/microsoft/url-rewrite) with this rule, added to the `Team Foundation Server/tfs` virtual directory (`C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\web.config`):

```
<rewrite>
    <rules>
        <rule name="Rewrite distributedtask/queues" stopProcessing="true">
            <match url="(.*)/(.*)/_apis/distributedtask/queues" />
            <conditions>
                <add input="{URL}" pattern="DefaultCollection/_apis/distributedtask/queues" negate="true" />
            </conditions>
            <action type="Rewrite" url="{R:1}/_apis/distributedtask/queues" logRewrittenUrl="true" />
        </rule>
    </rules>
</rewrite>
```

It basically rewrites API requests from
http://tfs2015:8080/tfs/DefaultCollection/MyProject/_apis/distributedtask/queues
to
http://tfs2015:8080/tfs/DefaultCollection/_apis/distributedtask/queues

Thank you.

**Comment by stephenmichaelf** [comment]
@icnocop We will clean up that text, I agree it's confusing.

I still am confused by your request: why would you need a new version of the lib to use against 2015 on-prem?

Also, I would not recommend doing the IIS rewrite.

**Comment by icnocop** [comment]
> why would you need a new version of the lib to use against 2015 on-prem?

I'm using https://github.com/huserben/TfsExtensions which depends on v6.6.3.

In order to use it against TFS 2015 on-prem, I had to implement the IIS URL Rewrite work-around.

Should v6.6.3 be compatible with TFS 2015 on-prem?
If not, how else would you suggest making it work?

Thank you.

**Comment by stephenmichaelf** [comment]
> Should v6.6.3 be compatible with TFS 2015 on-prem?

You'll have to talk with the Extension owner about this, which will also answer your last question.

**Comment by stephenmichaelf** [comment]
Closing, as mentioned please speak with the Extension owner.
