### ISSUE TITLE
How to get continuation token in axios API call for projects

### ISSUE THREAD

**Issue by jashan05** [microsoft/azure-devops-node-api#373]
### Issue Description
Not able to get all the headers in response while doing GET METHOD using AXIOS such as continuation token.

### Expected behaviour
Should get all the headers.

### Actual behaviour
Not getting all the headers escpecially  continuation token . e.g **x-ms-continuationtoken**

**Comment by jeff-simeon** [comment]
why was this closed and what is the resolution?
