### ISSUE TITLE
API to get list of projects

### ISSUE THREAD

**Issue by jashan05** [microsoft/azure-devops-node-api#374]
### Environment
Node version: v13.7.0
Npm version: 6.13.6
OS and version: MacOs
azure-devops-node-api version: 

### Issue Description
I want to get the list of projects in organization

### Expected behaviour
API is able to return list of all the projects in organization

### Actual behaviour
Couldnt find the functionality

**Comment by damccorm** [comment]
@jashan05 this library is just a wrapper around our APIs - does the API you're looking for exist anywhere in https://docs.microsoft.com/en-us/rest/api/azure/devops/account/accounts/list?view=azure-devops-rest-5.1? If not, the best path forward is probably to open a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by jashan05** [comment]
@damccorm  Yes api from Microsoft is available. It is basically to get the collection of projects in azure devops. I couldnt find any methods/class/interface to get the projects. The API from microsoft i am referring is -->
[this](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.1)

**Comment by msogden** [comment]
Get list of collections then iterate the projects

**Comment by damccorm** [comment]
You can use this function https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/CoreApi.ts#L38
