### ISSUE TITLE
Cannot create Git Client.

### ISSUE THREAD

**Issue by cp79shark** [microsoft/azure-devops-node-api#377]
### Environment (local)
Node version: 12.16.1
Npm version: 6.13.4
OS and version: Win 10 1909
azure-devops-node-api version:  ^10.1.0
@azure/functions: ^1.0.2-beta2

### Environment (Azure Function)
![image](https://user-images.githubusercontent.com/4753295/76656466-e305dc80-652c-11ea-88ab-77b99e180410.png)

### Issue Description
I cannot instantiate the `GitApi` locally or when deployed to Azure.

Relevant snippet of code.

```
    log.info(`Have a token for ${projectName} of ${token}`); // YES, this won't make it to prod
    const authHandler = azdev.getPersonalAccessTokenHandler(token);
    log.info(`Token Handler created`);
    const connection = new azdev.WebApi(encodeURI(`https://dev.azure.com/${projectName}/`), authHandler);
    log.info(`API connection created for ${connection.serverUrl}`);
    const gitClient = await connection.getGitApi();
    log.info(`Git Client created`);
```

### Expected behaviour
`connection.getGitApi()` should return my gitClient to issue requests to the DevOps REST API.

### Actual behaviour
Fails. See Log output below.

Debugging locally I see that the failure is occurring in the `beginGetAreaLocations` method of the `VsoClient`. It is using for the `requestUrl` param "https://dev.azure.com/[ORG]/_apis/Location".

This request is returning a 404. I don't see this API listed in the DevOps REST API documentation. 

### Logs
```
2020-03-13T20:20:12.423 [Information] Executing 'Functions.EvaluatePullRequest' (Reason='This function was programmatically called via the host APIs.', Id=36c653e7-997b-4f17-9ffc-3b974d7a8e03)
2020-03-13T20:20:12.482 [Information] Processing Git Pull Request Created Event.
2020-03-13T20:20:12.483 [Information] Have a token for <ORG> of <TOKEN>
2020-03-13T20:20:12.483 [Information] Token Handler created
2020-03-13T20:20:12.484 [Information] API connection created for https://dev.azure.com/<ORG>/
2020-03-13T20:20:12.711 [Error] Executed 'Functions.EvaluatePullRequest' (Failed, Id=36c653e7-997b-4f17-9ffc-3b974d7a8e03)
Result: Failure
Exception: TypeError: Cannot read property 'value' of null
Stack: TypeError: Cannot read property 'value' of null
    at D:\home\site\wwwroot\node_modules\azure-devops-node-api\VsoClient.js:124:52
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by cp79shark** [comment]
It has to do with the baseUrl. 

This (always using dev.azure.com/[org]) worked with the C# client, so I mistakenly assumed it worked with the Node client. Pulling the baseUrl out of the request and assigning it to the `getGitApi(url)` lets it connect.

**Comment by KyleBastien** [comment]
@cp79shark It looks like I'm running into the same issue, how were you able to resolve this? I tried putting the `https://dev.azure.com/<ORG>/` URL into the `getGitApi` call but it seems like I'm getting the same results.

**Comment by cp79shark** [comment]
@KyleBastien here is the current working code snippet from my project. `pullRequest` is set from the DevOps web hook Pull Request Create. The URI ends up being the ORG.visualstudio.com.

```
const baseUri = pullRequest.repository.project.url.split("/_apis")[0];

const authHandler = azdev.getPersonalAccessTokenHandler(token);
log.info(`Token Handler created`);
const connection = new azdev.WebApi(baseUri, authHandler);

log.info(`API connection created for ${connection.serverUrl}`);
const gitClient = await connection.getGitApi();
```

**Comment by KyleBastien** [comment]
@cp79shark Thanks for sharing got mine to work as well using the `org.visualstudio.com` URL, and then passing in `projectName` explicitly to the API calls that needed.

**Comment by robcresswell** [comment]
Could you reopen this? It should work fine with `https://dev.azure.com/<ORG>/`.

I could open a new issue, but it seems a shame to lose the discussion here

**Comment by cp79shark** [comment]
Sure. Re-opening for any triage they want to perform. I'm going to assume it's still failing for you, @robcresswell , with whatever the latest bits are?

**Comment by robcresswell** [comment]
@cp79shark I'm seeing the same error occasionally in an internal system. There's a high chance it's a bug in our side, but I wonder if the library should be more robust here. Reading the comments, it seems like everyone was using valid URLs but the library expects a specific format.

**Comment by robcresswell** [comment]
We've dropped the client due to other issues; feel free to close @cp79shark
