### ISSUE TITLE
Help: How to get user ID when using a PAT?

### ISSUE THREAD

**Issue by andrewhathaway** [microsoft/azure-devops-node-api#379]
Hi all, sorry this is mostly a request for help.

### Issue Description
Is it possible to get the User ID that the Personal Access Token is for when authenticated with a PAT? I've seen that the Profiles API is unavailable to PAT-authenticated requests.

Thanks!

**Comment by stephenmichaelf** [comment]
@andrewhathaway After you establish the connection the HTTP response headers should have this.

**Comment by andrewhathaway** [comment]
Which header specifically? I can see a few with GUIDs. `x-vss-userdata` is `{guid}:{emailAddr}` and there's also `x-vss-e2eid` which is a different guid to the one found in `userdata`.

**Comment by andrewhathaway** [comment]
Closing as I can confirm that the `guid` in the `x-vss-userdata` header is the user Id! Thanks for the pointer :)

**Comment by ankitbko** [comment]
@andrewhathaway how did you read this header? Can you post a snippet?
