### ISSUE TITLE
azure devops rest api access using nodejs

### ISSUE THREAD

**Issue by alokg7crdemo** [microsoft/azure-devops-node-api#389]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 
Npm version: 
OS and version: 
azure-devops-node-api version: 

### Steps to reproduce
1. 
2. 
3. 
4. 
5.

**Comment by stephenmichaelf** [comment]
No details, closing.
