### ISSUE TITLE
Add a sample for using the continuation token

### ISSUE THREAD

**Issue by kitforbes** [microsoft/azure-devops-node-api#395]
### Environment
Node version: `12.0.0`
Npm version: `6.9.0`
OS and version: Windows 10
azure-devops-node-api version: `10.1.1`

### Issue Description
I spent some time trying to work with the Releases API to pull back all releases within a project with the `getReleases()` function. This returns 50 by default and is able to max out at 100 if using `top`. As I need more than 100 returned, I wanted to use the continuation token, but I can't see how to do this.

It would be fantastic if you could add a sample showing users how to do this. Or, if I missed somethng obvious, please just point me in the right direction for how to do this.

### Expected behaviour
n/a

### Actual behaviour
n/a

### Steps to reproduce
n/a

### Logs
n/a

**Comment by brianhsb1671** [comment]
@kitforbes Were you able to get the continuation token?

**Comment by kitforbes** [comment]
Nope. I stopped trying and gave up on that task for the time being.

**Comment by johnnyreilly** [comment]
Is this related to https://github.com/microsoft/azure-devops-node-api/issues/415 ?

**Comment by kitforbes** [comment]
Bumping this issue once. I'll let it go stale next time. This library isn't great when you can't query all of the data.

**Comment by bworline** [comment]
How are you supposed to get a continuation token out of an azure-devops-node-api API method to pass back in to the same API method?  Many methods imply that a token is returned but I don't see how.  Example:  The comments for getBuilds() say, 
`@param {string} continuationToken - A continuation token, returned by a previous call to this method, that can be used to return the next set of builds.`
