### ISSUE TITLE
[Question] How to fetch files from a PR?

### ISSUE THREAD

**Issue by Hevia** [microsoft/azure-devops-node-api#396]
### Environment
Node version: v12.17.0
Npm version: 6.14.4
TSC version: 3.9.3
OS and version:  Windows 10
azure-devops-node-api version: ^10.1.1

### Issue Description
Apologies if this is a beginner question! I am an intern at Microsoft trying to use this for an internal project. 

I am trying to fetch **ALL** the files being worked on by a PR whenever a new PR is opened. However I cant find any function that seems to explicitly support this? I can successfully download the files from the master branch using getItemZip.

GetItemZip: https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/GitApi.ts#L2206

Is there a workflow component or API I am missing? I would appreciate the help! Thank you :)

**Comment by damccorm** [comment]
I don't believe we have an api to get the diff of a pr, you should be able to do this by getting all the relevant commits with [getPullRequestCommits](https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/GitApi.ts#L74) and then get the contents with [getCommitDiffs](https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/GitApi.ts#L41)

**Comment by Hevia** [comment]
This answered my question, forgot to close. Thanks!
