### ISSUE TITLE
Is there a way to link a GitHub issue to a workitem

### ISSUE THREAD

**Issue by ddyett** [microsoft/azure-devops-node-api#406]
I'm trying to add a link to a Github issue when I create a workitem.  I can see it's supposed to take an artifactlink but I can't  seem to use the GitHub uri with that.  It wants a uri of this form:  vstfs:///GitHub/Issue/4786ace5-7ca1-4bdc-a4c3-1b38ed994b05%2F1

The question I have is how to I create a new artifact uri so I can pass that in, or am I just looking at this incorrectly.

This fails
{
    "op": "add",
    "path": "/relations/-",
    "from": null,
    "value": {
        "rel": "ArtifactLink",
        "url": `${req.body.issue.html_url}`.   (of the form https://github.com/.../issues/1)
        "attributes": {
            "name": "GitHub Issue",
            "comment": "Making a new link"
        }
    }

This works

{
    "op": "add",
    "path": "/relations/-",
    "from": null,
    "value": {
        "rel": "ArtifactLink",
        "url": 'vstfs:///GitHub/Issue/4786ace5-7ca1-4bdc-a4c3-1b38ed994b05%2F1',
        "attributes": {
            "name": "GitHub Issue",
            "comment": "Making a new link"
        }
    }

**Comment by joshjohanning** [comment]
Yeah, how does one retrieve the GUID part of the URL? `4786ace5-7ca1-4bdc-a4c3-1b38ed994b05`


From: 
https://developercommunity.visualstudio.com/t/artifact-uri-format-in-external-link-of-work-items/964448

> Artifact URIs are made of three parts:
> 
> vstfs:///{artifactTool}/{artifactType}/{artifactId}
> 
> That last part, the artifactId, can also have multiple parts to it. For a github pull request, for example, it’s {repositoryId}/{pullRequestId}. To remove ambiguity about the URI segments, the artifactId gets encoded. Programmatically I don’t think it should be difficult for users to have logic to handle this case, so I would say this is just intended behavior.

**Comment by joshjohanning** [comment]
I couldn't really figure out how to formulate my own API request in Postman (and getting the body right), but I did find a javascript example that I modified: https://github.com/joshjohanning/azdo_commit_message_validator/blob/main/main.js#L85:L109
