### ISSUE TITLE
updatePullRequestReviewer doesn't update reviewer vote

### ISSUE THREAD

**Issue by beandrad** [microsoft/azure-devops-node-api#407]
### Environment
Node version: 12.18.2
Npm version: 6.14.5
OS and version: macOS Catalina 10.15.6
azure-devops-node-api version: 10.1.1

### Issue Description

When trying to update the reviewer vote using `GitApi.updatePullRequestReviewer()`, the reviewer vote is not updated.
```updatePullRequestReviewer(reviewer: GitInterfaces.IdentityRefWithVote, repositoryId: string, pullRequestId: number, reviewerId: string, project?: string): Promise<GitInterfaces.IdentityRefWithVote>;```

### Expected behaviour
The reviewer vote should be updated when the corresponding vote in the `updatePullRequestReviewer` is different from the current one.

### Actual behaviour
The reviewer vote is not updated by calling `updatePullRequestReviewer`.

### Steps to reproduce
1. Make a call to `updatePullRequestReviewer` with a new vote.

**Comment by tommywilkinson** [comment]
This issue should still be open. It seems to repro still today
