### ISSUE TITLE
getProfileApi() not working

### ISSUE THREAD

**Issue by abgopal** [microsoft/azure-devops-node-api#411]
WebApi() -> getProfileApi() fails with url for resource area 8ccfef3d-2b87-4e99-8ccb-66e343d2daa8 not available.

**Comment by viceice** [comment]
We have the same issue, see linked pr 😢

**Comment by viceice** [comment]
😢

**Comment by johnnyreilly** [comment]
No stalebot, no!

**Comment by ankitbko** [comment]
Is there any update on this?

**Comment by rarkins** [comment]
@EzzhevNikita @mjroghelia @damccorm @anatolybolshakov please reopen

**Comment by max-zaytsev** [comment]
As I can see in this [sample](https://github.com/microsoft/azure-devops-node-api/blob/ff820b2dd0c9a09cf09e64e94d3f95818a77249d/samples/profile.ts#L9)    

> Profile api can't be hit at the org level, has to be hit at the deployment level, so url should be structured like set API_URL=https://**vssps**.dev.azure.com/{orgName}

I tried running getProfileApi() without "vssps" in the serverUrl and got the same error:
_Error: Could not find information for resource area 8ccfef3d-2b87-4e99-8ccb-66e343d2daa8_

@abgopal, @viceice, @rarkins is this your case? Could you try using the serverUrl in this format?

**Comment by max-zaytsev** [comment]
@abgopal, @viceice, @rarkins is this issue still actual for you?

**Comment by rarkins** [comment]
I believe it is. Cc @JamieMagee

**Comment by m0sk1t** [comment]
@abgopal, @viceice, @rarkins #458 hope this PR helps us

**Comment by max-zaytsev** [comment]
Thanks @m0sk1t, but this will not fix the initial problem.
The solution is still to use the correct URL:

> Profile api can't be hit at the org level, has to be hit at the deployment level, so url should be structured like set API_URL=https://vssps.dev.azure.com/{orgName}
