### ISSUE TITLE
GitApi.getRefs seems to be missing pagination parts of API 

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-devops-node-api#415]
Hello!

Thanks for your work on this splendid API!  I've been playing with it this weekend and have found it really quick to get up and running with.  Solid choice using TypeScript! ❤️🌻 

I've just been looking at the `IGitApi.getRefs` endpoint and it seems to work great.  However, I've noticed that, in comparison with the documentation on the REST API (which this built on top of I believe?), the `getRefs` endpoint is missing pagination parameters.

https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/GitApi.ts#L5818-L5828

Consider the [REST API docs here](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/refs/list?view=azure-devops-rest-6.0#uri-parameters) which lists these parameters:

Name | In | Required | Type | Description
-- | -- | -- | -- | --
organization | path | True | string | The name of the Azure DevOps organization.
repositoryId | path | True | string | The name or ID of the repository.
project | path |   | string | Project ID or project name
api-version | query | True | string | Version of the API to use. This should be set to '6.0' to use this version of the api.
**$top** | query |   | integerint32 | [optional] Maximum number of refs to return. It cannot be bigger than 1000. If it is not provided but *continuationToken* is, top will default to 100.
**continuationToken** | query |   | string | The continuation token used for pagination.
filter | query |   | string | [optional] A filter to apply to the refs (starts with).
filterContains | query |   | string | [optional] A filter to apply to the refs (contains).
includeLinks | query |   | boolean | [optional] Specifies if referenceLinks should be included in the result. default is false.
includeMyBranches | query |   | boolean | [optional] Includes only branches that the user owns, the branches the user favorites, and the default branch. The default value is false. Cannot be combined with the filter parameter.
includeStatuses | query |   | boolean | [optional] Includes up to the first 1000 commit statuses for each ref. The default value is false.
latestStatusesOnly | query |   | boolean | [optional] True to include only the tip commit status for each ref. This option requires includeStatuses to be true. The default value is false.
peelTags | query |   | boolean | [optional] Annotated tags will populate the PeeledObjectId property. default is false.

The API as is does not support `$top` and `continuationToken` - so my guess is that the `IGitApi.getRefs` endpoint will return the first 100 refs only.

Am I reading this correctly?  Could this support be added please?  Thanks!

**Comment by vtbassmatt** [comment]
Hi @johnnyreilly - Martin Woodward sent your tweet my way. Sorry we haven't been super responsive here!

These clients are generated from the server-side controllers, and at a glance, I don't understand why those two parameters weren't included. Full transparency, we don't dedicate a lot of cycles here, but I will get it on the team's radar to investigate/improve.

**Comment by johnnyreilly** [comment]
Thanks @vtbassmatt - much appreciated!  And thanks Martin for sending the tweet to Matt! ❤️🌻

**Comment by johnnyreilly** [comment]
Just a heads up that I think I've found another "missing piece" 😄 - see https://github.com/microsoft/azure-devops-node-api/issues/416

**Comment by johnnyreilly** [comment]
I was just reading this article about how AutoRest is used to generate client libs:

https://devblogs.microsoft.com/azure-sdk/code-generation-with-autorest/

Does that include this client lib?

**Comment by johnnyreilly** [comment]
Hey @vtbassmatt / @mjroghelia 

Is there any way to follow along when this might work on / get shipped? I've been reaching around to try and find any public facing milestones around Azure DevOps APIs but haven't happened upon anything. Would you happen to know?

**Comment by vtbassmatt** [comment]
There's not another way to follow along besides this issue, I'm afraid.

I don't think we fully onboarded with AutoRest - our C# clients predate its introduction in Azure, for example. But I think we do use them in at least the Python client.

**Comment by johnnyreilly** [comment]
> There's not another way to follow along besides this issue, I'm afraid.

Cool, no worries @vtbassmatt - thought I'd check. I'm new to all this AzureDevOps stuff

**Comment by johnnyreilly** [comment]
Just pre-empting stalebot - this isn't stale

**Comment by johnnyreilly** [comment]
Please could this issue be opened?  It hasn't been resolved.  [I've written a blog post which documents a workaround](https://blog.johnnyreilly.com/2020/10/31/azure-devops-node-api-git-api-getrefs-wiki-api#handrolled-git-api) for anyone else who is struggling with this.

**Comment by SamJ07** [comment]
Can this please be re-opened? It is still not fixed.
