### ISSUE TITLE
Getting authentication issues after updating to latest typed-rest-client

### ISSUE THREAD

**Issue by christiango** [microsoft/azure-devops-node-api#419]
### Environment
Node version: 12.13.0
Npm version: 6.12.0
OS and version: Windows 10
azure-devops-node-api version: 10.1.1

### Issue Description
We use the azure-devops-node-api in some Azure Devops pipeline to do things like write comments to the PR. This was working fine until 11/6/2020 when we happened to have an auto update of our lockfile that took typed-rest-client (which is a dependency of azure-devops-node-api) from version 1.7.3 to 1.8.0.

What we are seeing is the following error
```
Error: TF400813: The user '' is not authorized to access this resource.
    at s (/home/vsts/work/1/a/bundle-buddy-cli/bundleBuddyCli.js:41:48158)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  statusCode: 401,
  result: {
    '$id': '1',
    innerException: null,
    message: "TF400813: The user '' is not authorized to access this resource.",
    typeName: 'Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server',
    typeKey: 'UnauthorizedRequestException',
    errorCode: 0,
    eventId: 3000
  }
}

```
When using --inspect-brk to break on this error, it seems to be happening on an options call that gets triggered when we call getGitApi and then it makes a call to ._getResourceAreaUrl

    public async getGitApi(serverUrl?: string, handlers?: VsoBaseInterfaces.IRequestHandler[]): Promise<gitm.IGitApi> {
        serverUrl = await this._getResourceAreaUrl(serverUrl || this.serverUrl, gitm.GitApi.RESOURCE_AREA_ID);
        handlers = handlers || [this.authHandler];
        return new gitm.GitApi(serverUrl, handlers, this.options);
    }

We reverted types-rest-client in our lockfile back to 1.7.3 and everything is working again on our side. Logging the issue in case others hit this or in case someone knows of a fix.

**Comment by johnnyreilly** [comment]
Maybe it's worth putting an issue against the repo:

https://github.com/microsoft/typed-rest-client

I wonder if this might be related to: https://github.com/microsoft/typed-rest-client/pull/238

cc @anatolybolshakov @damccorm

**Comment by damccorm** [comment]
@anatolybolshakov could you or your team take a look?

**Comment by JamieMagee** [comment]
I dug into this a bit more, as I'm being hit by it. It looks like [this commit](https://github.com/microsoft/typed-rest-client/commit/f9ff755631b982ee1303dfc3e3c823d0d31233e8) introduced the issue.

I think the solution is to set `allowCrossOriginAuthentication` to `true`, or the very least, expose it as a parameter in [the authentication handler methods](https://github.com/microsoft/azure-devops-node-api/blob/cf9a8734ac8a2e3fa919fcab0db65fbb0aa78d40/api/WebApi.ts#L50-L73)

**Comment by anatolybolshakov** [comment]
@JamieMagee thanks for digging into this! I created [PR](https://github.com/microsoft/azure-devops-node-api/pull/420) with exposing this as a parameter.

**Comment by JamieMagee** [comment]
@anatolybolshakov Thanks for the quick PR. Can you publish version `10.1.2` to npm?

**Comment by jjguijt** [comment]
I have encountered the same issue, a quick push to npm would be appreciated. Thanks for the quick work on this!

**Comment by damccorm** [comment]
This has been published

**Comment by anatolybolshakov** [comment]
Thanks @damccorm!
@christiango @JamieMagee @jjguijt could you please check that it works for you currently?

**Comment by johnnyreilly** [comment]
I think it might not be fixed - just experimenting.

**Comment by johnnyreilly** [comment]
I'm experiencing this: 

```shell
TF400813: The user '' is not authorized to access this resource.

Error: TF400813: The user '' is not authorized to access this resource.
    at RestClient.<anonymous> (/home/vsts/work/1/s/node_modules/typed-rest-client/RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/node_modules/typed-rest-client/RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  statusCode: 401,
  result: {
    '$id': '1',
    innerException: null,
    message: "TF400813: The user '' is not authorized to access this resource.",
    typeName: 'Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server',
    typeKey: 'UnauthorizedRequestException',
    errorCode: 0,
    eventId: 3000
  }
}
```

However I've pinned to 1.7.3 and am still experiencing the issue - it's possible my own issue is different

```
  "resolutions": {
    "typed-rest-client": "1.7.3"
  }
```

**Comment by johnnyreilly** [comment]
Yup - it was a different issue. This works for me!

**Comment by christiango** [comment]
Confirmed the latest version works when you pass the new parameter through to the handlers. Thanks for the quick turnaround!
