### ISSUE TITLE
Regenerate API for API version 6.0

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/azure-devops-node-api#422]
The latest version of `azure-devops-node-api`, `6.6.2`, targets API version `6.0-preview.1`. However, the stable version of `6.0` has been released. Can you please regenerate the API client to target the latest version?

**Comment by svanzoest** [comment]
This update would be appreciated

**Comment by JamieMagee** [comment]
@damccorm Could you please reopen this issue and `genclient`?
