### ISSUE TITLE
getCommitDiffs not sending diffCommonCommit as parameter in the request

### ISSUE THREAD

**Issue by ankitbko** [microsoft/azure-devops-node-api#429]
This is because the parameter type is boolean which makes this statement true when diffCommonCommit is set to false  https://github.com/microsoft/azure-devops-node-api/blob/470f9ca7bdfccd87e1c1fdea8023b8c3d2b1047a/api/VsoClient.ts#L188

**Comment by ankitbko** [comment]
@damccorm Can you please have a look at this? My project is kind of stuck due to this. I am happy to fix this but want someone from team to look at this first.

**Comment by rzulkoski** [comment]
I'm running into this issue as well, even on 11.0.0. Did you get this resolved @ankitbko?

**Comment by ankitbko** [comment]
@rzulkoski a workaround is to pass the param as `string` typecast it as `any`
`await git?.getCommitDiffs(repoId, undefined, String(diffCommonCommit) as any, undefined, undefined, base, target);`

**Comment by rzulkoski** [comment]
Thanks for the tip!
