### ISSUE TITLE
Incorrect HOST header is sent with requests

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/azure-devops-node-api#44]
See https://github.com/Microsoft/tfs-cli/issues/123

**Comment by stephenmichaelf** [comment]
@damccorm

**Comment by damccorm** [comment]
Looking at https://github.com/Microsoft/azure-devops-node-api/pull/233, it looks like we're now sending headers in a much different way than we were and I was unable to reproduce. I'm going to close, feel free to reopen if this issue persists.
