### ISSUE TITLE
https://dev.azure.com/_apis/Location is NOT FOUND

### ISSUE THREAD

**Issue by Phoebe-0319** [microsoft/azure-devops-node-api#442]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 8.9.4
Npm version: 5.6.0
OS and version: Windows 10
azure-devops-node-api version: 6.6.3

### Issue Description
Currently we develop in SharePoint-OnPrem, when we call getGitApi in WebApi.ts, we find that https://dev.azure.com/_apis/Location is NOT FOUND. This issue has blocked some our build tasks

### Expected behaviour
Successfully call getGitApi in WebApi.ts 

### Call Stack is here
getGitApi in WebApi.ts ->
_getResourceAreaUrl in WebApi.ts ->
_getResourceAreas in WebApi.ts ->
getResourceAreas in LocationsApi.ts ->
getVersioningData in VsoClient.ts ->
beginGetLocation in VsoClient.ts ->
beginGetAreaLocations in VsoClient.tsi ->
requestUrl: https://dev.azure.com/_apis/Location **[404]**

**Comment by EzzhevNikita** [comment]
Hi @Phoebe-0319, this ticket seems to be similar to this [one](https://github.com/microsoft/azure-devops-node-api/issues/377), could you please try to check if the solution from [this comment](https://github.com/microsoft/azure-devops-node-api/issues/377#issuecomment-607615816) works for you?

**Comment by Phoebe-0319** [comment]
> Hi @Phoebe-0319, this ticket seems to be similar to this [one](https://github.com/microsoft/azure-devops-node-api/issues/377), could you please try to check if the solution from [this comment](https://github.com/microsoft/azure-devops-node-api/issues/377#issuecomment-607615816) works for you?

Hi @edgarrs, thanks for your quick response. I have tried the workaround as you mentioned, but it could not work. Because '/_apis' is provided in inner code - [beginGetAreaLocations in VsoClient.ts](https://github.com/microsoft/azure-devops-node-api/blob/470f9ca7bdfccd87e1c1fdea8023b8c3d2b1047a/api/VsoClient.ts#L160)

Could you please help to resolve this issue? This issue has blocked our developing process for a while.

**Comment by EzzhevNikita** [comment]
@Phoebe-0319 How do you create a WebApi instance? I have tried the simple script with initializing of WebApi and getting getGitApi looks like it working for me.
Also as I see from your stack trace request address is not quite correct:
instead of _https://dev.azure.com/_apis/Location_  it should be _https://dev.azure.com/YourOrgName/_apis/Location_ .So I assume you need to change _defaultUrl_ when you create WebApi client from _https://dev.azure.com/_ to  _https://dev.azure.com/YourOrgName/_.
Could you please try to do it?

**Comment by EzzhevNikita** [comment]
@Phoebe-0319 Is it still actuall issue for you?

**Comment by EzzhevNikita** [comment]
Since there no updates for this issue for a long time, I'm closing it currently. Feel free to reopen it if the issue still actual for you.
