### ISSUE TITLE
Error: Failed request: (401) with basic sample

### ISSUE THREAD

**Issue by eosgortor** [microsoft/azure-devops-node-api#456]
### Environment
Node version: 14.15.4
Npm version: 6.14.10
OS and version: Windows Version 10.0.18363 Build 18363
azure-devops-node-api version: 11.0.1

### Issue Description
I`m trying to run the sample below from dev environment and get an error.

### Expected behaviour
The sample I run should work. The PAT and server url are working in an RestClient like Insomnia or Postman.

### Actual behaviour
An error is issued when VsoClient.js sends the options request, which does not have authorization headers (line 121). See below for the stacktrace.

### Steps to reproduce
I tried to execute a most basic example,:
```
    let orgUrl = "https://.../tfs";

    let token: string = '...';
    let project= '...';

    let authHandler = azdev.getPersonalAccessTokenHandler(token); 
    let connection = new azdev.WebApi(orgUrl, authHandler, {ignoreSslError:true}); 
    let build: ba.IBuildApi = await connection.getBuildApi();
    let defs: bi.DefinitionReference[] = await build.getDefinitions(project);
```

### Logs
```
(node:12508) UnhandledPromiseRejectionWarning: Error: Failed request: (401)
    at RestClient.<anonymous> (D:\git\TFSExtensions\Extensions\ReleaseNoteManager\dist\tasks\generateReleaseNotesMarkdown\index.js:58025:31)
    at Generator.next (<anonymous>)
    at fulfilled (D:\git\TFSExtensions\Extensions\ReleaseNoteManager\dist\tasks\generateReleaseNotesMarkdown\index.js:57829:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by anatolybolshakov** [comment]
Hi @eosgortor could you please check that PAT token is valid as not expired, and all necessary scopes are granted?

**Comment by eosgortor** [comment]
The PAT is working when using it in Insomnia. So it should be ok.

**Comment by anatolybolshakov** [comment]
@eosgortor which scopes do you have enabled for PAT?

**Comment by eosgortor** [comment]
All scopes are enables. It has full access.

Maybe I should emphazise again: The error occures when the HTTP-OPTIONS request is sent, which has no authorization headers. Is that meant to be that way?

**Comment by eosgortor** [comment]
Yes, we are using an on-prem server. The admin can configure the unauthorized options request? A quick search in www revealed nothing.

**Comment by balazsorban44** [comment]
Facing a similar issue, this might be related: https://github.com/MicrosoftDocs/azure-devops-docs/issues/11065

Using the documented scope, I could not execute a method. I had to assign a higher scope than documented.

**Comment by eosgortor** [comment]
> Facing a similar issue, this might be related: [MicrosoftDocs/azure-devops-docs#11065](https://github.com/MicrosoftDocs/azure-devops-docs/issues/11065)
> 
> Using the documented scope, I could not execute a method. I had to assign a higher scope than documented.

I guess that's not my problem, as I already gave full access to the token. But thanks for having a look.

**Comment by alexander-smolyakov** [comment]
@eosgortor is this issue still actual to you?

**Comment by eosgortor** [comment]
Yes, still the same behaviour. Maybe I can provide some logs?

**Comment by alexander-smolyakov** [comment]
> still the same behaviour. Maybe I can provide some logs?

@eosgortor, it will be great if you can share logs, you could also send them to my email: v-alsmo@microsoft.com

**Comment by alexander-smolyakov** [comment]
@edgarrs, it seems the problem could be related to the organization URL. Could you try adding `DefaultCollection` to the organization URL (e.g. `http://(tfsserver)/DefaultCollection/`) and see if the problem still persists?

**Comment by eosgortor** [comment]
That did the trick. Thank you very much. 

Would be great to document this somehow.
