### ISSUE TITLE
Errors when I try to call new azdev.WebApi(...)

### ISSUE THREAD

**Issue by sergiusxp** [microsoft/azure-devops-node-api#459]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 12.14.1
Npm version: 6.13.4
OS and version: Win10
azure-devops-node-api version: 8.1.1

### Issue Description
Hi, I am trying to make a connection but I get some errors that I cannot figure out

`let authHandler = azdev.getPersonalAccessTokenHandler(
      await SDK.getAccessToken()
    );
    let connection = new azdev.WebApi(organizationUrl, authHandler);`

### Expected behaviour
I expect to get a connection working

### Actual behaviour
I get those errors:

_ERROR in ./node_modules/azure-devops-node-api/WebApi.js
Module not found: Error: Can't resolve 'fs' in 'C:\Teams-FHL-Project-1\extension\teams-fhl-code-coverage\node_modules\azure-devops-node-api'
 @ ./node_modules/azure-devops-node-api/WebApi.js 44:11-24
 @ ./src/code-coverage-tab/code-coverage-tab.tsx

ERROR in ./node_modules/typed-rest-client/HttpClient.js
Module not found: Error: Can't resolve 'fs' in 'C:\Teams-FHL-Project-1\extension\teams-fhl-code-coverage\node_modules\typed-rest-client'
 @ ./node_modules/typed-rest-client/HttpClient.js 17:11-24
 @ ./node_modules/azure-devops-node-api/FileContainerApi.js
 @ ./node_modules/azure-devops-node-api/WebApi.js
 @ ./src/code-coverage-tab/code-coverage-tab.tsx

ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'net' in 'C:\Teams-FHL-Project-1\extension\teams-fhl-code-coverage\node_modules\tunnel\lib'
 @ ./node_modules/tunnel/lib/tunnel.js 3:10-24
 @ ./node_modules/tunnel/index.js
 @ ./node_modules/typed-rest-client/HttpClient.js
 @ ./node_modules/azure-devops-node-api/FileContainerApi.js
 @ ./node_modules/azure-devops-node-api/WebApi.js
 @ ./src/code-coverage-tab/code-coverage-tab.tsx

ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'tls' in 'C:\Teams-FHL-Project-1\extension\teams-fhl-code-coverage\node_modules\tunnel\lib'
 @ ./node_modules/tunnel/lib/tunnel.js 4:10-24
 @ ./node_modules/tunnel/index.js
 @ ./node_modules/typed-rest-client/HttpClient.js
 @ ./node_modules/azure-devops-node-api/FileContainerApi.js
 @ ./node_modules/azure-devops-node-api/WebApi.js
 @ ./src/code-coverage-tab/code-coverage-tab.tsx
i ｢wdm｣: Failed to compile.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
^CThe system cannot open the device or file specified._

**Comment by kuleshovilya** [comment]
Hello @sergiusxp . That doesn't seem to be an api or library issue. Please, check those links below for similar issues:
https://stackoverflow.com/questions/57161839/module-not-found-error-cant-resolve-fs-in
https://stackoverflow.com/questions/61936085/error-from-chokidar-c-error-ebusy-resource-busy-or-locked-lstat-c-dump

**Comment by kuleshovilya** [comment]
Any update on the issue?

**Comment by kuleshovilya** [comment]
I'll close issue for now. Please, feel free to reopen it or ping me at v-ikuleshov@microsoft.com
