### ISSUE TITLE
Question: is it possible to use credential provided by vscode extension vscode-azure-account ?

### ISSUE THREAD

**Issue by pkrukp** [microsoft/azure-devops-node-api#460]
Hi,

I would like to interact with Azure DevOps (for example download pipeline run published artifact). 
I would like to do that from VSCode extension.
VSCode has [Azure Account extension](https://github.com/microsoft/vscode-azure-account) which provides Azure Sign-In functionality for VSCode.

Is it possible to use credentials provided by the Azure Account extension with this  Azure DevOps Client ?

From what I see Azure DevOps Client requires organization url and personal access token. They don't seem to be available from Azure Account. It provides "user id", "tenant id", and ServiceClientCredentials/TokenCredentialsBase (https://github.com/microsoft/vscode-azure-account/blob/6c2d9b4d5137b77cb3ea9fa5c9fe3bf8cfedd95c/src/azure-account.api.d.ts#L30)

Any suggestions appreciated.
Thanks.

**Comment by pkrukp** [comment]
I made some progress - I can get access token from Azure Account extension like this: https://github.com/microsoft/vscode-azure-account/issues/260

But now I need "organization url". According to https://stackoverflow.com/questions/53608013/get-all-organizations-via-rest-api-for-azure-devops I can get "public alias" from my profile and pass it to "azure accounts" api. Two issues:
1. I don't see "accounts api" in azure-devops-node-api
2. (minor) "publicAlias" seems to be missing from typescript definitions?

```
// get access token from Azure Account extension
const token = await session.credentials2.getToken();
const authHandler = azdev.getPersonalAccessTokenHandler(token.accessToken);

// get "public alias" from profile of currently logged in user:
const webApi = new azdev.WebApi("https://vssps.dev.azure.com", authHandler);
const profileApi = await webApi.getProfileApi();
const myProfile = await profileApi.getProfile("me");
// "publicAlias" can be seen in runtime but typescript compiler complains that it's not available...
const publicAlias = (myProfile as any).publicAlias; 

// now, how to get list of organizations?
```

**Comment by pkrukp** [comment]
I was able to get a list of organizations like this (had to use a rest client):

```
const header = { 'Authorization': token.accessToken, 'Content-Type': "application/json" } as IHeaders;
const response = webApi.rest.client.get('https://app.vssps.visualstudio.com/_apis/accounts?memberId=' + publicAlias + '&api-version=6.1-preview.1', header);
const json = response.readBody();
const accounts = JSON.parse(json) as IAccountsResponse;
// organizations are in accounts.value[i].accountName
```

**Comment by kuleshovilya** [comment]
Hello @pkrukp . Glad you figured it out, is that what you needed? Or is there anything else?

**Comment by pkrukp** [comment]
Hi @kuleshovilya 

Could you confirm that this is correct way? I mean:
- are the steps correct
- is there no "accounts" api in azure-devops-node-api

It seems to be working, but I'd be glad to have confirmation that this is recommended way (maybe I'm using some internal api that could change at any moment, or it won't for in some cases?)

**Comment by kuleshovilya** [comment]
Yeah, for those purposes you'll need to use RestAPI, node API is for different purposes. There's a profile API, but that won't produce the data you need.

**Comment by pkrukp** [comment]
Thanks, in that case, I'm closing this issue. 

(Although, as a side note, I'd expect "accounts" to be part of this extension - it's part of DevOps REST API as far as I understand)
