### ISSUE TITLE
getCommitDiffs not showing changes between branches

### ISSUE THREAD

**Issue by BenHesketh21** [microsoft/azure-devops-node-api#466]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: v14.17.5
Npm version: 6.14.14
OS and version: Debian 9.13 Stretch
azure-devops-node-api version: 10.1.1 I think

### Issue Description

The getCommitDiffs function in the GitApi does not work as expected for checking the differences between branches.

### Expected behaviour

```typescript
    const vstsGit = await this.openGitConnection();
    const branch: GitVersionType = 0;
    const options: GitVersionOptions = 0;
    const sourceVersionDesc: GitBaseVersionDescriptor = {
      baseVersion:  'main', // sourceBranch
      baseVersionType: branch,
      baseVersionOptions: options,
    };

    const targetVersionDesc: GitTargetVersionDescriptor = {
      targetVersion: 'new-stuff', // targetBranch
      targetVersionType: branch,
      targetVersionOptions: options,
    };

    const changes = await vstsGit.getCommitDiffs(repoId, project, false, 0, 0, sourceVersionDesc, targetVersionDesc);
```

Should get a response like

```json
{
  allChangesIncluded: true,
  changeCounts: {},
  changes: [],
  commonCommit: 'commit-id',
  baseCommit: 'commit-id',
  targetCommit: 'commit-id',
  aheadCount: 213,
  behindCount: 21
}
```

### Actual behaviour

Get this response for every combination of branches

```json
{
  allChangesIncluded: true,
  changeCounts: {},
  changes: [],
  commonCommit: 'commit-id',
  baseCommit: 'same-commit-as-above',
  targetCommit: 'same-commit-as-above',
  aheadCount: 0,
  behindCount: 0
}
```

**Comment by Cugtyt** [comment]
``` typescript
const changes = await this.gitApi?.getCommitDiffs(this.repository!.id!, undefined, false, undefined, undefined, 
<GitInterfaces.GitBaseVersionDescriptor>{ version: sourceCommitId, versionType: GitInterfaces.GitVersionType.Commit }, 
<GitInterfaces.GitTargetVersionDescriptor>{ version: targetCommitId, versionType: GitInterfaces.GitVersionType.Commit })!;

console.log(`Changes ${pr.sourceRefName} ${pr.targetRefName}: ${changes.changes!.length} ${changes.baseCommit!} ${changes.targetCommit!} ${changes.commonCommit}`);
```

Changes refs/heads/cug/no-harm-logs refs/heads/main: 0 58b5e315a40cc1d810792c1394789239d3f37edf e042f825d0849d04fe48f2fd7b9443d44e488b77 e042f825d0849d04fe48f2fd7b9443d44e488b77

getCommitDiffs return empty changes, but there is a file change.
![image](https://user-images.githubusercontent.com/16632454/145599849-bdcfa79f-a08e-418f-8aed-66487c57a08c.png)

**Comment by BenHesketh21** [comment]
This is still broken, I have fixed it. Please can it be reviewed and merged!

**Comment by ecraig12345** [comment]
I hit this issue too. Based on the source, it looks like you need to use just `version`, `versionType`, and `versionOptions` for both the base and target object params.
https://github.com/microsoft/azure-devops-node-api/blob/55908ae28d367e7b30c167f679c4f1087f647cb2/api/GitApi.ts#L1125-L1134
