### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null in FileContainerApi

### ISSUE THREAD

**Issue by maikelvanhaaren** [microsoft/azure-devops-node-api#468]
### Environment
Node version: v14.18.1
Npm version: 6.14.15
OS and version: Windows 10
azure-devops-node-api version: 11.0.1

### Issue Description
Started with a fresh install of standard nuxt3 (beta) project and included the azure-devops-node-api package. Copied the first sample in my code with a correct organization URL and access token. 

### Expected behaviour
Returned a valid instance of the API client which is connected.

### Actual behaviour
Type error occured:

`entry.mjs:39 Error while mounting app: TypeError: Class extends value undefined is not a constructor or null
    at node_modules/azure-devops-node-api/FileContainerApi.js (FileContainerApi.js:141)
    at __require (chunk-XNAE4CLY.js?v=d7f59cdd:7)
    at node_modules/azure-devops-node-api/WebApi.js (WebApi.js:18)
    at __require (chunk-XNAE4CLY.js?v=d7f59cdd:7)
    at dep:azure-devops-node-api:1`

### Steps to reproduce
1. Create new project with nuxt3-beta
2. Add azure-devops-node-api
3. Use sample described in the README:

```
import * as azdev from "azure-devops-node-api";

// your collection url
let orgUrl = "https://dev.azure.com/yourorgname";

let token: string = process.env.AZURE_PERSONAL_ACCESS_TOKEN;

let authHandler = azdev.getPersonalAccessTokenHandler(token); 
let connection = new azdev.WebApi(orgUrl, authHandler);    
```

**Comment by max-zaytsev** [comment]
Hi @maikelvanhaaren,
Checked manually. Example works as expected

Take a look at [samples](https://github.com/microsoft/azure-devops-node-api/blob/master/samples/filecontainer.ts) to see how it works with FileContainerApi

```bash
npm run samples -- filecontainer
```
Closing the issue for now.
Please reopen if you still have any questions.
