### ISSUE TITLE
Not able to create attachments other than .txt files

### ISSUE THREAD

**Issue by SimonKib** [microsoft/azure-devops-node-api#469]
Similar to earlier reported issue (https://github.com/microsoft/azure-devops-node-api/issues/401), but with some more detail...

### Environment
Node version: 16.3.0
Npm version: 7.15.1
OS and version: MacOS 11.6
azure-devops-node-api version: 11.0.1

### Issue Description

Uploading file using busboy to take a form uploaded file and create filestream...
```
// then...
const readableStream: NodeJS.ReadableStream = Readable.from(file.fileStreamData)
result = await workItemTrackingApi.createAttachment(null, readableStream, file.filename)
```

...This returns an object with id and url.

```
{
  id: '97d7b9ef-f420-4782-a2f6-2fece531dd1b',
  url: 'https://[MY ORGANISATION].visualstudio.com/21066450-5b08-4133-a0ee-5825033500cd/_apis/wit/attachments/97d7b9ef-f420-4782-a2f6-2fece531dd1b?fileName=knitter.jpg'
}
```

### Expected behaviour
I would then expect the url to point to a file that works.

### Actual behaviour
I have tried with .jpg, .pdf and .txt
The url points to a working file, only when uploading a .txt file.
Can I somehow tell createAttachment() what format the readableStream is, or should I create the readable stream in another way?

### Steps to reproduce
1. const readableStream = Readable.from(someBuffer);
2. WorkItemTrackingApi.createAttachment(readableStream, 'filename') => get attachment reference with id and url

**Comment by SimonKib** [comment]
@max-zaytsev is this a bug or something you've experienced in other cases? Is there a workaround to this ?
Br, Simon

**Comment by SimonKib** [comment]
Is this repo maintained anymore?

**Comment by tatyana-kostromskaya** [comment]
Hi @SimonKib, I tried this api function on local files with different formats and it worked fine.
For example:
```
    const buffFile: Buffer = fs.createReadStream("test.png");
    const readableStream = Readable.from(buffFile);
    const result = await witApi.createAttachment(null, readableStream, "test.png");
```

There is no way to tell createAttachment() what format the readableStream is, but it should work fine with any format.

Could you please check that you correctly get file content?

**Comment by tatyana-kostromskaya** [comment]
Closing this ticket due to inactivity.
