### ISSUE TITLE
Question: Where is the approvals/checks API?

### ISSUE THREAD

**Issue by LennartOlsen** [microsoft/azure-devops-node-api#471]
### Environment
Node version: v14.17.4
Npm version: 6.14.14
OS and version: macos 11.6
azure-devops-node-api version: 11.0.1

### Issue Description
In order to support approving pipeline "releases" in our dashboard we would need to use for the approval API; [https://docs.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks](https://docs.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/?view=azure-devops-rest-6.1).

I cant seem to find it in the code or the docs, i know that there is Release Approval support.

### Expected behaviour
If the Approvals and Checks API is there the docs need to be improved, if not the API should be supported.

**Comment by waqasraz** [comment]
anyone?
