### ISSUE TITLE
Feature request: Support API that contains flakyIdentifiers

### ISSUE THREAD

**Issue by victorddiniz** [microsoft/azure-devops-node-api#476]
### Environment
Node version: v14.15.4
Npm version: 7.17.0
OS and version: Windows 10 Enterprise - 21H2
azure-devops-node-api version: 11.1.0

### Issue Description
I am interested in fetching the flaky identifiers of a test. [According to Azure DevOps Rest ](https://docs.microsoft.com/en-us/rest/api/azure/devops/testresults/result-meta-data/query?view=azure-devops-rest-6.0#testflakyidentifier)API, that information can be retrieved from the test metadata.
I was using `TestClient.queryTestResultsMetatadata` to retrieve the metadata. However, the information is not returned from the call. Investigating further, I realized it does not return the information I need because `TestClient.queryTestResultsMetadata` calls endpoint `{domain}/_apis/test/Results/ResultMetaData?api-version={version}`, which is not the same endpoint as in the aforementioned documentation, that is `{domain}/_apis/testresults/results/ResultMetaData?api-version={version}`.

### Expected behaviour
Expose an API where **FlakyIdentifiers** can be retrieved.

### Actual behaviour
Behavior does not exist in version.

### Steps to reproduce
Since it is a feature request, there is no way to reproduce.

### Logs
Below I've attached an example of the return objects from each of the endpoints and you can observe how one returns **FlakyIdentifiers**, while the other doesn't although they represent the same test reference.

**Return object from `{domain}/_apis/test/Results/ResultMetaData?api-version={version}` (Done by `TestClient.queryTestResultsMetadata`):**

```json
{
    "count": 1,
    "value": [
        {
            "testCaseReferenceId": 35581759,
            "priority": 0,
            "automatedTestStorage": "jest.config.json",
            "automatedTestName": "VP-Mock Image suite edge Verify non-intercepted image is mocked. [ow:example@email.com] <edge>::VP-Mock Image suite edge Verify non-intercepted image is mocked. [ow:example@email.com] <edge>::testProject\\mockImage\\mockImage.spec.js",
            "testCaseTitle": "VP-Mock Image suite > edge > Verify non-intercepted image is mocked. [ow:example@email.com] <edge>",
            "owner": ""
        }
    ]
}
```

**Return object from `{domain}/_apis/testresults/results/ResultMetaData?api-version={version}` (Feature request):**

```json
{
    "count": 1,
    "value": [
        {
            "testCaseReferenceId": 35581759,
            "priority": 0,
            "automatedTestStorage": "jest.config.json",
            "automatedTestName": "VP-Mock Image suite edge Verify non-intercepted image is mocked. [ow:example@email.com] <edge>::VP-Mock Image suite edge Verify non-intercepted image is mocked. [ow:example@email.com] <edge>::testProject\\mockImage\\mockImage.spec.js",
            "testCaseTitle": "VP-Mock Image suite > edge > Verify non-intercepted image is mocked. [ow:example@email.com] <edge>",
            "owner": "",
            "flakyIdentifiers": [
                {
                    "branchName": "refs/heads/main",
                    "isFlaky": true
                }
            ]
        }
    ]
}
```

**Comment by AndreyIvanov42** [comment]
"Test Results" is a deployment level API. At the moment, there are certain difficulties with providing this kind of API as part of autogenerated REST clients (this repository belongs to them). My recommendation for now would be to just create/send the requests using the typed-rest-client.
