### ISSUE TITLE
Interacting with @azure/identity

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/azure-devops-node-api#479]
### Environment
Node version: 12 & 14
Npm version: 0.35
OS and version: MacOS 10.15 Catalina
azure-devops-node-api version: 11.1.0

### Issue Description
Locally, we have a CLI tool we've developed using `azure-devops-node-api`, and the way I get the personal access token for the developer is to call `az account get-access-token` behind the scenes, and that works great.

However, I'd like to widen our audience without having to tell a bunch of additional folks to go and install the az CLI tool.  It looks like I could use the `@azure/identity` package (for example) to get az's "open your local browser, click Login, return to Terminal and be logged in" flow, without having to install `az` -- but, I'm not sure how to hook up the identity package's `DefaultAzureCredential` with the `RequestHandlers` that this package uses.

Is there an example anywhere of how I could use `@azure/identity` to get a working access token, and then unwrap them and it pass it into `azure-devops-node-api`?

**Comment by anatolybolshakov** [comment]
@elliot-nelson we are currently working on more prioritized tickets - will get back shortly once we'll have capacity.
