### ISSUE TITLE
Rate limits from Azure DevOps

### ISSUE THREAD

**Issue by szwalkowski** [microsoft/azure-devops-node-api#480]
Does this library anyhow support rate limiting? 
https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops
Can't find anything in docs, nor in code unfortunately.

**Comment by anatolybolshakov** [comment]
Hi @szwalkowski there is no support for proactive Rate limits check as described in [docs](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#api-client-experience) at the moment.

**Comment by szwalkowski** [comment]
@anatolybolshakov got it, thanks!
