### ISSUE TITLE
Question about external authentication

### ISSUE THREAD

**Issue by recs182** [microsoft/azure-devops-node-api#482]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 16.13.1
Npm version: 8.1.2
OS and version: Windows 10
azure-devops-node-api version: 

### Issue Description

People at work found this library very useful because we have tons of automations that interact with azure-devops api but we could not see a way of using it without make the authentication directly at the application.
Could exist a way of the authentication process be abstracted at a gateway instead of doing it at the application (passing token to the library) ?

In this way the library would just call an endpoint that would act like a proxy just for authentication, the library would just provide the abstractions for the APIs, just this would help immensely.

**Comment by tatyana-kostromskaya** [comment]
Hi @recs182 , as far as I know there is no way to make external authentication for this library. 
But still you can use different authentication methods to get tokens outside and pass them to the app.

**Comment by recs182** [comment]
Thank you
