### ISSUE TITLE
Feature Request: Add "Code Search" to the client library

### ISSUE THREAD

**Issue by lszomoru** [microsoft/azure-devops-node-api#483]
Could you please add "[code search](https://docs.microsoft.com/en-us/rest/api/azure/devops/search/code-search-results/fetch-code-search-results?view=azure-devops-rest-7.1)" to the client library?

**Comment by EzzhevNikita** [comment]
@lszomoru Thanks for the issue-reporting in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.

**Comment by jackmtpt** [comment]
Can this be re-opened? It's clearly not completed.
