### ISSUE TITLE
Pagination not working on Node 14.x or 16.x

### ISSUE THREAD

**Issue by mmajcica** [microsoft/azure-devops-node-api#484]
### Environment
Node version: v16.13.1
Npm version: 8.1.2
OS and version: Windows 10 1909
azure-devops-node-api version: 11.1.0

### Issue Description
Pagination calls do fail if the code is running on Node 16.x or 14.x.

### Expected behavior
```
    let coreApi = await connection.getCoreApi();

    let projects = await coreApi.getProjects();

    let projects2 = await coreApi.getProjects(undefined, undefined, undefined, "100", undefined);
```

Expected to have 100 elements in the projects variable and 15 in the projects2 variable.

### Actual behavior
The first call is done right, we do get 100 items in that array. Second call times out:

```
Exception: Error: connect ETIMEDOUT 13.107.42.20:443
Stack: Error: connect ETIMEDOUT 13.107.42.20:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:134:14).
```

### Steps to reproduce
1.  Get an organization that has enough projects that pagination can be tested (default pagination is 100 items, so at least 101 projects necessary in the above case).
2. Run the above code or adapt it for the page size of your choice.

Seems however that this is not an issue with azure-devops-node-api library, but its dependencies. Check also my issue here https://github.com/microsoft/typed-rest-client/issues/306

**Comment by denis-tikhomirov** [comment]
@mmajcica, Thanks for the issue-reporting in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.

**Comment by mmajcica** [comment]
I found the culprit. It has to do with a typo inside the NO_PROXY env var used. Though this solves the issue, I would expect that such a typo would not cause such wired issues. This should be investigated, however not by you, but with nodejs community.
