### ISSUE TITLE
Add Support for Packaging Apis

### ISSUE THREAD

**Issue by Banner-Keith** [microsoft/azure-devops-node-api#485]
I recently needed to use the packaging apis (https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact-details/get-packages?view=azure-devops-rest-7.1)

I noticed that there is currently not support for that in this library. I instantiated the credential managers manually, and a RestClient and it works just fine.

I was thinking I could open a PR with these apis, but I see that those are apparently auto-generated or something like that.

How much effort would it be for you to add these apis to this library? Is there anything I can do to help out?

**Comment by denis-tikhomirov** [comment]
@Banner-Keith, thanks for the feedback-providing in this repository, currently we are under issues with higher priority, we will take a look at this ticket once we will have enough capacity.

**Comment by Banner-Keith** [comment]
@denis-tikhomirov  thank you for taking the time to triage this. Totally understand the priority and capacity issue. My original intent was to contribute this following your guidelines rather than giving you a to-do. But that was before I realized it was automated. Let me know if there's anything I can do to help out.

**Comment by Banner-Keith** [comment]
Not stale

**Comment by Banner-Keith** [comment]
Still wanted.
