### ISSUE TITLE
Feature Request: add support for git policy configurations api

### ISSUE THREAD

**Issue by NoamTD** [microsoft/azure-devops-node-api#491]
Can you add support for [git policy-configurations](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/policy-configurations/list?view=azure-devops-rest-5.0)?

**Comment by alexander-smolyakov** [comment]
@NoamTD thanks for your request, we've added this feature request to our backlog. We'll take a look at it once we have enough capacity.

**Comment by NoamTD** [comment]
@alexander-smolyakov are there any updates?
