### ISSUE TITLE
Improve developer UX on IBuildApi and BuildInterfaces

### ISSUE THREAD

**Issue by Everspace** [microsoft/azure-devops-node-api#492]
### Environment
azure-devops-node-api version: 11.1.1

### Issue Description
Using some functions like `IBuildApi.getBuilds()` is prone to issues due to the way it's generated making a very long signature. If you want to get every build out of a project since `minTime`, you have to remember that you're needing to call `getBuilds(project, undefined, undefined, minTime)`, maxTime? it's 3. This becomes complicated.

In addition all interfaces on say... `interfaces.BuildInterfaces` are completely `Partial`, which makes for a lot of redundant checking code. Every `Build` has an id! This does not match the documentation on [Build](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get?view=azure-devops-rest-6.0#build) in the rest API which doesn't say that any of these may not be returned.

### Expected behaviour

A signature more like...

```ts
async getBuilds(project: string, options: GetBuildsOptions)
```

and not having to go `build.id!` any time I use a non-null/undefined build.

**Comment by tatyana-kostromskaya** [comment]
Hi @Everspace , the signature of the method fully complies with the request through Rest API [Builds - List](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-6.0).
We can not change the way how it is generated, so we can not change the signature.

And as far as I can see list of properties in the interface and API documentation fully match. And properties in the interface marked as optional because this interface is used in other requests like Queue build and Update Build.

**Comment by Everspace** [comment]
Then those should `extend Partial<Build>` or `IBuild` is the interface and
then `Build` is the actual return type which is a more definite, and not
have the base be that way.

The reason I say it doesn't match is because something like `getBuild()`
returns a `Build` where the id is possibly absent. All builds returned from
`getbuilds` have the property of `id`. `id` is never undefined. In code
this requires you to handle things like `id` you need to either `build?.id
?? 0` and add a whole bunch of noisy error handling for something that
doesn't matter, or violate the purpose of typescript and ignoring this
unsafety (`build.id!`) and it obscures real places that might be undefined
(like a job not having `finishTime` yet... because it isn't finished!).

This is really hard to work with and I am seriously just considering using
the http rest calls instead.

What is the method of proposing changes to these with the team that writes
the generator, or supplying better methods around these not very developer
friendly interfaces and methods?

**Comment by tatyana-kostromskaya** [comment]
@Everspace, could you please post your question on https://developercommunity.visualstudio.com/search?space=21?
It would help to engage owners of all related areas to solve it.

**Comment by Everspace** [comment]
https://developercommunity.visualstudio.com/t/Improve-UX-for-Nodejs-SDK/1703783?space=21

I have added the feedback to the link requested.

**Comment by tatyana-kostromskaya** [comment]
I will close this issue, as now we have ticket on dev community and status will be written there
