### ISSUE TITLE
Continuation token functionality is unusable

### ISSUE THREAD

**Issue by bworline** [microsoft/azure-devops-node-api#493]
### Environment

Node version: 14.17.6
Npm version: 6.14.15
OS and version: WIn10 21H2
azure-devops-node-api version: 11.1.1

### Issue Description

How does one get a continuation token out of an azure-devops-node-api API method to pass back into the same API method?  Many methods imply that a token is returned but I don't see how.

Example:  The comments for getBuilds() say, 
`@param {string} continuationToken - A continuation token, returned by a previous call to this method, that can be used to return the next set of builds.`

The return type is a `Promise<Build[]>` array of builds, so it's unclear how a token would even be made available to the caller.

**Comment by max-zaytsev** [comment]
Hi @bworline, Thanks for reporting this. Most of the code here is auto-generated from the server-side controllers. 
In this case it might be worth hitting the endpoint directly through an http call (or using the typed-rest-client).

**Comment by max-zaytsev** [comment]
Close this for now. Please reopen if you still have any questions
