### ISSUE TITLE
Impossible to get ConnectionData if the organization name contains a hyphen

### ISSUE THREAD

**Issue by miromaksim** [microsoft/azure-devops-node-api#495]
### Environment
Node version:  16.14.2
Npm version:  8.0.0
OS and version: MacOS 12.0.1 (21A559)
azure-devops-node-api version: 11.1.1

### Issue Description
It is impossible to get ConnectionData if the organization name contains a hyphen
Code example: https://codesandbox.io/s/azure-devops-node-api-hyphen-issue-b4qc4i

### Expected behaviour
ConnectionData object should be returned

### Actual behaviour
Throw error in case of organiztion with the hyphen in the name

Error message: TF400813: The user '' is not authorized to access this resource.

### Steps to reproduce
1. Create organization with a hyphen in the name
2. Create personal access token for above organization
3. Create api via WebApi.createWithBearerToken method using token and organization URL
4. Call api.connect()

### Logs
-

My test tokens for the code example:
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/81145250/160829512-2d47276b-19a1-4a15-9c98-50195068a8e7.png">

**Comment by anatolybolshakov** [comment]
Hi @miromaksim thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one once be able to.

**Comment by anatolybolshakov** [comment]
@miromaksim btw just wanted to warn also - please avoid publishing of sensitive data like PATs in pubic sources (like https://codesandbox.io) - this could be insecure for your devops organization.

**Comment by anatolybolshakov** [comment]
@miromaksim seems like there is some issue with Azure DevOps api and org names containing hyphens - I managed to reproduce it even without node-api library... You can check it with simple get request to 'https://dev.azure.com/<orgname>/_apis/connectionData' (with http header 'Authorization: Bearer <PAT>' to authorize).
I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it and describe steps to reproduce with pure API calls

**Comment by miromaksim** [comment]
https://developercommunity.visualstudio.com/t/Some-issue-with-Azure-DevOps-API-and-org/10005143?space=21&q=https%3A%2F%2Fdev.azure.com%2Fmy-test-org-with-hyphen%2F_apis%2FconnectionData&entry=problem
