### ISSUE TITLE
How report a testCaseResult and see all the test case details, how to match reported testCaseId with existing test case

### ISSUE THREAD

**Issue by Pieras2** [microsoft/azure-devops-node-api#499]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 16.14.1
Npm version: 6.14.13
OS and version: Windows 10
azure-devops-node-api version: 11.1.1

### Issue Description
When I report test case result I don't see test case data in TFS > Test Plans > Runs > my run 

How can I call testApi method to make results visible in this view correctly the same way when I see results executing tests manually via web browser

![image](https://user-images.githubusercontent.com/53040671/162152086-c3370b43-4bdd-4366-968b-cc00ca5a0ef6.png)

My code example:

`const model = {
            name: "Test run from console – completed",
            startedDate: "2022.04.05",
            isAutomated: true,
            configurationIds: [39],
            plan: { id: planId.toString(), name: '', url: '' }
        }

        await testApi.createTestRun(model, projectName).then(async (testRun) => {
            const runId = testRun.id
            const testResult = [
                {
                    id: 72750,
                    testCaseReferenceId: 72750,
                    outcome: 'Blocked',
                    automatedTestName: 'some test title',
                    comment: 'some comment'
                },
                {
                    id: 72753,
                    testCaseReferenceId: 72753,
                    outcome: 'Failed',
                    automatedTestName: 'some test title 2',
                    comment: 'some comment 2'
                }
            ]
            await testApi.addTestResultsToTestRun(testResult, projectName, runId)`

**Comment by anatolybolshakov** [comment]
Hi @Pieras2 could you please try to pass test name as 'testCaseTitle' field of 'TestCaseResult' object instead?
For comment field - not really sure why it's not being displayed in view, and how to make it visible (if it's even possible at the moment) - I would suggest to ask in https://developercommunity.visualstudio.com/search?space=21 about it

**Comment by Pieras2** [comment]
I will try and give feedback

**Comment by Pieras2** [comment]
testCaseTitle - didn't help. I will ask the community as you said, thanks for a try.

**Comment by Pieras2** [comment]
I reported it to ms community. For me it doesn't work, even if I try though curl based on their API definition.
Their description of api is terrible. Somwhat everything described but no info about which is mandatory/optional requests order etc :( I will have to try look into webinspector how the requests are sent

**Comment by Pieras2** [comment]
For us reporting test result via Azure DevOps doesn't work. Even my developer friend didn't succeeded. The API used by Azure DevOps is different than documented and we were not able to create a test result with displayed title etc.

I skipped it.
