### ISSUE TITLE
ITestInterface to add update test fields

### ISSUE THREAD

**Issue by Kprachwani** [microsoft/azure-devops-node-api#500]
Question : can we have a new method which supports updating fields of a testcase.

Requirement : 
we are working on typescript based testcases where we wanted to use azure-devops-node-api to update automated test name and automation status fields based on passed testcase ID.

It will add support for maintaining testcases which are automated using Cypress, Typescript for angular web forms.

Could you please guide how we can achieve this functionality?
If we can have this new feature added on this node api would be really great.

Thanks so much,
Kanchan

**Comment by KprachwaniTR** [comment]
@alexander-smolyakov  Hello, Good day! 
could you please provide an update on when team will be adding this enhancement?

Thanks much
Kanchan
