### ISSUE TITLE
Git PullRequest model has `workitemRef`, but the API does not return it

### ISSUE THREAD

**Issue by XVincentX** [microsoft/azure-devops-node-api#502]
According to the [official documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-pull-request?view=azure-devops-rest-6.0) the Pull Request endpoint does *not* return any `workitemRef`, while this SDK defines the field anyway.

https://github.com/microsoft/azure-devops-node-api/blob/e3daeea0d23b9d011a88b120e53eb4f8aa475542/api/interfaces/GitInterfaces.ts#L1694

Is this a leftover or is there a way to get such data from the SDK directly?

**Comment by vmapetr** [comment]
Hi @XVincentX thanks for reporting! We are currently working on more prioritized issues but will get back to this one once be able to.

**Comment by XVincentX** [comment]
@vmapetr I would like to get in touch about this if possible. I work in Microsoft and I have been using this SDK for a couple of days now and I think there are some areas that could really use some improvements and make the experience better.

What is the best way to get in touch with you?

**Comment by SvetlanaMaliugina** [comment]
Hi @XVincentX , most of the code here is auto-generated from API definitions, and apparently, some methods cannot be generated for nodejs due to the limitations of the generation tool.
Could you please post your question on https://developercommunity.visualstudio.com/search?space=21? It would help to engage owners of all related areas to solve it.

**Comment by johnnyreilly** [comment]
I have half an idea it uses https://restsharp.dev/

**Comment by XVincentX** [comment]
This is a Node SDK, not too sure how it applies to the node sdk

**Comment by johnnyreilly** [comment]
Yeah - I stand corrected - was thinking of something else

**Comment by iivmok** [comment]
This is still an issue.

I'm using the latest version of [Microsoft.TeamFoundationServer.Client (19.212.0-preview)](https://www.nuget.org/packages/Microsoft.TeamFoundationServer.Client/19.212.0-preview), but the client just calls the REST API.

[`GetPullRequestsAsync()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.sourcecontrol.webapi.githttpclientbase.getpullrequestsasync?view=azure-devops-dotnet) call indeed does not return `WorkItemRefs[]`. I have to loop over the pull requests and fetch work items for each with [`GetPullRequestWorkItemRefsAsync()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.sourcecontrol.webapi.githttpclientbase.getpullrequestworkitemrefsasync?view=azure-devops-dotnet) which takes a lot of time and calls. Then I need to call [`GetWorkItemsAsync()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.workitemtracking.webapi.workitemtrackinghttpclientbase.getworkitemsasync?view=azure-devops-dotnet) for the work items for basic details.

**Comment by iivmok** [comment]
Not stale.
