### ISSUE TITLE
Named parameters and/or interfaces for parameters

### ISSUE THREAD

**Issue by carneirofc** [microsoft/azure-devops-node-api#504]
Some methods can accept quite a large amount of optional parameters and most cases the consumer would only require a few of them.
As it stands, the user experience when using the api is not that great and error prone.

Would a PR that includes new interfaces or methods be accepted?

The other option would be the api consumer to write a wrapper around the package, but I dont think it would scale very well.

### Issue Description
Out of the box I was thinking in a something simple proxy for the original method:

```typescript
export interface IGitApi extends basem.ClientApiBase {
...
   getItems(repositoryId: string, project?: string, scopePath?: string, recursionLevel?: GitInterfaces.VersionControlRecursionType, includeContentMetadata?: boolean, latestProcessedChange?: boolean, download?: boolean, includeLinks?: boolean, versionDescriptor?: GitInterfaces.GitVersionDescriptor): Promise<GitInterfaces.GitItem[]>;
...
}

// to

export interface IGitApi extends basem.ClientApiBase {
...
   getItems(repositoryId: string, project?: string, scopePath?: string, recursionLevel?: GitInterfaces.VersionControlRecursionType, includeContentMetadata?: boolean, latestProcessedChange?: boolean, download?: boolean, includeLinks?: boolean, versionDescriptor?: GitInterfaces.GitVersionDescriptor): Promise<GitInterfaces.GitItem[]>;
   getItems(kwargs:{repositoryId: string, project?: string, scopePath?: string, recursionLevel?: GitInterfaces.VersionControlRecursionType, includeContentMetadata?: boolean, latestProcessedChange?: boolean, download?: boolean, includeLinks?: boolean, versionDescriptor?: GitInterfaces.GitVersionDescriptor}): Promise<GitInterfaces.GitItem[]>;
...
````

**Comment by SvetlanaMaliugina** [comment]
Hi @carneirofc, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by jamiehaywood** [comment]
hi @SvetlanaMaliugina any movement on this? 

An example of @johnnyreilly's problem that I'm facing:
```ts
const releases = await releaseApi.getDeployments(
  projectId,
  definitionId,
  undefined,
  undefined,
  undefined,
  undefined,
  DeploymentStatus.All,
  undefined,
  undefined,
  undefined,
  100
)
```
which is awful for code readability.

**Comment by jamiehaywood** [comment]
not stale

**Comment by jamin84** [comment]
bump

**Comment by mccolljr** [comment]
This is becoming a pain point for my team. We are using the `BuildApi.getBuilds` API to get the list of builds for a specific repository, which looks like this:

![image](https://github.com/microsoft/azure-devops-node-api/assets/8538024/fb07b2fa-b13c-4c3b-829f-a741660f3af6)

It works, but it would be a lot nicer if we could provide an object with only the required parameters.

**Comment by mccolljr** [comment]
This was not stale
