### ISSUE TITLE
gettasks api call doesnt return tasks of all the phases snapshots

### ISSUE THREAD

**Issue by kriti218** [microsoft/azure-devops-node-api#510]
### Environment
Node version: 12
Npm version: 
OS and version: windows
azure-devops-node-api version: 10.2.2

### Issue Description
We have release pipelines which have multiple phases (including agent and agentless jobs). We are using getTasks() api call to get tasks for the release and environment but it seems it gets tasks for only the first agent job and doesnt get all tasks for all the agent jobs whereas it does get it agentless jobs.

### Expected behaviour
It should either get all the tasks for that release irrespective of agent jobs they are running under

### Actual behaviour
It gets only for first agent job

Can you please suggest an alternative to achieve what i just mentioned.

**Comment by DenisRumyantsev** [comment]
Hi, @kriti218, thanks for reporting this issue. We will take a look at it when we finish working on more prioritized issues.

**Comment by kriti218** [comment]
Hi @DenisRumyantsev, Is there any ETA on this? I am blocked because of this issue as gettasks doesnt give tasks for all the agent jobs and only for one. Early help is really appreciated!
