### ISSUE TITLE
getCommits API call returns extra commits when providing the searchCriteria an array of ids

### ISSUE THREAD

**Issue by xiphoid24** [microsoft/azure-devops-node-api#514]
### Environment

Node version: 16.17.0
Npm version: 8.15.0
OS and version: Windows 10
azure-devops-node-api version: 11.2.0

### Issue Description
We are using the API to get a set of commits. The `getCommits` method accepts a `searchCriteria` object which has an `ids` field. The `ids` field is a sting array of commit ids. When using this method, several commits are returned not just the commits requested by id. Looking at the [git API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get-commits?view=azure-devops-rest-7.1&tabs=HTTP), it accepts a single query parameter named `searchCriteria.ids` which is an array of commit ids. From my testing, the query parameters are not being formatted properly. Instead of creating a single parameter with a comma separated list of commit ids, it is creating a new parameter for each of the commit ids with the parameter name of 
`searchCriteria.ids.{indexInArray}`. This causes the API to ignore the commit ids all together.

### Expected behaviour
When calling the `getCommits` method while providing the `searchCriteria` `ids` field a string array of commit ids it only returns the commits matching the ids provided.

The URL created for the api call is in the following format:
`https://domain.com/CollectionName/ProjectId/_apis/git/repositories/RepositoryName/commits?searchCriteria.ids=CommitId0,CommitId1,CommitId2`

### Actual behaviour
When calling the `getCommits` method while providing the `searchCriteria` `ids` field a string array of commit ids it returns commits where the id matches the ids provided and several others (most likely all).

The URL created for the api call is in the following format:
`https://domain.com/CollectionName/ProjectId/_apis/git/repositories/RepositoryName/commits?searchCriteria.ids.0=CommitId0&searchCriteria.ids.1=CommitId1&searchCriteria.ids.2=CommitId2`

### Steps to reproduce
1. Use the `GitApi` to call the `getCommits` method.
1. Provide the `getCommits` method a `searchCriteria` object with the `ids` field containing a string array of commit ids
    - `{ ids: ["CommitId0", "CommitId1"] }`
1. Log the returned commits
1. Observe it contains more commits than requested

### Suggestion
This seems to be caused by the [queryParamsToStringHelper](https://github.com/microsoft/azure-devops-node-api/blob/master/api/VsoClient.ts#L187) method in the `VsoClient.ts` file. [Here](https://github.com/microsoft/azure-devops-node-api/blob/master/api/VsoClient.ts#L194) it loops all of the properties of the `queryParams` object. Once the recursion gets to an array, it loops over the array setting the `property` to the current index of the array. This creates a single query parameter for each index instead of combining the array into a single query parameter.

This could be fixed by updated the `if` found [here](https://github.com/microsoft/azure-devops-node-api/blob/master/api/VsoClient.ts#L195) to check if `queryParams` is not an array.
#### Example
`if (queryParams.hasOwnProperty(property) && !Array.isArray(queryParams)) {`

This would skip the parameter looping an let the rest of the processing convert the string array into a single comma separated string.

#### Update:
I created a fork, branch and [committed](https://github.com/gregpechiro/azure-devops-node-api/commit/6d0c1f138ed61c5f24228e3652e33f1bac86b4ce) the proposed change

**Comment by kirill-ivlev** [comment]
Hi @gregpechiro!

Thank you for your request, please feel free to create PR to the parent repo, we will test & review it, once we will have capacity.

**Comment by gregpechiro** [comment]
Hey @kirill-ivlev,
Thanks for taking a look. Here is a link to the [PR](https://github.com/microsoft/azure-devops-node-api/pull/516).

**Comment by GravlLift** [comment]
Just ran into this issue myself. @kirill-ivlev, @gregpechiro's PR is a single line change and it's been open for 3 months, what's the holdup?

**Comment by xiphoid24** [comment]
@kirill-ivlev I failed to comment to keep this open. As far as I know this is still an issue. Please reopen this.
