### ISSUE TITLE
Help with finding changes for a deployment in an environment (pipelines)

### ISSUE THREAD

**Issue by stiasta** [microsoft/azure-devops-node-api#517]
Hi!
This is not really a bug or a feature request. I am looking for help to find data that I can find in Azure Devops UI.

Where can I find this list?
![image](https://user-images.githubusercontent.com/3349175/187656935-ea147c4c-c10c-4f36-b7fd-3c53e6de61d9.png)

It can be found under: 
pipelines > environments > [select environment] > deployments > [select deployment] > changes

The url looks like this: 
https://dev.azure.com/[organization]/[team project]/_environments/23/runs?environmentExecutionRecordId=1161&ownerId=76694&definitionId=623&planType=Build&view=jobshistory

In essence. I am trying to get the commits/changes since last deployment to an environment.

**Comment by DmitriiBobreshev** [comment]
Hi @stiasta, unfortunately, probably, [API version 7.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.1) doesn't have a method for it, you can try to get this info through [a build request](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get-changes-between-builds?view=azure-devops-rest-7.1) via [getBuildChanges](https://github.com/microsoft/azure-devops-node-api/blob/master/api/BuildApi.ts#L41) method, and get builds from [getBuilds](https://github.com/microsoft/azure-devops-node-api/blob/master/api/BuildApi.ts#L37) method, but response doesn't provide information about used Environments or Deployments
