### ISSUE TITLE
Git - getPullRequests() not returning 'closedBy' property

### ISSUE THREAD

**Issue by NickMcBurney** [microsoft/azure-devops-node-api#518]
### Environment
Node version:  14.20.0
Npm version:  6.14.15
OS and version: Windows 10
azure-devops-node-api version: 11.2.0

### Issue Description
I'm calling API to get completed pull requests using call:
`const completedPullRequests: GitInterfaces.GitPullRequest[] = await gitApiObject.getPullRequests(MY_REPO_URL, { status: 3 );`

With this I get a list of completed pull requests as expected but it is missing the `closedBy` property which is included in type interface here https://github.com/microsoft/azure-devops-node-api/blob/master/api/interfaces/GitInterfaces.ts#L1570

### Expected behavior
I expect when calling for completed pull requests, I get the identity of the person who completed the pull request with similar format to the `createdBy` proeprty (which is working as expected)

### Actual behavior
 `closedBy` property does not exist on the response for any completed PRs listed

### Steps to reproduce
1. Install package
2. Call `getPullRequests` on a repo with completed PRs
3. Review response - missing `closedBy` property

**Comment by KonstantinTyukalov** [comment]
Hi @NickMcBurney thank you for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon
