### ISSUE TITLE
Add support for `pipelines` API

### ISSUE THREAD

**Issue by dtrts** [microsoft/azure-devops-node-api#519]
Hello, 

I was recently developing a tool to kick off builds in ADO and eventually ran into some limitations with the `BuildApi`. It appears the needs I have would be covered by the similar `pipelines` endpoints: 

https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/

If possible can these be added to the set of generated APIs? 

Thanks for your time,
Douglas

**Comment by KonstantinTyukalov** [comment]
Hi @dtrts thanks for the suggestion!
We've added this request to our backlog and will consider this approach once we've dealt with higher priority tickets

**Comment by Pooja444** [comment]
@KonstantinTyukalov I was recently working on a project and I also found that a client for the 'pipelines' endpoint is missing. I would love to contribute to this issue, is that a possibility?

**Comment by KonstantinTyukalov** [comment]
@Pooja444 all api endpoints are automatically generated internally, so it is probably not possible to contribute here.

**Comment by lekuehn** [comment]
Hi @KonstantinTyukalov,
are there any updates regarding the timeline of the implementation of this feature?

**Comment by jakebailey** [comment]
Not stale (I hope) 🙂

**Comment by skrebsb** [comment]
Is there any update on when the pipelines api will be added? The builds api is limited, particularly concerning queueing pipeline runs against specific versions of resources.

For example, if I have pipeline B that consumes an artifact of pipeline A, there is no means of specifying through the BuildAPI which version of pipeline A I want pipeline B to run against; it will always use `latest`. This can be easily accomplished using the `RunResourcesParameters` of the [run pipeline](https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run-pipeline?view=azure-devops-rest-7.1#runresourcesparameters) endpoint in the `Pipelines` api.

**Comment by 50Wliu** [comment]
Not stale.

**Comment by jakebailey** [comment]
FWIW it's not too hard to do this without "official" support; I read the source for the Go SDK (which does support this feature), and have done:

- https://github.com/microsoft/typescript-benchmarking/blob/0c51259ff2d4869f93329943aed466a1c7e351cf/scripts/src/backfill/common.ts#L67
- https://github.com/microsoft/typescript-bot-test-triggerer/blob/a3763f499ecbab4028334f609f3749bd9bcdc364/GithubCommentReader/index.js#L195

```ts
const verData = await build.vsoClient.getVersioningData(
    "7.1-preview.1",
    "pipelines",
    "7859261e-d2e9-4a68-b820-a5d84cc5bb3d",
    { project, pipelineId },
);
const url = verData.requestUrl;
const options = build.createRequestOptions("application/json", verData.apiVersion);
assert(url);

const response = await build.rest.create(url, args, options);
return response.result as PipelineRunResult;
```

**Comment by jakebailey** [comment]
FWIW doing this with the client without official support isn't too hard; the Go API client supports this feature and it's not hard to just do the same thing with the client: https://github.com/microsoft/typescript-benchmarking/blob/0c51259ff2d4869f93329943aed466a1c7e351cf/scripts/src/backfill/common.ts#L67

**Comment by jakebailey** [comment]
It looks like this was fixed in v13 via #590? (No tags or changelog but the API is present.)

**Comment by johnnyreilly** [comment]
I'm not sure if this is the same thing you're battling with @jakebailey - but I've often found the API isn't 100% covered by the client lib. I found a way to hand roll my way forward which I share in case it's useful 

https://johnnyreilly.com/azure-devops-node-api-git-api-getrefs-wiki-api#handrolled-git-api

**Comment by DmitriiBobreshev** [comment]
Hi @dtrts, @jakebailey, the pipelines API was added in v13 and the new routes for other APIs were added. 
I'm closing the issue, please feel free to reopen it/create a new one in case of errors.
