### ISSUE TITLE
getPagesBatch - paginated data

### ISSUE THREAD

**Issue by SorsOps** [microsoft/azure-devops-node-api#521]
### Environment
Node version: v14.19.1
Npm version:  7.15.1
OS and version: Windows 21H2 OS Build 19044.2006
azure-devops-node-api version: 

### Issue Description
`WikiApi` exposes a method called `getPagesBatch`.  The first parameter is `pagesBatchRequest: WikiInterfaces.WikiPagesBatchRequest` which has a property called `continuationToken` intended for paginated data when the number of pages exceeds a maximum and is included in the response header of the call. Unfortunately `getPagesBatch` does not provide this in the response as it is just the pages it retrieved, with no indication that the number of pages is truncated according to a maximum. Is there someway this can be exposed in the response so subsequent calls can be made to retrieve the rest of the pages?

### Expected behaviour
A token for subsequent calls is provided to indicate data has been paginated is returned

### Actual behaviour
Just the pages are returned as an array with no means to access the header from the response of the rest client

### Steps to reproduce
```
// All uppercase vars are environment variables retrieved elsewhere
import azdev  from 'azure-devops-node-api';
const authHandler = azdev.getPersonalAccessTokenHandler(TOKEN);
const connection = new azdev.WebApi(ORG, authHandler);
const theWiki= await connection.getWikiApi();
const pages = await theWiki.getPagesBatch({}, PROJECT, WIKI_ID)
```

**Comment by SorsOps** [comment]
Not stale. still an issue

**Comment by andriy-viyatyk** [comment]
It is not fixed
