### ISSUE TITLE
Getting error while running samples

### ISSUE THREAD

**Issue by PavanMudigondaTR** [microsoft/azure-devops-node-api#523]
### Environment
Node version: 18.10
Npm version: 18.10
OS and version: MAC OS 
azure-devops-node-api version: 

### Issue Description
Getting error while runner samples

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/86745613/199805949-a608060d-59b8-4924-9e9e-05a687f483cd.png">

### Expected behaviour
samples should work

### Steps to reproduce
1. clone this repo
2.  npm install
3.  npm run samples
4. 
5.

**Comment by DmitriiBobreshev** [comment]
Hi @PavanMudigondaTR, did you manage to resolve your issue?

**Comment by DmitriiBobreshev** [comment]
Hi @PavanMudigondaTR. i'm closing the issue, please feel free to reopen it in case you need help
