### ISSUE TITLE
ITestInterface to add method to update test fields for automation method association

### ISSUE THREAD

**Issue by KanchanPrachwaniTR** [microsoft/azure-devops-node-api#524]
Similar issue opened previously : https://github.com/microsoft/azure-devops-node-api/issues/500
Question : can we have a new method which supports updating fields of a testcase.

Requirement :
we are working on typescript based testcases where we wanted to use azure-devops-node-api to update automated test name and automation status fields based on passed testcase ID.

It will add support for maintaining testcases which are automated using Cypress, Typescript for angular web forms.

Could you please guide how we can achieve this functionality?
If we can have this new feature added on this node api would be really great.

Thanks so much,
Kanchan

**Comment by DmitriiBobreshev** [comment]
Hi @KprachwaniTR, thanks for reporting, as I can see, the current ms API contains only the delete method for testcases in [the Test](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/test-cases/delete?view=azure-devops-rest-7.1&tabs=HTTP) and [the TestPlan](https://learn.microsoft.com/en-us/rest/api/azure/devops/testplan/test-cases/delete?view=azure-devops-rest-7.1&tabs=HTTP) routes, unfortunately, while the API routes are not implemented we cannot implement them in azure-devops-node-api package either, you can create the issue on [Developer Comunity](https://developercommunity.visualstudio.com/home) to speed up the process, and after adding this routes we can add it in the package.

**Comment by KprachwaniTR** [comment]
Hello @DmitriiBobreshev , good day!

I have added a feature request for the same on dev community, link for reference : https://developercommunity.visualstudio.com/t/Include-API-route-to-update-automation-a/10211939

Thanks, 
Kanchan
