### ISSUE TITLE
`getProfile` return type is missing fields

### ISSUE THREAD

**Issue by RLRabinowitz** [microsoft/azure-devops-node-api#525]
### Environment
Node version: 14.17.0
Pnpm version: 6.35.0
OS and version: MacOS 10.15.7
azure-devops-node-api version: 11.2.0

### Issue Description
Profile API's `getProfile` (and other APIs)'s return types don't match the actual return type.

For example, when fetching a profile, the profile contains a `publicAlias`, but it's missing from the return type of `getProfile`
[Get Profile API reference](https://learn.microsoft.com/bs-latn-ba/rest/api/azure/devops/profile/profiles/get?view=azure-devops-rest-4.1&tabs=HTTP)

### Expected behaviour
The return type of `getProfile` (`ProfileInterfaces.Profile`) should match actual profile type. `publicAlias` should exist in the type

### Actual behaviour
`publicAlias` does not exist on the type, even though the field exists on the response.

### Steps to reproduce
1. Use the `ProfileApi`'s `getProfile`
2. Try to access `publicAlias`
3. TS errors, saying there's no such field on `Profile`

**Comment by DmitriiBobreshev** [comment]
Hi @RLRabinowitz, thank's for reporting us, Interface files are generated, when they were generated probably `publicAlias` and some other fields weren't exist. We'll try to fix the issue once we will have enough capacity
