### ISSUE TITLE
Subscription Creation Doesn't Work - `Error: Unable to find FilterMatcher for matcher Microsoft.VisualStudio.Services.Notifications.WebApi.UnsupportedFilter`

### ISSUE THREAD

**Issue by Wassap124** [microsoft/azure-devops-node-api#526]
### Environment
Node version: `v16.15.0`
Npm version: `8.5.5`
OS and version: `MacOS Monterey 12.3.1`
azure-devops-node-api version: `11.2.0`

### Issue Description
Im trying to create simple subscriptions using the `NotificationApi`.

Im using [this documentation](https://learn.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#git.push) as a source for eventTypes.
### Expected behaviour
The above error is thrown when I try to use simple parameters, such as:
```ts
await notificationsApi.createSubscription({
   filter: {
     type: 'git.push'
   }
});
```

### Actual behaviour
This error is thrown
```
Error: Unable to find FilterMatcher for matcher Microsoft.VisualStudio.Services.Notifications.WebApi.UnsupportedFilter
```

**Comment by vmapetr** [comment]
Hi @Wassap124, thanks for your report!
We've added this issue to our backlog. We'll take a look at it once we have enough capacity.
