### ISSUE TITLE
Expose Hooks API

### ISSUE THREAD

**Issue by Wassap124** [microsoft/azure-devops-node-api#527]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
azure-devops-node-api version: 11.2.0

### Issue Description
Very similar to https://github.com/microsoft/azure-devops-node-api/issues/522

The [hooks api](https://learn.microsoft.com/en-us/rest/api/azure/devops/hooks/subscriptions/create?view=azure-devops-rest-7.0&tabs=HTTP) is not exposed by this package, even though it's public and documented.

The types and interfaces are already defined [here](https://github.com/microsoft/azure-devops-node-api/blob/master/api/interfaces/ServiceHooksInterfaces.ts). but again like the aforementioned issue, aren't accessible.
### Expected behaviour
I should be able to call Hooks APIs.

### Actual behaviour
Hooks APIs are not accessible via this package.

### Steps to reproduce
Try to use the Hooks - List API
Notice it doesn't exist in the package

**Comment by vmapetr** [comment]
Hi @Wassap124, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by lesyk-lesyk** [comment]
Any updates on implementing hooks API in this SDK?
