### ISSUE TITLE
Please could 415 be reopened? - it's not fixed

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-devops-node-api#528]
https://github.com/microsoft/azure-devops-node-api/issues/415

Thanks!

**Comment by vmapetr** [comment]
Hi @johnnyreilly, thank you for the report. We'll take a look at this when we have the capacity.

**Comment by vmapetr** [comment]
@johnnyreilly - sure. I reopen the previous ticket and gonna close this one.
