### ISSUE TITLE
Please add example to webhook discord

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [microsoft/azure-devops-node-api#529]
![image](https://user-images.githubusercontent.com/9791364/205463721-477aefb7-9d7c-4c46-8b97-3ac3647a47d1.png)
![image](https://user-images.githubusercontent.com/9791364/205463753-6220b7d2-d5e5-4337-82cf-d1ed91ac4cf7.png)

**Comment by DenisRumyantsev** [comment]
@luizcarlospedrosogomes thanks for suggesting this.
We are currently working on higher-priority issues and we will work on this one as soon as we can
