### ISSUE TITLE
Azure Pipelines task Npm@1 is unable to use corporate SSL proxy certificates

### ISSUE THREAD

**Issue by gregsonian** [microsoft/azure-devops-node-api#531]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: Varies by NodeTool task, but targeting 16.x
Npm version: Vries by NodeTool tas, but targeting 8.x
OS and version: Windows 10 Enterprise Edition 20H2
azure-devops-node-api version: 
azure-devops-agent version: 2.213.2

### Issue Description
Npm@1 task fails when a corporate SSL proxy cert is needed. Isolated the problem to the VsoClient.
VsoClient loses information, e.g. about extra certs, when passing down to RestClient via getVersioningData.

### Expected behaviour
Options that include extra certificate information should be included in the OPTIONS request.

### Actual behaviour
Receive an error when the 

### Steps to reproduce
1. Setup network that requires an SSL Proxy with a signed CA certificate.
2. Add Agent.CAInfo = "signed CA certificate file"
3. Optionally add environment variables NODE_EXTRA_CA_CERTS with the same file path as Step 2.
4. Create a pipeline that uses Npm@1 task.
5. Run the pipeline, receiving an error 'Unable to get local issuer certificate'

### Logs

[azdevops-scrubbed.log](https://github.com/microsoft/azure-devops-node-api/files/10249122/azdevops-scrubbed.log)

**Comment by gregsonian** [comment]
I traced the error through the following modules:
- azure-pipelines-tasks/Tasks/NpmV1/npmcustom.ts
- azure-pipelines-tasks/Tasks/Common/packaging-common/npm/npmregistry.ts
- azure-pipelines-tasks/Tasks/Common/packaging-common/locationUtilities.ts
- azure-devops-node-api/api/VsoClient.ts
    - getVersioningData
    - this.beginGetLocation
    - this.beginGetAreaLocations /* Here, the requestUrl is passed without the WebApi cert info */
- typed-rest-client/lib/RestClient.ts
- typed-rest-client/lib/HttpClient.ts /* ctor here is without options, therefore no cert */

**Comment by ismayilov-ismayil** [comment]
Hi @gregsonian, thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by gregsonian** [comment]
After more debugging, I determined the CA info is passed to the typed-rest-client via `RequestOptions`. I confirmed that the call to `fs` to open the file is being met. There are follow-up errors, for example _Self-signed certificate in certificate chain_, but the reported cause above is not the issue.
