### ISSUE TITLE
The api method _apis/{area}/hubs/{hubName}/plans/{planId}/{resource} is not implemented

### ISSUE THREAD

**Issue by avetkhov** [microsoft/azure-devops-node-api#533]
### Environment
Node version: 14.18.3
Npm version: 8.19.2
OS and version: macOs Ventura 13.1
azure-devops-node-api version: 11.2.0

### Issue Description
The endpoint _apis/{area}/hubs/{hubName}/plans/{planId}/{resource} for the distributedtask area is missing. The description of this one is available in the https://{instance}/{team-project}/_apis request output.

Also a mention of the method can be found in the MS documentation for the InvokeRESTAPI@1 [task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml#where-should-a-task-signal-completion-when-callback-is-chosen-as-the-completion-event).

### Expected behaviour
Implement the method for the TaskApi

### Actual behaviour
Not implemented

**Comment by LiliaSabitova** [comment]
Hi @avetkhov most of the code here is auto-generated from the server-side controllers.
You can try using the [typed-rest-client](https://github.com/microsoft/typed-rest-client/blob/master/README.md) to make a call to the missing apis.

**Comment by avetkhov** [comment]
@LiliaSabitova why this method is excluded from auto-generate process on server side. This is some kind of internal or restricted one?
