### ISSUE TITLE
Npm install failed for Node.js 6

### ISSUE THREAD

**Issue by avetkhov** [microsoft/azure-devops-node-api#535]
### Environment
Node version: 6.17.1
Npm version: 3.10.10
OS and version: ubuntu-18.04
azure-devops-node-api version: 11.2.0

### Issue Description
Npm install command failed for Node.js 6. The latest pipelines get the same issue.

### Expected behaviour
The pipeline has no errors.

### Actual behaviour
The Jon node 6 in the pipeline has failed.

**Comment by LiliaSabitova** [comment]
Hi @avetkhov, could you please describe your issue with more details?

**Comment by avetkhov** [comment]
Hi @LiliaSabitova. I mean the GitHub actions pipeline is failed every time on job named Node 6. You can see at here https://github.com/microsoft/azure-devops-node-api/pulls. I created the pull request to fix this problem
