### ISSUE TITLE
Expose Member Entitlement Management APIs

### ISSUE THREAD

**Issue by neeharika289** [microsoft/azure-devops-node-api#537]
### Environment
Node version: 16.17.0
Npm version: 8.19.2
OS and version: Windows 10
azure-devops-node-api version: 11.2.0

### Issue Description
Member Entitlement Management APIs are not exposed by this package. For ex, creating a user and adding the user to permission groups like projectReader etc.  Azure DevOps Services Rest API public documentation - https://learn.microsoft.com/en-us/rest/api/azure/devops/memberentitlementmanagement/user-entitlements/add?view=azure-devops-rest-7.0&tabs=HTTP

### Expected behaviour
Implement methods for Member Entitlement Management

### Actual behaviour
Methods for Member Entitlement Management are not available

**Comment by LiliaSabitova** [comment]
Hi @neeharika289 most of the code here is auto-generated from the server-side controllers.
You can try using the [typed-rest-client](https://github.com/microsoft/typed-rest-client/blob/master/README.md) to make a call to the missing apis.

**Comment by ivanduplenskikh** [comment]
Hi, @neeharika289
Is this issue still actual for you?
