### ISSUE TITLE
Looking for api method similar to GetTestResolutionStates.

### ISSUE THREAD

**Issue by quldude** [microsoft/azure-devops-node-api#542]
Is there a way to get resolution states similar to how this api returns when the web ui calls it?
`https://dev.azure.com/{org}/{projectid}/_api/_testresult/GetTestResolutionStates?__v=5`

**Comment by DmitriiBobreshev** [comment]
Hi @quldude, azure-devops-node-api is mostly autogenerated, so if it's not present in [msdoc ](https://learn.microsoft.com/en-us/rest/api/azure/devops/testresults/result-meta-data/query?view=azure-devops-rest-7.0&tabs=HTTP), there probably now presented in azure-devops-node-api, all test API located in [ITestApi](https://github.com/microsoft/azure-devops-node-api/blob/master/api/TestApi.ts#L20), and possible you can work with [getTestResults](https://github.com/microsoft/azure-devops-node-api/blob/master/api/TestApi.ts#L60), but I'm not 100% sure that it fully suits your case.

You can try to create an issue on [devcommunity](https://developercommunity.visualstudio.com/AzureDevOps?preview=true) with this suggestion, but unfortunately, we can't help you with it.
