### ISSUE TITLE
Custom Server URL is ignored

### ISSUE THREAD

**Issue by XVincentX** [microsoft/azure-devops-node-api#544]
Most of the functions such as `getGitAPI` takes an optional server URL as the first parameter. 

Apparently such parameter gets happily ignored and the final request goes to the `defaultUrl` provided in the constructor anyway. 

I dug in the source code and it appears to be because the `_getResourceAreaUrl` function returns something cached during the construction of the object.

**Comment by vmapetr** [comment]
Hi @XVincentX! thank you for reporting this.
We are currently working on higher-priority issues and we will work on this one as soon as we can.

**Comment by johnnyreilly** [comment]
Bet it's not stale
