### ISSUE TITLE
TestApi.updateTestResults() returning 500 from server

### ISSUE THREAD

**Issue by SamJBarney** [microsoft/azure-devops-node-api#546]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 14.16.1
Npm version: 6.14.12
OS and version: Mac OS 12.6.2
azure-devops-node-api version: 12.0.0

### Issue Description
The endpoint TestApi.updateTestResults() points to started returning a 500 on Tuesday with no changes to my code.

### Expected behaviour
Server should return a success with the updated TestCaseResult array

### Actual behaviour
Server returns a 500 with the following message:
```
Error: Value cannot be null.
Parameter name: result
```

### Steps to reproduce
1. Retrieve the test point ids for n number of suites
2. Create a test run
3. Retrieve the TestCaseResult array for the run from the server
4. Map the results to objects with the following properties: { id, automatedTestName, outcome, completedDate, testPoint, testCaseTitle, testCaseRevision}
5. Call TestApi.updateTestResults() with the data along with the other required arguments.

### Logs
Here is the json returned from the server:
```
{
    "$id": "1",
    "innerException": null,
    "message": "Value cannot be null.\r\nParameter name: result",
    "typeName": "Microsoft.VisualStudio.Services.Common.VssServiceException, Microsoft.VisualStudio.Services.Common",
    "typeKey": "VssServiceException",
    "errorCode": 0,
    "eventId": 3000
}
```

**Comment by max-zaytsev** [comment]
@SamJBarney thanks for reporting. We'll take a look at this issue when we have enough capacity

**Comment by DmitriiBobreshev** [comment]
Hi @SamJBarney, the error usually means that you sent an array with TestCaseResult which contains a null value inside that array, could you please check that the sent array contains only [TestCaseResults](https://github.com/microsoft/azure-devops-node-api/blob/master/api/interfaces/TestInterfaces.ts#L2581)?

**Comment by DmitriiBobreshev** [comment]
Hi @SamJBarney, do you have any updates to share?
