### ISSUE TITLE
getPagesBatch doesn't support continuationToken

### ISSUE THREAD

**Issue by davea38** [microsoft/azure-devops-node-api#548]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 16.13.1
Npm version: npm 9.1.2, 
OS and version: Windows 10 21H2
azure-devops-node-api version: 12.0.0

### Issue Description
IWikiApi.getPagesBatch does not return a continuationToken

### Expected behaviour
IWikiApi.getPagesBatch **should** return a continuationToken as part of its response enabling repeated calling of the method in a do while loop

### Actual behaviour
The current method returns an Promise<WikiInterfaces.WikiPageDetail[]> type, which only contains results. It should actually contain the continuationToken returned by the webservice as well as the results so if there are more than top X, we can list the rest of the wiki pages

### Steps to reproduce
1. Connect to DevOps
2. Call getWikiApi method
3. Call getPagesBatch with a small value for top
4. Be annoyed when you can only get the first X

### Logs
N/A

**Comment by davea38** [comment]
Anyone? The wiki I'm using has well over 100 pages of content so my only option currently is to write some custom code that calls the web service and handles the paging token correctly

**Comment by DmitriiBobreshev** [comment]
Hi @davea38, sorry for the delay, I'm afraid that the method and the WikiApi.ts file are [autogenerated](https://github.com/microsoft/azure-devops-node-api/blob/master/api/WikiApi.ts#L7), so, unfortunately, we can't modify the method to include the header "x-ms-continuationtoken" in the [response ](https://learn.microsoft.com/en-us/rest/api/azure/devops/wiki/pages-batch/get?view=azure-devops-rest-7.0&tabs=HTTP#request-body), the good news that [IRestResponse ](https://github.com/microsoft/azure-devops-node-api/blob/master/api/WikiApi.ts#L838) includes response headers in it, so, for now, you can only create some class which will extend WikiApi and modify getPagesBatch method inside it.

**Comment by davea38** [comment]
Hi @DmitriiBobreshev , thank you for the reply :) It turned out that the last id sent in a batch is the continuation token needed to be sent with the next batch, so all I needed to do was check to see if the number of current items received % batch size === 0 then try to get the next batch using the last id in the current batch.

Not the most efficient code in the world, but for me it's not an issue.
