### ISSUE TITLE
Service Principal Authentication

### ISSUE THREAD

**Issue by afscrome** [microsoft/azure-devops-node-api#551]
### Environment
Node version: v18.15.0
Npm version: 9.5.0
OS and version: Ubuntu 22.04 WSL
azure-devops-node-api version: 

### Issue Description
With support for Service Principal & Managed Identity has recently been recently added to Azure Devops, I was hoping to see some way to use `@azure\identity`'s `TokenCredential` class for authentication with this library.

https://devblogs.microsoft.com/devops/introducing-service-principal-and-managed-identity-support-on-azure-devops/

### Expected behaviour
A way of using the `TokenCredential` implementations from `@azure\identity` to authenticate with Azure devops.  e.g.

```ts
const authHandler = getAzureIdentityHandler(token: TokenCredential)
```

### Actual Behaviour
There seems to be some level of support for bearer authentication, however that takes a static token.  This means if the auth handler lasts for a long time, the token may expire in progress.

https://github.com/microsoft/azure-devops-node-api/blob/9a1de110df3020c8f08984c2f8140f2c32be85f1/api/WebApi.ts#L58-L60

### Steps to reproduce
N/A

### Logs
N/A

**Comment by KonstantinTyukalov** [comment]
Thanks for the reporting! We're currently working on higher priority issues, but we will get back to this one soon

**Comment by jakebailey** [comment]
I feel like this should be reopened; my current workaround is to manually keep around `expiresOnTimestamp` from the credential and just recreate the API client when it's getting too close to expired. (Disclaimer: I haven't tested it yet, but I don't see why that wouldn't work. It's just frustrating to have to manually implement.)
