### ISSUE TITLE
Organization URL gets trimmed as part of the Create Test Run Method

### ISSUE THREAD

**Issue by saikiran40cs** [microsoft/azure-devops-node-api#552]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 18.16.0
Npm version: 9.5.1
OS and version: Windows 10
azure-devops-node-api version: 12.0.0

### Issue Description
The Organization URL gets trimmed as part of the Create Test Run Method
const _orgUrl: string = "https://dev.azure.com/Org-1/";
const project: string = "Project%25Name"

### Expected behaviour
Able to create test run

### Actual behaviour
404 error is thrown as we have improper URL passed

### Steps to reproduce
1. Create the Azure DevOps PAT Token
2. Create the instance for Web Api using Org URL and Token Handler
3. Create the instance for TestApi
4. Create the RunCreateModel

![image](https://github.com/microsoft/azure-devops-node-api/assets/6228048/814d1d0e-c021-4725-90c1-7a975b8f22c4)

### Logs
![image](https://github.com/microsoft/azure-devops-node-api/assets/6228048/d2f90db9-4392-436a-a659-9aa103ecc6c7)

**Comment by LiliaSabitova** [comment]
Hi @saikiran40cs, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by saikiran40cs** [comment]
This issue is resolved. I had fixed this issue. You can close the ticket
