### ISSUE TITLE
getTestResultsByBuild throws 401 error

### ISSUE THREAD

**Issue by jkomban** [microsoft/azure-devops-node-api#553]
### Environment
Node version: v17.2.0 
Npm version: 8.1.4
OS and version: Windows 11 Enterprise, 22H2
azure-devops-node-api version: 12.0.0

### Issue Description
I am using `azure-devops-node-api` module for the first time. I am trying to run the below function(getTestResultsByBuild) but it fails with 401. I checked all permissions to the PAT. Below is the code.

### Expected behaviour
It should give results or empty.

### Actual behaviour
Throws 401 error. I gave full permissions to the PAT.

### Steps to reproduce

> async function TestAzureDevOpsTestApi() {
>
> const authHandler = AzureDevOpsApi.getPersonalAccessTokenHandler(PAT);
>   const connection = new AzureDevOpsApi.WebApi(PROJECT_URL, authHandler, options);

>   const testApi = await connection.getTestApi();
>   const buildApi = await connection.getBuildApi()
 >  try {
>     const buildResults = await buildApi.getBuild(PROJECT_NAME, BUILD_NUMBER);
>    console.log(`Build Results: Repo Type ${buildResults.repository.type}`);
> 
>   // Below test api is working fine.
>     const testResultsById = await testApi.getTestRunById(PROJECT_NAME, 37464);
>     console.log(`Total test count: ${testResultsById.totalTests}  ->  + ${testResultsById.state}`);
> 
>     // Below test api throws 401 error.
>     const testResults = await testApi.getTestResultsByBuild(PROJECT_NAME, BUILD_NUMBER);
>     console.log(testResults);
>   } catch (e) {
>     console.error(e.message);
>     console.log(e);
>   }
}
> 
> 
> TestAzureDevOpsTestApi();

### Logs
![image](https://github.com/microsoft/azure-devops-node-api/assets/23691998/986fdbf0-3755-4d37-bbb9-3feabd068462)

**Comment by MAUH96** [comment]
I have the same issue, have you guys looked into this?

Error occurred: Error: Failed request: (401)
    at RestClient.<anonymous> (/Users/myname/Documents/project - c p/Integration/Repo/Deployments/node_modules/typed-rest-client/RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/myname/Documents/project folder/Integration/Repo/Deployments/node_modules/typed-rest-client/RestClient.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 401

**Comment by jkomban** [comment]
The issue is should not be stale.

**Comment by ivanduplenskikh** [comment]
@jkomban could you please check **getTestResultsApi**?
```js
const testApiResults = await connection.getTestResultsApi();
const testResults = await testApiResults.getTestResultsByBuild(PROJECT_NAME, BUILD_NUMBER);
```

**Comment by ivanduplenskikh** [comment]
@jkomban, I'm closing this issue for now - feel free to reopen if it is still relevant for you.
