### ISSUE TITLE
Tags and Releases are not maintained

### ISSUE THREAD

**Issue by tintse-thxsky-MSFT** [microsoft/azure-devops-node-api#554]
When I download from the latest release page https://github.com/microsoft/azure-devops-node-api/releases/tag/v6.7
The pages says it is v6.7, and the downloaded filename is 6.7, but when I open the package.json the version field is 11.2.0

This is really confusing and should get fixed/clarified asap.

**Comment by kirill-ivlev** [comment]
Hi @tintse-thxsky-MSFT,
Thank you for reporting it, we will have a look
