### ISSUE TITLE
Add support for Graph API

### ISSUE THREAD

**Issue by XVincentX** [microsoft/azure-devops-node-api#561]

**Comment by aleksandrlevochkin** [comment]
Hi @XVincentX this Node API doesn't support Graph API by design, but you still may use it directly via REST API https://learn.microsoft.com/en-us/rest/api/azure/devops/graph/

**Comment by cal5barton** [comment]
Why is this by design, when there are interfaces for Graph entities but no API client?

**Comment by cal5barton** [comment]
Why is this by design, when there are interfaces for Graph entities but no API client? The C# version of this wrapper supports it out of the box.
