### ISSUE TITLE
"getDeployments" is not returning more than 100 deployments per call.

### ISSUE THREAD

**Issue by paolagutierz** [microsoft/azure-devops-node-api#562]
I am using the releaseApi.getDeployments method to retrieve deployment information from Azure DevOps. However, I noticed that the maximum quantity of values returned is limited to 100, even when I pass the top parameter with a value of 200. This means that I cannot fetch more than 100 deployments in a single call.

This becomes a significant challenge for our reporting requirements at the company, as we need to generate a comprehensive report that includes all deployments executed during a sprint, and the total number of deployments often exceeds 2000.

**Comment by LiliaSabitova** [comment]
Hi @paolagutierz most of the code here is auto-generated from the server-side controllers.
You can try using the [typed-rest-client](https://github.com/microsoft/typed-rest-client/blob/master/README.md) to find a suiable api.
