### ISSUE TITLE
Using Managed Identities?

### ISSUE THREAD

**Issue by dylanmccurry-msft** [microsoft/azure-devops-node-api#563]
Hi, is it possible to utilize this library using Managed Identities?

**Comment by kirill-ivlev** [comment]
Hi @dylanmccurry-msft thank you for your question
It is not tested by our team now, but [according to this document](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops#3-access-azure-devops-resources-with-an-azure-ad-token) you may use it as a regular token
