### ISSUE TITLE
VsoClient and not existing ADO

### ISSUE THREAD

**Issue by szwalkowski** [microsoft/azure-devops-node-api#565]
If you try to create clients with not existing ADO you get unexpected error

"TypeError: Cannot read property 'value' of null
    at /workspace/node_modules/azure-devops-node-api/VsoClient.js:124:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"

This is the place where we have problem: 
https://github.com/microsoft/azure-devops-node-api/blob/master/api/VsoClient.ts#L167C30-L167C30

res response:

{
  "statusCode": 404,
  "result": null,
  "headers": {}
}

There's no way you can call value on result. And the error is terrible, we should get some kind of 404 error

**Comment by KonstantinTyukalov** [comment]
Hi @szwalkowski thanks for reporting! The patch is ready: https://github.com/microsoft/azure-devops-node-api/pull/567
Will be merged soon
