### ISSUE TITLE
HTTP 503 error retry mechanism needs to be added in case of failure.

### ISSUE THREAD

**Issue by saikiran40cs** [microsoft/azure-devops-node-api#566]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 18.x
Npm version: 9.8.1
OS and version: 10
azure-devops-node-api version: 12.1.0

### Issue Description
HTTP 503 error retry mechanism needs to be added in case of failure.

### Expected behaviour
When a 503 error is thrown there must be one retry to check if it is actually a server error. as subsequent payloads are working

### Actual behaviour
  statusCode: 503,
  responseHeaders: {}

### Steps to reproduce
1. Create test run, test result 
2. Update test result using the const testResult = await testApiObject.updateTestResults(testResultDetails, this.projectName, testRunId);

### Logs
<body>
        <header>
            <img class="logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABMklEQVR4Xu3UrUtDYRTH8eeMweCGccF/YNFNNmw2NZpMiyYVtKhgEIsvYQwmGGwTTIOlLQgWwe5AxffgWzBZLJsYRMTHb/DCZduzHbzVH3w4cOD8ynO5pl+stSnswTOKxKDJDE4pHfpzIcc+FljswyCDE3bTvQqlrUQYY5hFHgnHXRXzIvIeukshFxQlsIonaPKILZRxjLfgICgsOw6/cI0KljCK5O8NOhPHFJ1z+MAVLnGOC9yICHt94tiFQYnjTRMxMXhQRF8YPf+F4yji01qbgWdIZBQN4BkWrzhDHdtYxCSG4ff6sKWtNMdoKD6lFl6Qdv0cwqV5Rg0Eet9Y7ngUEakzCjB4wK2irIkJbndcr7yBAzREJMtMY91Rfo8Ryo76PVISK132g1jDHQ7hh+9+AMwVLZmudBWFAAAAAElFTkSuQmCC">
            <span class="title">Azure DevOps Services</span>
        </header>
        <div id='content'>
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUEAAAFBCAYAAADpDh0xAAAACXBIWXMAAAsSAAALEgHS3X78AAAgAElEQVR42u3dfVRc5aHv8d9MAgESXpKIecMyKpG8GqKJ5q7llbGxeqq1IZq2R9sKUU/bq/ZKT+ui1h5Demw1q96esTWu9h41RI+m1tRAPWq1WsFzl0eNRpDmBUOboeYdSYBAIBBm7h+zgeFlXhj2zGzg+1nLZYA9e/Z+ZvPjedvPtnm9XgHARGWnCAAQggBACAIAIQgAhCAAEIIAQAgCACEIAIQgABCCAEAIAgAhCACEIAAQggBACAIAIQgAhCAAEIIAQAgCACEIAIQgABCCAEAIAgAhCACEIAAQggBACAIAIQgAhCAAEIIAQAgCACEIAIQgABCCAEAIAgAhCACEIAAQggBACAIAIQgAhCAAEIIAQAgCACEIAIQgABCCAEAIAgAhCACEIAAQggBACAIAIQiAEAQAQhAACEEAIAQBgBAEAEIQAAhBACAEAYAQBABCEAAIQQAgBAGAEAQAQhAACEEAIAQBgBAEAEIQAAhBACAEAYAQBABCEAAIQQAgBAGAEAQAQhAACEEAIAQBgBAEAEIQAAhBACAEAYAQBABCEAAIQQAgBAGAEAQAQhAACEEAIAQBgBAEAEIQAAhBACAEAYAQBABCEAAIQQAgBAGAEAQAQhAAJEmTKQJYRY6rziHJMejb7vriXDelg2ixeb1eSgGxDrsMSU5JeX7/Tw/xsgZJbkmVkirri3MrKUkQghhrwVdg/LfGpN1WSCqrL84tp4RBCMLKTdxSI/zSo/Q2DZLKJLnqi3ObKXUQgrBKzc8lqTCGb9tiBGEpnwAIQcQzAIuN2l96nA6hQVIR/YYgBBGPpm+ZpHyLHNJGaoUgBBGrAHRKKo9j7S+QKkkF9BUiECZLw4wALJL0lgUDUEattNLoowSoCSIqAbhlDBxqi6Q8Jl6DmiAm...
            <div id='message'>
                <h2>Sorry! Our services aren't available right now.</h2>
                <p>We're working to restore all services as quickly as possible. Please check back soon.</p>
                <p class='subheading'>To see the latest status on our services, please visit our <a href="[https://go.microsoft.com/fwlink/?linkid=242573">support](https://go.microsoft.com/fwlink/?linkid=242573%22%3Esupport) page</a>.</p>
            </div>
            <div id='errorref'>
                <span>
                    Ref A: 578F632E34D343B09001185201CA97CB Ref B: BL2AA2030108007 Ref C: 2023-09-01T08:47:11Z
                </span>
            </div>
        </div>
    </body>
</html>

    at RestClient.<anonymous> (C:\a\1\s\node_modules\typed-rest-client\RestClient.js:202:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\a\1\s\node_modules\typed-rest-client\RestClient.js:6:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 503,
  responseHeaders: {}
}

**Comment by KonstantinTyukalov** [comment]
Hi @saikiran40cs thank you for the feedback. We're working on higher priority issues now, but we'll get back to this one soon.

**Comment by saikiran40cs** [comment]
This issue still exists and no update has been provided so far
