### ISSUE TITLE
getCommitDiffs does not accept the whole payload

### ISSUE THREAD

**Issue by Om4n3k** [microsoft/azure-devops-node-api#573]
### Environment
Node version: 18.14.2
Yarn version: 1.22.19
OS and version: Win 11
azure-devops-node-api version: 12.1.0

### Issue Description
getCommitDiffs from gitApi ignores baseVersionDescriptor and targetVersionDescriptor payloads
`
gitClient.getCommitDiffs(this.repoId, this.project, true, 100, 0, {
          baseVersion: 'ADC_Wizard_15894,
        }, {
          targetVersion: 'main'
        })
`
Even after adding another properties (baseVersionType, baseVersionOptions, etc.), following URL gets generated:
![image](https://github.com/microsoft/azure-devops-node-api/assets/51209348/06faaae9-699b-4703-a18e-f94234c41ff9)
### Expected behaviour
The url should look like this
![image](https://github.com/microsoft/azure-devops-node-api/assets/51209348/d71107e2-5ebc-43af-a2cc-4b5e5d908dad)
There should be differences between those branches
![image](https://github.com/microsoft/azure-devops-node-api/assets/51209348/481bf5fb-2171-48d6-996a-5ceb49fdee8f)

### Actual behaviour
There are no differences found due to missing base and target branches

### Steps to reproduce
1. Initialize the handler with PAT and org url
2. Provide payload to the getCommitDiffs method as above

**Comment by DmitriiBobreshev** [comment]
Hi @Om4n3k, thanks for the feedback, the GitApi is [fully generated ](https://github.com/microsoft/azure-devops-node-api/blob/master/api/GitApi.ts#L7) so we can't patch them by hand now. We'll try to fix it once we'll have enough time
