### ISSUE TITLE
Can't get azure-devops-node-api working with a React project

### ISSUE THREAD

**Issue by ClydeDz** [microsoft/azure-devops-node-api#575]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 20.10.0
Npm version: 10.2.3
OS and version: Windows 11
azure-devops-node-api version: 2.1.0

### Issue Description

Tried installing this npm package in a React project but it would have multiple build issues. After resolving them and [providing a fallback](https://github.com/ClydeDz/azuredevops-node-react-demo/blob/main/webpack.config.js#L32-L46) after reading solutions online, I'm now running into a browser console error originating from the package. 

I ran a node only project and that seems to be working. Its only when trying to install in a React project and webpack perhaps? 

### Expected behaviour

I'd expect the npm package to allow me use a React project as a frontend to communicate with Azure devops backend and display contents on my react website.

### Actual behaviour

Errors described above

### Steps to reproduce
1. Get the latest from https://github.com/ClydeDz/azuredevops-node-react-demo
2. npm install 
3. npm build
4. npm start
5. You should see no output in the browser but instead console errors

### Logs

![image](https://github.com/microsoft/azure-devops-node-api/assets/13506613/9b814ef7-c8a2-4a5f-801f-fb7d3e6353f9)

**Comment by ivanduplenskikh** [comment]
Hi @ClydeDz thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
