### ISSUE TITLE
Use secure file name as reference data instead of id

### ISSUE THREAD

**Issue by aklakina** [microsoft/azure-devops-node-api#593]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: v18.14.0
Npm version: 9.3.1
OS and version: windows 10 22H2
azure-devops-node-api version: 2022.1

### Issue Description

When updating a secure file (deleting and then reuploading with the new content with the same name) every classic pipeline breaks that was using that secure file.
### Expected behaviour

The classic pipelines should hold the reference for the new secure file.
### Actual behaviour

The classic pipelines referencing the old secure file break.
### Steps to reproduce
This issue is strongly related to https://github.com/microsoft/azure-pipelines-tasks-common-packages/issues/309
1. upload secure file
2. create classic pipeline with a secure file download task
3. set the secure file created in step 1 to be downloaded
4. save pipeline
5. delete secure file and reupload

### Fix

#591 
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azure-devops-node-api/pull/591
```

**Comment by vmapetr** [comment]
Hi @aklakina - thanks for reporting! 
We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by aklakina** [comment]
The issue is still present.
