### ISSUE TITLE
Add work item batch update function to `WorkItemTrackingApi`

### ISSUE THREAD

**Issue by csvtuda** [microsoft/azure-devops-node-api#594]
Hey there,

We're currently trying to add a few automated update utilities to our frameworks, for example for automatically setting the automation status of test cases. We know that it is possible to update many work items in a single batch request, as specified [here](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/?view=azure-devops-rest-7.0#update-workitems-in-batch) or [here](https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/WorkItemBatchUpdate?view=azure-devops-rest-5.0). The endpoint also does what it's supposed to do (verified in Postman).

Unfortunately, this neat library does not provide such a method in the `WorkItemTrackingApi`. There is only a function for updating a single work item and for retrieving work items in a batch request.

Would it be possible to add a function for updating work items in a batch request, as specified in the documentation?

---

> 1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues

As far as I can see, this was never discussed: https://github.com/microsoft/azure-devops-node-api/issues?q=work+item+batch+

### Environment
Node version: v18.12.1
Npm version: 8.19.2
OS and version: Windows 10 Pro 22H2 19045.4291
azure-devops-node-api version: 13.0.0

**Comment by aleksandrlevochkin** [comment]
Hi @csvtuda! Thank you for reaching out regarding this enhancement.  We are currently working on higher-prioritized issues, but we will get back to this one as soon as we can.
