### ISSUE TITLE
Update Release State

### ISSUE THREAD

**Issue by vargdieg** [microsoft/azure-devops-node-api#595]
### Environment
Node version: 20.11.1
Npm version: 10.2.4
OS and version: Windows
azure-devops-node-api version: 12.4.0

### Issue Description
Im trying to change the status of an release from an active state to an abandon state using the azure-devops-node-api, using the releaseapi.updateRelease() function

### Expected behaviour
The expected behaviour is that the status of the release changing from active to abandon, and if i get the release information, i get the status as abandoned

### Actual behaviour
The updateRelease() executes satisfactory, and when obtaining the release after the execution, it is not noted the difference

### Steps to reproduce
1.  Get the release API
2.  Obtain the information about an existing release
3.  Changing the status of the obtained release to the desired state (abandoned)
4. Usign the updateRelease function, update the release information
5. Obtain again the information of the release (the status did not change)

### Logs
```
const releaseapi: IReleaseApi = await getReleaseApi();

const release: Release = await releaseapi.getRelease(projectId, releaseId); //release.status = 2 (Active)
release.status = ReleaseStatus.Abandoned; //release.status = 4
             
const result = await releaseapi.updateRelease(release,projectId,releaseId);//result.status = 2 (Active)
```

**Comment by aleksandrlevochkin** [comment]
Hi @vargdieg, thank you for reporting this issue. We are working on higher-prioritized issues at the moment, but we will get back to this one as soon as possible.
