### ISSUE TITLE
GitPullRequestSearchCriteria interface (and probably others) out of date

### ISSUE THREAD

**Issue by deerware** [microsoft/azure-devops-node-api#599]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `azure-devops-node-api@11.2.0` for the project I'm working on.

The [GitPullRequestSearchCriteria](https://learn.microsoft.com/en-us/javascript/api/azure-devops-extension-api/gitpullrequestsearchcriteria) interface seems to be out of date.

Here is the diff that solved my problem. queryTimeRangeType enum is not specified, just a quick workaround so I can get working.

```diff
diff --git a/node_modules/azure-devops-node-api/interfaces/GitInterfaces.d.ts b/node_modules/azure-devops-node-api/interfaces/GitInterfaces.d.ts
index 817e555..0e19174 100644
--- a/node_modules/azure-devops-node-api/interfaces/GitInterfaces.d.ts
+++ b/node_modules/azure-devops-node-api/interfaces/GitInterfaces.d.ts
@@ -1862,6 +1862,18 @@ export interface GitPullRequestSearchCriteria {
      * Whether to include the _links field on the shallow references
      */
     includeLinks?: boolean;
+    /**
+     * If specified, filters pull requests that created/closed before this date based on the queryTimeRangeType specified.
+     */
+    maxTime?: Date;
+    /**
+     * If specified, filters pull requests that created/closed after this date based on the queryTimeRangeType specified.
+     */
+    minTime?: Date;
+    /**
+     * The type of time range which should be used for minTime and maxTime. Defaults to Created if unset.
+     */
+    queryTimeRangeType?: 'created' | 'closed';
     /**
      * If set, search for pull requests whose target branch is in this repository.
      */
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vmapetr** [comment]
Hi @deerware thanks for reporting! 
We are working on more prioritized issues at the moment, but will get back to this one soon.
