### ISSUE TITLE
How can you specify what api version to use. I'm getting different results from when I just do a postman call against the rest api. 

### ISSUE THREAD

**Issue by duncanmapes** [microsoft/azure-devops-node-api#603]
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
Node version: 
Npm version: 
OS and version: 
azure-devops-node-api version: 

### Steps to reproduce
1. 
2. 
3. 
4. 
5.

**Comment by KonstantinTyukalov** [comment]
Hi @duncanmapes, you can use the `?api-version=<version>` query param to use specific api version in your direct http calls.
Ref: https://learn.microsoft.com/en-us/rest/api/azure/devops#components-of-a-rest-api-requestresponse-pair

You can't choose what api version to use in this library as all types and methods rely on the specific api version usage.

Please let me know if you any additional questions

**Comment by duncanmapes** [comment]
noted, thanks
