### ISSUE TITLE
Resetting Reviewer vote to 0 via GitAPI has no effect

### ISSUE THREAD

**Issue by tommywilkinson** [microsoft/azure-devops-node-api#611]
### Environment
Node version: 18.15.0
Npm version: 9.5.0
OS and version: both windows 11 (current) and linux (ubuntu current LTS)
azure-devops-node-api version: 10.2.2

### Issue Description
Updating reviewer vote has no effect via node API. 

### Expected behavior
Updating a reviewer vote to 0 should reset the vote in the pull request for a given reviewer. 

### Actual behavior
No effect on reviewer vote status after performing vote reset REST call. 

### Steps to reproduce
1. Create an ADO PR
2. Have an "Approved" reviewer in that PR
3. Use rest API to attempt to update that reviewer's vote to 0, using `updatePullRequestReviewer`
4. Observer that REST call completes successfully, but vote status will not have been reset (will still be "Approved") 

### Logs
Can provide MSFT internal pipeline agent logs upon request.

**Comment by ismayilov-ismayil** [comment]
Hi @tommywilkinson,  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by ismayilov-ismayil** [comment]
Hi @tommywilkinson 
After investigation I realized that the feature works as expected. 
Please consider that, you have to use correct vote.id,  and PAT owner (which you are using in the node-api) can reset their own vote.
```
    let webApi: nodeApi.WebApi = await common.getWebApi();
    let gitApiObject: GitApi.IGitApi = await webApi.getGitApi();
    const repos: GitInterfaces.GitRepository[] = await gitApiObject.getRepositories("lab");
    const repo: GitInterfaces.GitRepository = repos[6]
    const pullRequestCriteria: GitInterfaces.GitPullRequestSearchCriteria = <GitInterfaces.GitPullRequestSearchCriteria>{};
    const pullRequests = await gitApiObject.getPullRequests(repo.id, pullRequestCriteria);

    const pullRequest =  pullRequests[0]
    const votes = await gitApiObject.getPullRequestReviewers(repo.id, pullRequest.pullRequestId);
   
    let vote: GitInterfaces.IdentityRefWithVote[] = [{vote:0, id:votes[0].id}]
    await gitApiObject.updatePullRequestReviewers(vote, repo.id, pullRequest.pullRequestId )  
```
![Image](https://github.com/user-attachments/assets/95e730de-f86f-400f-b60d-80341926d48e)


closing this now, please don't hesitate to re-open or create new one
