### ISSUE TITLE
Request option typedefs should be marked optional

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/azure-devops-node-api#72]
When specifying options for a request, the tyepdefs like [`GitInterfaces.GitQueryCommitsCriteria`](https://github.com/Microsoft/vsts-node-api/blob/master/api/interfaces/GitInterfaces.ts#L1082-L1143) require every single parameter to be filled out.  Instead these should all be marked as optional.

For example, if I wanted to get the first git commit on a certain day this is all I need to specify:
```ts
const commitQueryOptions: any = {
    $top: 1,
    fromDate: "2017-01-03T00:00:00.000Z",
    toDate:   "2017-01-03T23:59:59.999Z",
    itemVersion: {
        versionOptions: GitInterfaces.GitVersionOptions.PreviousChange,
        versionType: GitInterfaces.GitVersionType.Commit
    }
};

vso.getGitApi().getCommits(repo.id, commitQueryOptions).then(() => {
  //do stuff...
})
```

At first I tried to provide empty strings and `null` for the options I didn't care about, but that wouldn't compile since it didn't line with twith the typedefs. TFS also gave me back `400` errors saying that certain data was required to be set to `null`

However, the above code works for now but I'm not a fan of being forced to use the `any` type (weak typing) when the real typedefs exist.  It just seems silly to require the dev to fill out 20+ options that they don't care about, especially since it actually works just fine when you don't.

**Comment by david-richards** [comment]
+ 1.
I've reverted my scripts calling the API to use JavaScript to get around exactly this problem.

Requiring a ton of params which the rest api docs doesn't require is really inconsistent, and passing them is likely to make my code break against new versions of the api (plus for some calls it's impractically large & noisy).

I'd say the library is almost unusable with Typescript at the moment

**Comment by stephenmichaelf** [comment]
Thanks for the feedback, I will take a look into this and see if we can get it fixed.

**Comment by damccorm** [comment]
This is also being tracked in #74, so I'm going to close here.
