### ISSUE TITLE
Include a more specific user agent string in HTTP calls

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/azure-devops-node-api#90]
Need to include a more descriptive user agent string in calls from this client. This will help us better understand how/where people are using the library.

The user-agent string should always include information about the client library, but also information about the tool/app/service using the library (optionally). This might be specified like this:

```
var requestSettings: IWebApiRequestSettings = {
 
    productName = "MyTool",
    productVersion = "12.322"
   
};

var webApi  = new WebApi(connectionUrl, creds, requestSettings);
```

if product name is specified ...

```
   {ToolName}/{ToolVersion} (vsts-node-api {VstsNodeApiVersion}; {osname} {osversion})
```

Otherwise ...

```
   vsts-node-api/{VstsNodeApiVersion} ({osname} {osversion})
```

Examples:

* `vsts-node-api/6.1.1-preivew (Windows 10.01232)`
* `tfx-cli/0.3.49 (vsts-node-api 14.1223.2; Windows 10.1232)`

**Comment by willsmythe** [comment]
@scottdallamura / @bryanmacfarlane  - take a look and let's close on this. We can evolve it over time as more information is needed. The version of the client, the OS, and optional "tool" information is the main info we need to start seeing in the telemetry on the server.

**Comment by stephenmichaelf** [comment]
Working on this now, can create Issue in tfx-cli too.

**Comment by stephenmichaelf** [comment]
And add L0 tests once that infrastructure is setup. Good candidate for a Nock test to make sure the header is set correctly with/without tool being specified.

**Comment by damccorm** [comment]
@stephenmichaelf I added a PR to address this, I'm going to hold off on adding testing until #218 is approved (adding a setup for testing) to avoid issues merging them together.
